// This source code was auto-generated by GDataSetGenerator478, Version=490.1.0.0
namespace Gordic.Report.Interface {
    using Gordic.General;
    using Gordic.General.ApplicationInterface;
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    /// <summary>Autogenerated.</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("GGinvfofDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
    public partial class GGinvfofDataSet : global::Gordic.General.GDataSet, GeneratedBy.GDataSetGenerator478 {
        /// <summary>Autogenerated.</summary>
        private SeznamDataTable tableSeznam;
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SeznamDataTable Seznam {
            get {
                return this.tableSeznam;
            }
        }
        /// <summary>Autogenerated.</summary>
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public GGinvfofDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected GGinvfofDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Seznam"] != null)) {
                    base.Tables.Add(new SeznamDataTable(ds.Tables["Seznam"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            GGinvfofDataSet cln = ((GGinvfofDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Seznam"] != null)) {
                    base.Tables.Add(new SeznamDataTable(ds.Tables["Seznam"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected virtual void InitVars(bool initTable) {
            this.tableSeznam = ((SeznamDataTable)(base.Tables["Seznam"]));
            if ((initTable == true)) {
                if ((this.tableSeznam != null)) {
                    this.tableSeznam.InitVars();
                }
            }
            this.UpdateFromNamespace();
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "GGinvfofDataSet";
            this.Prefix = "";
            this.Namespace = "http://www.gordic.cz/TR/data/Report.GReportGinvfof/1.0";
            this.Locale = new global::System.Globalization.CultureInfo("en-US");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSeznam = new SeznamDataTable();
            base.Tables.Add(this.tableSeznam);
            m_ixsxme = "Report.GReportGinvfof";
            m_xmeta_ver = 1;
            m_xmeta_subver = 0;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeSeznam() {
            return false;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            GGinvfofDataSet ds = new GGinvfofDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        /// <summary>Autogenerated.</summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public delegate void SeznamRowChangeEventHandler(object sender, SeznamRowChangeEvent e);
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        /// <summary>Autogenerated.</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public partial class SeznamDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable, GeneratedBy.GDataSetGenerator478, System.Collections.Generic.IEnumerable<SeznamRow> {
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnixs_fun;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnixs_tof;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnixs_str;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnixs_alv;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnixs_frm;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnpopis;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnpriz_fos;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnk_v;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnaktivita;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columndat_zmena;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnzmenu_prov;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ixs_funColumn {
                get {
                    return this.columnixs_fun;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ixs_tofColumn {
                get {
                    return this.columnixs_tof;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ixs_strColumn {
                get {
                    return this.columnixs_str;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ixs_alvColumn {
                get {
                    return this.columnixs_alv;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ixs_frmColumn {
                get {
                    return this.columnixs_frm;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn popisColumn {
                get {
                    return this.columnpopis;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn priz_fosColumn {
                get {
                    return this.columnpriz_fos;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn k_vColumn {
                get {
                    return this.columnk_v;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn aktivitaColumn {
                get {
                    return this.columnaktivita;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn dat_zmenaColumn {
                get {
                    return this.columndat_zmena;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn zmenu_provColumn {
                get {
                    return this.columnzmenu_prov;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamRow this[int index] {
                get {
                    return ((SeznamRow)(this.Rows[index]));
                }
            }
            /// <summary>Autogenerated.</summary>
            public event SeznamRowChangeEventHandler SeznamRowChanging;
            /// <summary>Autogenerated.</summary>
            public event SeznamRowChangeEventHandler SeznamRowChanged;
            /// <summary>Autogenerated.</summary>
            public event SeznamRowChangeEventHandler SeznamRowDeleting;
            /// <summary>Autogenerated.</summary>
            public event SeznamRowChangeEventHandler SeznamRowDeleted;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamDataTable() {
                this.TableName = "Seznam";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SeznamDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected SeznamDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddSeznamRow(SeznamRow row) {
                this.Rows.Add(row);
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            global::System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                SeznamDataTable cln = ((SeznamDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SeznamDataTable();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnixs_fun = base.Columns["ixs_fun"];
                this.columnixs_tof = base.Columns["ixs_tof"];
                this.columnixs_str = base.Columns["ixs_str"];
                this.columnixs_alv = base.Columns["ixs_alv"];
                this.columnixs_frm = base.Columns["ixs_frm"];
                this.columnpopis = base.Columns["popis"];
                this.columnpriz_fos = base.Columns["priz_fos"];
                this.columnk_v = base.Columns["k_v"];
                this.columnaktivita = base.Columns["aktivita"];
                this.columndat_zmena = base.Columns["dat_zmena"];
                this.columnzmenu_prov = base.Columns["zmenu_prov"];
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnixs_fun = new global::System.Data.DataColumn("ixs_fun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnixs_fun);
                this.columnixs_tof = new global::System.Data.DataColumn("ixs_tof", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnixs_tof);
                this.columnixs_str = new global::System.Data.DataColumn("ixs_str", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnixs_str);
                this.columnixs_alv = new global::System.Data.DataColumn("ixs_alv", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnixs_alv);
                this.columnixs_frm = new global::System.Data.DataColumn("ixs_frm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnixs_frm);
                this.columnpopis = new global::System.Data.DataColumn("popis", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpopis);
                this.columnpriz_fos = new global::System.Data.DataColumn("priz_fos", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpriz_fos);
                this.columnk_v = new global::System.Data.DataColumn("k_v", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnk_v);
                this.columnaktivita = new global::System.Data.DataColumn("aktivita", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnaktivita);
                this.columndat_zmena = new global::System.Data.DataColumn("dat_zmena", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndat_zmena);
                this.columnzmenu_prov = new global::System.Data.DataColumn("zmenu_prov", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnzmenu_prov);
                this.columnixs_fun.MaxLength = 12;
                this.columnixs_tof.MaxLength = 12;
                this.columnixs_str.MaxLength = 12;
                this.columnixs_alv.MaxLength = 12;
                this.columnixs_frm.MaxLength = 12;
                this.columnzmenu_prov.MaxLength = 12;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamRow NewSeznamRow() {
                return ((SeznamRow)(this.NewRow()));
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SeznamRow(builder);
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SeznamRowChanged != null)) {
                    this.SeznamRowChanged(this, new SeznamRowChangeEvent(((SeznamRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SeznamRowChanging != null)) {
                    this.SeznamRowChanging(this, new SeznamRowChangeEvent(((SeznamRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SeznamRowDeleted != null)) {
                    this.SeznamRowDeleted(this, new SeznamRowChangeEvent(((SeznamRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SeznamRowDeleting != null)) {
                    this.SeznamRowDeleting(this, new SeznamRowChangeEvent(((SeznamRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveSeznamRow(SeznamRow row) {
                this.Rows.Remove(row);
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                GGinvfofDataSet ds = new GGinvfofDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SeznamDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
            /// <summary>Autogenerated.</summary>
            public new Gordic.General.GDataRowCollection<SeznamRow> Rows {
                get {
                    return new Gordic.General.GDataRowCollection<SeznamRow>(base.Rows);
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamRow AddSeznamRow(Gordic.General.GString ixs_fun, Gordic.General.GString ixs_tof, Gordic.General.GString ixs_str, Gordic.General.GString ixs_alv, Gordic.General.GString ixs_frm, Gordic.General.GString popis, Gordic.General.GInt16 priz_fos, Gordic.General.GInt16 k_v, Gordic.General.GInt16 aktivita, Gordic.General.GDateTime dat_zmena, Gordic.General.GString zmenu_prov) {
                SeznamRow rowSeznamRow = ((SeznamRow)(NewRow()));
                object[] l_oItems = new object[11];
                if ((ixs_fun != null)) {
                    l_oItems[0] = ixs_fun.DbValue;
                }
                if ((ixs_tof != null)) {
                    l_oItems[1] = ixs_tof.DbValue;
                }
                if ((ixs_str != null)) {
                    l_oItems[2] = ixs_str.DbValue;
                }
                if ((ixs_alv != null)) {
                    l_oItems[3] = ixs_alv.DbValue;
                }
                if ((ixs_frm != null)) {
                    l_oItems[4] = ixs_frm.DbValue;
                }
                if ((popis != null)) {
                    l_oItems[5] = popis.DbValue;
                }
                if ((priz_fos != null)) {
                    l_oItems[6] = priz_fos.DbValue;
                }
                if ((k_v != null)) {
                    l_oItems[7] = k_v.DbValue;
                }
                if ((aktivita != null)) {
                    l_oItems[8] = aktivita.DbValue;
                }
                if ((dat_zmena != null)) {
                    l_oItems[9] = dat_zmena.DbValue;
                }
                if ((zmenu_prov != null)) {
                    l_oItems[10] = zmenu_prov.DbValue;
                }
                rowSeznamRow.ItemArray = l_oItems;
                Rows.Add(rowSeznamRow);
                return rowSeznamRow;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamRow AddSeznamRow() {
                SeznamRow rowSeznamRow = ((SeznamRow)(NewRow()));
                Rows.Add(rowSeznamRow);
                return rowSeznamRow;
            }
            /// <summary>Autogenerated.</summary>
            public virtual System.Collections.Generic.IEnumerator<SeznamRow> GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
        }
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        /// <summary>Autogenerated.</summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public partial class SeznamRow : global::Gordic.General.GDataRow, GeneratedBy.GDataSetGenerator478 {
            /// <summary>Autogenerated.</summary>
            private SeznamDataTable tableSeznam;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SeznamRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSeznam = ((SeznamDataTable)(this.Table));
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [GLength(12)]
            public Gordic.General.GString ixs_fun {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.ixs_funColumn], ((ushort)(this.tableSeznam.ixs_funColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.ixs_funColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.ixs_funColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.ixs_funColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [GLength(12)]
            public Gordic.General.GString ixs_tof {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.ixs_tofColumn], ((ushort)(this.tableSeznam.ixs_tofColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.ixs_tofColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.ixs_tofColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.ixs_tofColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [GLength(12)]
            public Gordic.General.GString ixs_str {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.ixs_strColumn], ((ushort)(this.tableSeznam.ixs_strColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.ixs_strColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.ixs_strColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.ixs_strColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [GLength(12)]
            public Gordic.General.GString ixs_alv {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.ixs_alvColumn], ((ushort)(this.tableSeznam.ixs_alvColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.ixs_alvColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.ixs_alvColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.ixs_alvColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [GLength(12)]
            public Gordic.General.GString ixs_frm {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.ixs_frmColumn], ((ushort)(this.tableSeznam.ixs_frmColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.ixs_frmColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.ixs_frmColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.ixs_frmColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GString popis {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.popisColumn], ((ushort)(this.tableSeznam.popisColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.popisColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.popisColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.popisColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GInt16 priz_fos {
                get {
                    return Gordic.General.GInt16.Parse(this[this.tableSeznam.priz_fosColumn]);
                }
                set {
                    object cval = this[this.tableSeznam.priz_fosColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.priz_fosColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        short val = value.BaseValue;
                        if (((cval.GetType() != typeof(short)) 
                                    || (val != ((short)(cval))))) {
                            this[this.tableSeznam.priz_fosColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GInt16 k_v {
                get {
                    return Gordic.General.GInt16.Parse(this[this.tableSeznam.k_vColumn]);
                }
                set {
                    object cval = this[this.tableSeznam.k_vColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.k_vColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        short val = value.BaseValue;
                        if (((cval.GetType() != typeof(short)) 
                                    || (val != ((short)(cval))))) {
                            this[this.tableSeznam.k_vColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GInt16 aktivita {
                get {
                    return Gordic.General.GInt16.Parse(this[this.tableSeznam.aktivitaColumn]);
                }
                set {
                    object cval = this[this.tableSeznam.aktivitaColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.aktivitaColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        short val = value.BaseValue;
                        if (((cval.GetType() != typeof(short)) 
                                    || (val != ((short)(cval))))) {
                            this[this.tableSeznam.aktivitaColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GDateTime dat_zmena {
                get {
                    return Gordic.General.GDateTime.Parse(this[this.tableSeznam.dat_zmenaColumn]);
                }
                set {
                    object cval = this[this.tableSeznam.dat_zmenaColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.dat_zmenaColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        System.DateTime val = value.BaseValue;
                        if (((cval.GetType() != typeof(System.DateTime)) 
                                    || (val != ((System.DateTime)(cval))))) {
                            this[this.tableSeznam.dat_zmenaColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [GLength(12)]
            public Gordic.General.GString zmenu_prov {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznam.zmenu_provColumn], ((ushort)(this.tableSeznam.zmenu_provColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznam.zmenu_provColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznam.zmenu_provColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznam.zmenu_provColumn] = val;
                        }
                    }
                }
            }
        }
        /// <summary>
        ///Row event argument class
        ///</summary>
        /// <summary>Autogenerated.</summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public class SeznamRowChangeEvent : global::System.EventArgs, GeneratedBy.GDataSetGenerator478 {
            /// <summary>Autogenerated.</summary>
            private SeznamRow eventRow;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataRowAction eventAction;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamRowChangeEvent(SeznamRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamRow Row {
                get {
                    return this.eventRow;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        /// <summary>Autogenerated.</summary>
        public enum ColSeznam {
            /// <summary>Autogenerated.</summary>
            ixs_fun,
            /// <summary>Autogenerated.</summary>
            ixs_tof,
            /// <summary>Autogenerated.</summary>
            ixs_str,
            /// <summary>Autogenerated.</summary>
            ixs_alv,
            /// <summary>Autogenerated.</summary>
            ixs_frm,
            /// <summary>Autogenerated.</summary>
            popis,
            /// <summary>Autogenerated.</summary>
            priz_fos,
            /// <summary>Autogenerated.</summary>
            k_v,
            /// <summary>Autogenerated.</summary>
            aktivita,
            /// <summary>Autogenerated.</summary>
            dat_zmena,
            /// <summary>Autogenerated.</summary>
            zmenu_prov,
        }
    }
}
