<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="GScheduledReport" targetNamespace="http://www.gordic.cz/TR/data/Report.GScheduledReport/1.0" xmlns:mstns="http://www.gordic.cz/TR/data/Report.GScheduledReport/1.0" xmlns="http://www.gordic.cz/TR/data/Report.GScheduledReport/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="GScheduledReportDataSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ScheduledReport">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ixs_poz" type="xs:string" nillable="true" />
              <xs:element name="name" type="xs:string" nillable="true" />
              <xs:element name="poznamka" type="xs:string" nillable="true" />
              <xs:element name="mail_addresses" type="xs:string" nillable="true" />
              <xs:element name="mail_subject" type="xs:string" nillable="true" />
              <xs:element name="mail_body" type="xs:string" nillable="true" />
              <xs:element name="mail_attach" type="xs:boolean" nillable="true" />
              <xs:element name="file_save" type="xs:string" nillable="true" />
              <xs:element name="dms_type" type="xs:short" nillable="true" />
              <xs:element name="dms_ixp" type="xs:string" nillable="true" />
              <xs:element name="dms_podp" type="xs:short" nillable="true" />
              <xs:element name="dms_typ_dok" type="xs:string" nillable="true" />
              <xs:element name="dms_fun" type="xs:string" nillable="true" />
              <xs:element name="dms_body" type="xs:string" nillable="true" />
              <xs:element name="dms_poznamka" type="xs:string" nillable="true" />
              <xs:element name="dms_spipl" type="xs:string" nillable="true" />
              <xs:element name="dms_spizn" type="xs:string" nillable="true" />
              <xs:element name="uda_uda" type="xs:string" nillable="true" />
              <xs:element name="ses_info" type="xs:string" nillable="true" />
              <xs:element name="mail_zip" type="xs:short" nillable="true" />
              <xs:element name="err_mail" type="xs:short" nillable="true" />
              <xs:element name="pkg_body" type="xs:string" nillable="true" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>