<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xs:schema targetNamespace="http://www.gordic.cz/TR/data/ListOfPreselectedDataset/1.0" xmlns:mstns="http://www.gordic.cz/TR/data/ListOfPreselectedDataset/1.0" xmlns="http://www.gordic.cz/TR/data/ListOfPreselectedDataset/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:app1="http://www.gordic.cz/TR/data/ListOfPreselectedDataset/1.0">
  <xs:element name="ListOfPreselectedDataset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ListOfPreselected">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tema" nillable="true">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <!--<xs:maxLength value="12" />-->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="nazev" nillable="true">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <!--<xs:maxLength value="12" />-->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="pred_reg" nillable="true">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <!--<xs:maxLength value="12" />-->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="pred_form" nillable="true">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <!--<xs:maxLength value="12" />-->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="pred_out" type="xs:string" nillable="true"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>