<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xs:schema id="SeznamFaziSestavDataSet" targetNamespace="http://www.gordic.cz/TR/data/Report.SeznamFaziSestav/1.0" xmlns:mstns="http://www.gordic.cz/TR/data/Report.SeznamFaziSestav/1.0" xmlns="http://www.gordic.cz/TR/data/Wfl.SeznamNavazanychEDokumentu/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:app1="http://www.gordic.cz/TR/data/Report.SeznamFaziSestav/1.0">
  <xs:element name="SeznamFaziSestavDataSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SeznamFaziSestav">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="faze" type="xs:string" nillable="false" />
              <xs:element name="faze_txt" type="xs:string" nillable="true" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>