// This source code was auto-generated by GDataSetGenerator478, Version=490.1.0.0
namespace Gordic.Report.Interface {
    using Gordic.General;
    using Gordic.General.ApplicationInterface;
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    /// <summary>Autogenerated.</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("SeznamFaziSestavDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
    public partial class SeznamFaziSestavDataSet : global::Gordic.General.GDataSet, GeneratedBy.GDataSetGenerator478 {
        /// <summary>Autogenerated.</summary>
        private SeznamFaziSestavDataTable tableSeznamFaziSestav;
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SeznamFaziSestavDataTable SeznamFaziSestav {
            get {
                return this.tableSeznamFaziSestav;
            }
        }
        /// <summary>Autogenerated.</summary>
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SeznamFaziSestavDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected SeznamFaziSestavDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["SeznamFaziSestav"] != null)) {
                    base.Tables.Add(new SeznamFaziSestavDataTable(ds.Tables["SeznamFaziSestav"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            SeznamFaziSestavDataSet cln = ((SeznamFaziSestavDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SeznamFaziSestav"] != null)) {
                    base.Tables.Add(new SeznamFaziSestavDataTable(ds.Tables["SeznamFaziSestav"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected virtual void InitVars(bool initTable) {
            this.tableSeznamFaziSestav = ((SeznamFaziSestavDataTable)(base.Tables["SeznamFaziSestav"]));
            if ((initTable == true)) {
                if ((this.tableSeznamFaziSestav != null)) {
                    this.tableSeznamFaziSestav.InitVars();
                }
            }
            this.UpdateFromNamespace();
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "SeznamFaziSestavDataSet";
            this.Prefix = "";
            this.Namespace = "http://www.gordic.cz/TR/data/Report.SeznamFaziSestav/1.0";
            this.Locale = new global::System.Globalization.CultureInfo("en-US");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSeznamFaziSestav = new SeznamFaziSestavDataTable();
            base.Tables.Add(this.tableSeznamFaziSestav);
            m_ixsxme = "Report.SeznamFaziSestav";
            m_xmeta_ver = 1;
            m_xmeta_subver = 0;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeSeznamFaziSestav() {
            return false;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            SeznamFaziSestavDataSet ds = new SeznamFaziSestavDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        /// <summary>Autogenerated.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        /// <summary>Autogenerated.</summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public delegate void SeznamFaziSestavRowChangeEventHandler(object sender, SeznamFaziSestavRowChangeEvent e);
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        /// <summary>Autogenerated.</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public partial class SeznamFaziSestavDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable, GeneratedBy.GDataSetGenerator478, System.Collections.Generic.IEnumerable<SeznamFaziSestavRow> {
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnfaze;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataColumn columnfaze_txt;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn fazeColumn {
                get {
                    return this.columnfaze;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn faze_txtColumn {
                get {
                    return this.columnfaze_txt;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavRow this[int index] {
                get {
                    return ((SeznamFaziSestavRow)(this.Rows[index]));
                }
            }
            /// <summary>Autogenerated.</summary>
            public event SeznamFaziSestavRowChangeEventHandler SeznamFaziSestavRowChanging;
            /// <summary>Autogenerated.</summary>
            public event SeznamFaziSestavRowChangeEventHandler SeznamFaziSestavRowChanged;
            /// <summary>Autogenerated.</summary>
            public event SeznamFaziSestavRowChangeEventHandler SeznamFaziSestavRowDeleting;
            /// <summary>Autogenerated.</summary>
            public event SeznamFaziSestavRowChangeEventHandler SeznamFaziSestavRowDeleted;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavDataTable() {
                this.TableName = "SeznamFaziSestav";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SeznamFaziSestavDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected SeznamFaziSestavDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddSeznamFaziSestavRow(SeznamFaziSestavRow row) {
                this.Rows.Add(row);
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            global::System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                SeznamFaziSestavDataTable cln = ((SeznamFaziSestavDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SeznamFaziSestavDataTable();
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnfaze = base.Columns["faze"];
                this.columnfaze_txt = base.Columns["faze_txt"];
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnfaze = new global::System.Data.DataColumn("faze", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfaze);
                this.columnfaze_txt = new global::System.Data.DataColumn("faze_txt", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfaze_txt);
                this.columnfaze.AllowDBNull = false;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavRow NewSeznamFaziSestavRow() {
                return ((SeznamFaziSestavRow)(this.NewRow()));
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SeznamFaziSestavRow(builder);
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SeznamFaziSestavRowChanged != null)) {
                    this.SeznamFaziSestavRowChanged(this, new SeznamFaziSestavRowChangeEvent(((SeznamFaziSestavRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SeznamFaziSestavRowChanging != null)) {
                    this.SeznamFaziSestavRowChanging(this, new SeznamFaziSestavRowChangeEvent(((SeznamFaziSestavRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SeznamFaziSestavRowDeleted != null)) {
                    this.SeznamFaziSestavRowDeleted(this, new SeznamFaziSestavRowChangeEvent(((SeznamFaziSestavRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SeznamFaziSestavRowDeleting != null)) {
                    this.SeznamFaziSestavRowDeleting(this, new SeznamFaziSestavRowChangeEvent(((SeznamFaziSestavRow)(e.Row)), e.Action));
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveSeznamFaziSestavRow(SeznamFaziSestavRow row) {
                this.Rows.Remove(row);
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SeznamFaziSestavDataSet ds = new SeznamFaziSestavDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SeznamFaziSestavDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
            /// <summary>Autogenerated.</summary>
            public new Gordic.General.GDataRowCollection<SeznamFaziSestavRow> Rows {
                get {
                    return new Gordic.General.GDataRowCollection<SeznamFaziSestavRow>(base.Rows);
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavRow AddSeznamFaziSestavRow(Gordic.General.GString faze, Gordic.General.GString faze_txt) {
                SeznamFaziSestavRow rowSeznamFaziSestavRow = ((SeznamFaziSestavRow)(NewRow()));
                object[] l_oItems = new object[2];
                if ((faze != null)) {
                    l_oItems[0] = faze.DbValue;
                }
                if ((faze_txt != null)) {
                    l_oItems[1] = faze_txt.DbValue;
                }
                rowSeznamFaziSestavRow.ItemArray = l_oItems;
                Rows.Add(rowSeznamFaziSestavRow);
                return rowSeznamFaziSestavRow;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavRow AddSeznamFaziSestavRow() {
                SeznamFaziSestavRow rowSeznamFaziSestavRow = ((SeznamFaziSestavRow)(NewRow()));
                Rows.Add(rowSeznamFaziSestavRow);
                return rowSeznamFaziSestavRow;
            }
            /// <summary>Autogenerated.</summary>
            public virtual System.Collections.Generic.IEnumerator<SeznamFaziSestavRow> GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
        }
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        /// <summary>Autogenerated.</summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public partial class SeznamFaziSestavRow : global::Gordic.General.GDataRow, GeneratedBy.GDataSetGenerator478 {
            /// <summary>Autogenerated.</summary>
            private SeznamFaziSestavDataTable tableSeznamFaziSestav;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SeznamFaziSestavRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSeznamFaziSestav = ((SeznamFaziSestavDataTable)(this.Table));
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GString faze {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznamFaziSestav.fazeColumn], ((ushort)(this.tableSeznamFaziSestav.fazeColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznamFaziSestav.fazeColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznamFaziSestav.fazeColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznamFaziSestav.fazeColumn] = val;
                        }
                    }
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Gordic.General.GString faze_txt {
                get {
                    return Gordic.General.GString.Parse(this[this.tableSeznamFaziSestav.faze_txtColumn], ((ushort)(this.tableSeznamFaziSestav.faze_txtColumn.MaxLength)), true);
                }
                set {
                    object cval = this[this.tableSeznamFaziSestav.faze_txtColumn];
                    if (((value == null) 
                                || value.IsNull)) {
                        if ((cval != System.DBNull.Value)) {
                            this[this.tableSeznamFaziSestav.faze_txtColumn] = System.DBNull.Value;
                        }
                    }
                    else {
                        string val = value.BaseValue;
                        if (((cval.GetType() != typeof(string)) 
                                    || (val != ((string)(cval))))) {
                            this[this.tableSeznamFaziSestav.faze_txtColumn] = val;
                        }
                    }
                }
            }
        }
        /// <summary>
        ///Row event argument class
        ///</summary>
        /// <summary>Autogenerated.</summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("GDataSetGenerator478", "490.1.0.0")]
        public class SeznamFaziSestavRowChangeEvent : global::System.EventArgs, GeneratedBy.GDataSetGenerator478 {
            /// <summary>Autogenerated.</summary>
            private SeznamFaziSestavRow eventRow;
            /// <summary>Autogenerated.</summary>
            private global::System.Data.DataRowAction eventAction;
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavRowChangeEvent(SeznamFaziSestavRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SeznamFaziSestavRow Row {
                get {
                    return this.eventRow;
                }
            }
            /// <summary>Autogenerated.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        /// <summary>Autogenerated.</summary>
        public enum ColSeznamFaziSestav {
            /// <summary>Autogenerated.</summary>
            faze,
            /// <summary>Autogenerated.</summary>
            faze_txt,
        }
    }
}
