declare namespace Gordic.Data.Readers {
    /**
    * Klientská část AL - číselník Rekcpdv
    * keys : ["typ_pdv"]
    * columns: ["typ_pdv","typ_pdv_txt","k_v"]
    * filters: ["typ_pdv","typ_pdv_txt","k_v"]
    */
    class Rekcpdv extends Base<Gordic.Data.Readers.RekcpdvDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RekcpdvDto {
		/**Autogenerated.*/
		typ_pdv?: number|null;
		/**Autogenerated.*/
		typ_pdv_txt?: string|null;
		/**Autogenerated.*/
		k_v?: number|null;
	}
	const enum RekcpdvDtoNames { typ_pdv = "typ_pdv", typ_pdv_txt = "typ_pdv_txt", k_v = "k_v",}
	const enum RekcpdvDtoFragments { typ_pdv = "*", typ_pdv_txt = "*", k_v = "*",}
	const enum RekcpdvDtoTypes { typ_pdv = "number", typ_pdv_txt = "string", k_v = "number",}
	const enum RekcpdvDtoTypeLengths {}

    /**
    * Klientská část AL - Rekskli
    * keys : ["ixs_kli"]
    * columns: ["ixs_kli","ico","nazev","id_klient","obec","esu_txt"]
    * filters: ["ixs_kli","nazev"]
    */
    class Rekskli extends Base<Gordic.Data.Readers.RekskliDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RekskliDto {
		/**Autogenerated.*/
		ixs_kli?: string|null;
		/**Autogenerated.*/
		ico?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		id_klient?: number|null;
		/**Autogenerated.*/
		obec?: string|null;
		/**Autogenerated.*/
		esu_txt?: string|null;
	}
	const enum RekskliDtoNames { ixs_kli = "ixs_kli", ico = "ico", nazev = "nazev", id_klient = "id_klient", obec = "obec", esu_txt = "esu_txt",}
	const enum RekskliDtoFragments { ixs_kli = "*", ico = "*", nazev = "*", id_klient = "*", obec = "*", esu_txt = "*",}
	const enum RekskliDtoTypes { ixs_kli = "string", ico = "string", nazev = "string", id_klient = "number", obec = "string", esu_txt = "string",}
	const enum RekskliDtoTypeLengths {}
}
declare namespace Gordic.Prefabs.Select {
    /**
    * Klientská část AL - číselník Rekcpdv
    * FieldOptions
    * itemTemplate: "{typ_pdv_txt}"
    * helperColumns: ["typ_pdv_txt"]
    *
    * DataReader 
    * keys: ["typ_pdv"]
    * columns: ["typ_pdv","typ_pdv_txt","k_v"]
    * filters: ["typ_pdv","typ_pdv_txt","k_v"]
    */
    function rekcpdv(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RekcpdvDto>): GSelectBoxOptions<Gordic.Data.Readers.RekcpdvDto>;
    /**
    * Klientská část AL - Rekskli
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev"]
    *
    * DataReader 
    * keys: ["ixs_kli"]
    * columns: ["ixs_kli","ico","nazev","id_klient","obec","esu_txt"]
    * filters: ["ixs_kli","nazev"]
    */
    function rekskli(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RekskliDto>): GSelectBoxOptions<Gordic.Data.Readers.RekskliDto>;}
