declare namespace Gordic.Data.Readers {
    /**
    * Klientská část AL - Úroveň verifikace uživatele typu veřejnost
    * keys : ["verif_exu"]
    * columns: ["verif_exu","nazev"]
    * filters: ["verif_exu","nazev"]
    */
    class Ginsvex extends Base<Gordic.Data.Readers.GinsvexDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface GinsvexDto {
		/**Autogenerated.*/
		verif_exu?: number|null;
		/**Autogenerated.*/
		nazev?: string|null;
	}
	const enum GinsvexDtoNames { verif_exu = "verif_exu", nazev = "nazev",}
	const enum GinsvexDtoFragments { verif_exu = "*", nazev = "*",}
	const enum GinsvexDtoTypes { verif_exu = "number", nazev = "string",}
	const enum GinsvexDtoTypeLengths {}

    /**
    * Klientská část AL
    * keys : ["ixs_tpp"]
    * columns: ["ixs_tpp","nazev","typ_prist_nah","typ_prist_nah_txt","poc_hod_exp","poc_dni_exp","poc_hod_exp_max","poc_dni_exp_max","aktivita"]
    * filters: ["ixs_tpp","nazev","aktivita"]
    */
    class DefiniceOmezenehoPristupu extends Base<Gordic.Rap.Interface.GDefiniceOmezenehoPristupuDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Příznak vložení plné moci
    * keys : ["priz_plm"]
    * columns: ["priz_plm","priz_plm_txt"]
    * filters: ["priz_plm"]
    */
    class Rapcplm extends Base<Gordic.Rap.Interface.GRapcplmDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Stav požadavků pro nahlížení na spis
    * keys : ["stav_spn"]
    * columns: ["stav_spn","stav_spn_txt"]
    * filters: ["stav_spn"]
    */
    class Rapcspn extends Base<Gordic.Rap.Interface.GRapcspnDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Typ přístupu k nahlížení
    * keys : ["typ_prist_nah"]
    * columns: ["typ_prist_nah","typ_prist_nah_txt"]
    * filters: ["typ_prist_nah"]
    */
    class Rapctpp extends Base<Gordic.Rap.Interface.GRapctppDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Způsob ověření přístupu osob
    * keys : ["zp_overeni"]
    * columns: ["zp_overeni","zp_overeni_txt"]
    * filters: ["zp_overeni"]
    */
    class Rapczpo extends Base<Gordic.Rap.Interface.GRapczpoDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Klientská část AL
    * keys : ["kod_sps"]
    * columns: ["kod_sps","kod_sps_txt"]
    * filters: ["kod_sps","kod_sps_txt"]
    */
    class StrukturaPopisuZivotniSituace extends Base<Gordic.Rap.Interface.GStrukturaPopisuZivotniSituaceDto>
    {
        constructor(options?: IGReaderBase);
    }
}
declare namespace Gordic.Prefabs.Select {
    /**
    * Klientská část AL - Úroveň verifikace uživatele typu veřejnost
    * FieldOptions
    * itemTemplate: "{?}"
    * helperColumns: ["?"]
    *
    * DataReader 
    * keys: ["verif_exu"]
    * columns: ["verif_exu","nazev"]
    * filters: ["verif_exu","nazev"]
    */
    function ginsvex(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.GinsvexDto>): GSelectBoxOptions<Gordic.Data.Readers.GinsvexDto>;
    /**
    * Klientská část AL
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ixs_tpp","nazev"]
    *
    * DataReader 
    * keys: ["ixs_tpp"]
    * columns: ["ixs_tpp","nazev","typ_prist_nah","typ_prist_nah_txt","poc_hod_exp","poc_dni_exp","poc_hod_exp_max","poc_dni_exp_max","aktivita"]
    * filters: ["ixs_tpp","nazev","aktivita"]
    */
    function definiceOmezenehoPristupu(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Rap.Interface.GDefiniceOmezenehoPristupuDto>): GSelectBoxOptions<Gordic.Rap.Interface.GDefiniceOmezenehoPristupuDto>;
    /**
    * Příznak vložení plné moci
    * FieldOptions
    * itemTemplate: "{priz_plm_txt}"
    * helperColumns: ["priz_plm", "priz_plm_txt"]
    *
    * DataReader 
    * keys: ["priz_plm"]
    * columns: ["priz_plm","priz_plm_txt"]
    * filters: ["priz_plm"]
    */
    function rapcplm(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Rap.Interface.GRapcplmDto>): GSelectBoxOptions<Gordic.Rap.Interface.GRapcplmDto>;
    /**
    * Stav požadavků pro nahlížení na spis
    * FieldOptions
    * itemTemplate: "{stav_spn_txt}"
    * helperColumns: ["stav_sps", "stav_spn_txt"]
    *
    * DataReader 
    * keys: ["stav_spn"]
    * columns: ["stav_spn","stav_spn_txt"]
    * filters: ["stav_spn"]
    */
    function rapcspn(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Rap.Interface.GRapcspnDto>): GSelectBoxOptions<Gordic.Rap.Interface.GRapcspnDto>;
    /**
    * Typ přístupu k nahlížení
    * FieldOptions
    * itemTemplate: "{typ_prist_nah_txt}"
    * helperColumns: ["typ_prist_nah","typ_prist_nah_txt"]
    *
    * DataReader 
    * keys: ["typ_prist_nah"]
    * columns: ["typ_prist_nah","typ_prist_nah_txt"]
    * filters: ["typ_prist_nah"]
    */
    function rapctpp(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Rap.Interface.GRapctppDto>): GSelectBoxOptions<Gordic.Rap.Interface.GRapctppDto>;
    /**
    * Způsob ověření přístupu osob
    * FieldOptions
    * itemTemplate: "{zp_overeni_txt}"
    * helperColumns: ["zp_overeni","zp_overeni_txt"]
    *
    * DataReader 
    * keys: ["zp_overeni"]
    * columns: ["zp_overeni","zp_overeni_txt"]
    * filters: ["zp_overeni"]
    */
    function rapczpo(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Rap.Interface.GRapczpoDto>): GSelectBoxOptions<Gordic.Rap.Interface.GRapczpoDto>;
    /**
    * Klientská část AL
    * FieldOptions
    * itemTemplate: "{kod_sps_txt}"
    * helperColumns: ["kod_sps", "kod_sps_txt"]
    *
    * DataReader 
    * keys: ["kod_sps"]
    * columns: ["kod_sps","kod_sps_txt"]
    * filters: ["kod_sps","kod_sps_txt"]
    */
    function strukturaPopisuZivotniSituace(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Rap.Interface.GStrukturaPopisuZivotniSituaceDto>): GSelectBoxOptions<Gordic.Rap.Interface.GStrukturaPopisuZivotniSituaceDto>;}
