// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.4.5
// Machine:  PCL0100AOX2
// DateTime: 21.10.2025 18:08:49
// UserName: maliger
// Input file <Gordic.General.ODataParser.y - 21.10.2025 18:08:41>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace Gordic.General.ODataParser
{
internal enum Tokens {error=94,EOF=95,ODataSignal_METADATA=96,
    ODataSignal_BATCH=97,ODataSignal_SKIPTOKEN=98,ODataSignal_COUNT=99,Infinity_LUC=100,NotANumber_LXC=101,All_LUC=102,
    Json_LLC=103,Floor_LLC=104,Xml_LLC=105,Year_LLC=106,Round_LLC=107,GeoLength_LLC=108,
    GeoDotIntersects_LLC=109,GeoDotDistance_LLC=110,GetTotalOffsetMinutes_LLC=111,Length_LLC=112,Now_LLC=113,None_LLC=114,
    IndexOf_LLC=115,Sum_LLC=116,Substring_LLC=117,Contains_LLC=118,StartsWith_LLC=119,Second_LLC=120,
    Hour_LLC=121,Concat_LLC=122,Ceiling_LLC=123,Day_LLC=124,Days_LLC=125,Date_LLC=126,
    Desc_LLC=127,As_LLC=128,Average_LLC=129,All_LLC=130,AllPages_LLC=131,Any_LLC=132,
    Asc_LLC=133,Atom_LLC=134,Trim_LLC=135,ToLower_LLC=136,ToUpper_LLC=137,Time_LLC=138,
    EndsWith_LLC=139,Month_LLC=140,Min_LLC=141,Minute_LLC=142,MinDateTime_LLC=143,Max_LLC=144,
    MaxDateTime_LLC=145,And_LLC=146,Or_LLC=147,Eq_LLC=148,Ne_LLC=149,Lt_LLC=150,
    Le_LLC=151,Gt_LLC=152,Ge_LLC=153,In_LLC=154,Has_LLC=155,Add_LLC=156,
    Sub_LLC=157,Mul_LLC=158,Div_LLC=159,Mod_LLC=160,Not_LLC=161,IsOf_LLC=162,
    Cast_LLC=163,Null_LLC=164,True_LLC=165,False_LLC=166,TextConstant=167,NumberConstant=168,
    DateConstant=169,ID=170};

// Abstract base class for GPLEX scanners
internal abstract class ScanBase : AbstractScanner<GODataFilter.Tree,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

internal class GODataFilterParser: ShiftReduceParser<GODataFilter.Tree, LexLocation>
{
  // Verbatim content from Gordic.General.ODataParser.y - 21.10.2025 18:08:41
    public GODataFilter.Tree Result;
  // End verbatim content from Gordic.General.ODataParser.y - 21.10.2025 18:08:41

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[41];
  private static State[] states = new State[80];
  private static string[] nonTerms = new string[] {
      "stat", "$accept", "expr", "primitiveLiteral", "null_symbol", "boolean_symbol", 
      "value", "nexpr", "sexpr", "boolMethodCallExpr", "ve", "in_value_list", 
      "endsWithMethodCallExpr", "startsWithMethodCallExpr", "containsMethodCallExpr", 
      };

  static GODataFilterParser() {
    states[0] = new State(new int[]{40,75,161,6,139,15,119,60,118,67,170,24,164,27,168,28,169,29,167,30,165,32,166,33,95,79},new int[]{-1,1,-3,3,-8,78,-10,13,-13,14,-14,59,-15,66,-9,73,-7,74,-4,25,-5,26,-6,31});
    states[1] = new State(new int[]{95,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{147,4,146,11,95,-2});
    states[4] = new State(new int[]{161,6,139,15,119,60,118,67,170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-8,5,-10,13,-13,14,-14,59,-15,66,-9,73,-7,74,-4,25,-5,26,-6,31});
    states[5] = new State(-16);
    states[6] = new State(new int[]{40,8,170,24,164,27,168,28,169,29,167,30,165,32,166,33},new int[]{-9,7,-7,74,-4,25,-5,26,-6,31});
    states[7] = new State(-19);
    states[8] = new State(new int[]{40,75,161,6,139,15,119,60,118,67,170,24,164,27,168,28,169,29,167,30,165,32,166,33},new int[]{-3,9,-7,35,-8,78,-10,13,-13,14,-14,59,-15,66,-9,73,-4,25,-5,26,-6,31});
    states[9] = new State(new int[]{41,10,147,4,146,11});
    states[10] = new State(-20);
    states[11] = new State(new int[]{161,6,139,15,119,60,118,67,170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-8,12,-10,13,-13,14,-14,59,-15,66,-9,73,-7,74,-4,25,-5,26,-6,31});
    states[12] = new State(-17);
    states[13] = new State(-21);
    states[14] = new State(-35);
    states[15] = new State(new int[]{40,16});
    states[16] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-7,17,-4,25,-5,26,-6,31});
    states[17] = new State(new int[]{44,18});
    states[18] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,19,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[19] = new State(new int[]{41,20});
    states[20] = new State(-40);
    states[21] = new State(new int[]{148,22,152,37,150,40,151,42,153,44,149,46,154,48,41,-23,147,-23,146,-23,95,-23,44,-23});
    states[22] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,23,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[23] = new State(-26);
    states[24] = new State(-12);
    states[25] = new State(-13);
    states[26] = new State(-4);
    states[27] = new State(-9);
    states[28] = new State(-5);
    states[29] = new State(-6);
    states[30] = new State(-7);
    states[31] = new State(-8);
    states[32] = new State(-10);
    states[33] = new State(-11);
    states[34] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-7,35,-9,57,-4,25,-5,26,-6,31});
    states[35] = new State(new int[]{41,36,148,22,152,37,150,40,151,42,153,44,149,46,154,48});
    states[36] = new State(-14);
    states[37] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,38,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[38] = new State(-27);
    states[39] = new State(-24);
    states[40] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,41,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[41] = new State(-28);
    states[42] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,43,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[43] = new State(-29);
    states[44] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,45,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[45] = new State(-30);
    states[46] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,47,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[47] = new State(-31);
    states[48] = new State(new int[]{40,49});
    states[49] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-12,50,-11,56,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[50] = new State(new int[]{41,51,44,52});
    states[51] = new State(-32);
    states[52] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-7,53,-4,25,-5,26,-6,31});
    states[53] = new State(-34);
    states[54] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-7,55,-4,25,-5,26,-6,31});
    states[55] = new State(new int[]{41,36});
    states[56] = new State(-33);
    states[57] = new State(new int[]{41,58});
    states[58] = new State(-25);
    states[59] = new State(-36);
    states[60] = new State(new int[]{40,61});
    states[61] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-7,62,-4,25,-5,26,-6,31});
    states[62] = new State(new int[]{44,63});
    states[63] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,64,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[64] = new State(new int[]{41,65});
    states[65] = new State(-39);
    states[66] = new State(-37);
    states[67] = new State(new int[]{40,68});
    states[68] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,54},new int[]{-7,69,-4,25,-5,26,-6,31});
    states[69] = new State(new int[]{44,70});
    states[70] = new State(new int[]{170,24,164,27,168,28,169,29,167,30,165,32,166,33,40,34},new int[]{-11,71,-7,21,-4,25,-5,26,-6,31,-9,39});
    states[71] = new State(new int[]{41,72});
    states[72] = new State(-38);
    states[73] = new State(-22);
    states[74] = new State(new int[]{148,22,152,37,150,40,151,42,153,44,149,46,154,48});
    states[75] = new State(new int[]{40,75,161,6,139,15,119,60,118,67,170,24,164,27,168,28,169,29,167,30,165,32,166,33},new int[]{-3,76,-7,35,-8,78,-10,13,-13,14,-14,59,-15,66,-9,73,-4,25,-5,26,-6,31});
    states[76] = new State(new int[]{41,77,147,4,146,11});
    states[77] = new State(-15);
    states[78] = new State(-18);
    states[79] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,95});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-1, new int[]{95});
    rules[4] = new Rule(-4, new int[]{-5});
    rules[5] = new Rule(-4, new int[]{168});
    rules[6] = new Rule(-4, new int[]{169});
    rules[7] = new Rule(-4, new int[]{167});
    rules[8] = new Rule(-4, new int[]{-6});
    rules[9] = new Rule(-5, new int[]{164});
    rules[10] = new Rule(-6, new int[]{165});
    rules[11] = new Rule(-6, new int[]{166});
    rules[12] = new Rule(-7, new int[]{170});
    rules[13] = new Rule(-7, new int[]{-4});
    rules[14] = new Rule(-7, new int[]{40,-7,41});
    rules[15] = new Rule(-3, new int[]{40,-3,41});
    rules[16] = new Rule(-3, new int[]{-3,147,-8});
    rules[17] = new Rule(-3, new int[]{-3,146,-8});
    rules[18] = new Rule(-3, new int[]{-8});
    rules[19] = new Rule(-8, new int[]{161,-9});
    rules[20] = new Rule(-8, new int[]{161,40,-3,41});
    rules[21] = new Rule(-8, new int[]{-10});
    rules[22] = new Rule(-8, new int[]{-9});
    rules[23] = new Rule(-11, new int[]{-7});
    rules[24] = new Rule(-11, new int[]{-9});
    rules[25] = new Rule(-11, new int[]{40,-9,41});
    rules[26] = new Rule(-9, new int[]{-7,148,-11});
    rules[27] = new Rule(-9, new int[]{-7,152,-11});
    rules[28] = new Rule(-9, new int[]{-7,150,-11});
    rules[29] = new Rule(-9, new int[]{-7,151,-11});
    rules[30] = new Rule(-9, new int[]{-7,153,-11});
    rules[31] = new Rule(-9, new int[]{-7,149,-11});
    rules[32] = new Rule(-9, new int[]{-7,154,40,-12,41});
    rules[33] = new Rule(-12, new int[]{-11});
    rules[34] = new Rule(-12, new int[]{-12,44,-7});
    rules[35] = new Rule(-10, new int[]{-13});
    rules[36] = new Rule(-10, new int[]{-14});
    rules[37] = new Rule(-10, new int[]{-15});
    rules[38] = new Rule(-15, new int[]{118,40,-7,44,-11,41});
    rules[39] = new Rule(-14, new int[]{119,40,-7,44,-11,41});
    rules[40] = new Rule(-13, new int[]{139,40,-7,44,-11,41});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // stat -> expr
{ Result=ValueStack[ValueStack.Depth-1]; }
        break;
      case 3: // stat -> EOF
{ Result=null; }
        break;
      case 9: // null_symbol -> Null_LLC
{ CurrentSemanticValue =  GODataFilter.Null(); }
        break;
      case 10: // boolean_symbol -> True_LLC
{ CurrentSemanticValue =  GODataFilter.True(); }
        break;
      case 11: // boolean_symbol -> False_LLC
{ CurrentSemanticValue =  GODataFilter.False(); }
        break;
      case 12: // value -> ID
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 14: // value -> '(', value, ')'
{ CurrentSemanticValue=ValueStack[ValueStack.Depth-2]; }
        break;
      case 15: // expr -> '(', expr, ')'
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 16: // expr -> expr, Or_LLC, nexpr
{ CurrentSemanticValue = GODataFilter.Or(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 17: // expr -> expr, And_LLC, nexpr
{ CurrentSemanticValue =  GODataFilter.And(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 19: // nexpr -> Not_LLC, sexpr
{ CurrentSemanticValue = GODataFilter.Not(ValueStack[ValueStack.Depth-1]); }
        break;
      case 20: // nexpr -> Not_LLC, '(', expr, ')'
{ CurrentSemanticValue = GODataFilter.Not(ValueStack[ValueStack.Depth-2]); }
        break;
      case 23: // ve -> value
{CurrentSemanticValue=ValueStack[ValueStack.Depth-1];}
        break;
      case 24: // ve -> sexpr
{CurrentSemanticValue=ValueStack[ValueStack.Depth-1];}
        break;
      case 25: // ve -> '(', sexpr, ')'
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 26: // sexpr -> value, Eq_LLC, ve
{ CurrentSemanticValue = GODataFilter.Eq(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 27: // sexpr -> value, Gt_LLC, ve
{ CurrentSemanticValue = GODataFilter.Gt(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 28: // sexpr -> value, Lt_LLC, ve
{ CurrentSemanticValue = GODataFilter.Lt(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 29: // sexpr -> value, Le_LLC, ve
{ CurrentSemanticValue = GODataFilter.Le(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 30: // sexpr -> value, Ge_LLC, ve
{ CurrentSemanticValue = GODataFilter.Ge(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 31: // sexpr -> value, Ne_LLC, ve
{ CurrentSemanticValue = GODataFilter.Ne(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 32: // sexpr -> value, In_LLC, '(', in_value_list, ')'
{ CurrentSemanticValue = GODataFilter.In(ValueStack[ValueStack.Depth-5],ValueStack[ValueStack.Depth-2]); }
        break;
      case 33: // in_value_list -> ve
{ CurrentSemanticValue = new GODataFilter.TreeValueList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 34: // in_value_list -> in_value_list, ',', value
{ ((GODataFilter.TreeValueList)ValueStack[ValueStack.Depth-3]).Add(ValueStack[ValueStack.Depth-1]);CurrentSemanticValue=ValueStack[ValueStack.Depth-3]; }
        break;
      case 38: // containsMethodCallExpr -> Contains_LLC, '(', value, ',', ve, ')'
{ CurrentSemanticValue = GODataFilter.Contains(ValueStack[ValueStack.Depth-4],ValueStack[ValueStack.Depth-2]); }
        break;
      case 39: // startsWithMethodCallExpr -> StartsWith_LLC, '(', value, ',', ve, ')'
{ CurrentSemanticValue = GODataFilter.StartsWith(ValueStack[ValueStack.Depth-4],ValueStack[ValueStack.Depth-2]); }
        break;
      case 40: // endsWithMethodCallExpr -> EndsWith_LLC, '(', value, ',', ve, ')'
{ CurrentSemanticValue = GODataFilter.EndsWith(ValueStack[ValueStack.Depth-4],ValueStack[ValueStack.Depth-2]); }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

    public GODataFilterParser(string expression) : base(new Scanner()) { ((Scanner)Scanner).SetSource(expression,0); }


}
}
