<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  </PropertyGroup>       

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="document\DefaultDocument.cs" />
    <Compile Include="document\DocumentEventArgs.cs" />
    <Compile Include="document\DocumentFactory.cs" />
    <Compile Include="document\foldingstrategy\FoldStart.cs" />
    <Compile Include="document\highlightingstrategy\HighlightingDefinitionInvalidException.cs" />
    <Compile Include="document\IDocument.cs" />
    <Compile Include="document\ISegment.cs" />
    <Compile Include="document\linemanager\DeferredEventList.cs" />
    <Compile Include="document\linemanager\LineSegmentTree.cs" />
    <Compile Include="document\TextAnchor.cs" />
    <Compile Include="document\TextLocation.cs" />
    <Compile Include="document\TextUtilities.cs" />
    <Compile Include="document\bookmarkmanager\BookmarkManager.cs" />
    <Compile Include="document\bookmarkmanager\BookmarkManagerMemento.cs" />
    <Compile Include="document\formattingstrategy\DefaultFormattingStrategy.cs" />
    <Compile Include="document\formattingstrategy\IFormattingStrategy.cs" />
    <Compile Include="document\highlightingstrategy\DefaultHighlightingStrategy.cs" />
    <Compile Include="document\highlightingstrategy\FontContainer.cs" />
    <Compile Include="document\highlightingstrategy\HighlightBackground.cs" />
    <Compile Include="document\highlightingstrategy\HighlightColor.cs" />
    <Compile Include="document\highlightingstrategy\HighlightInfo.cs" />
    <Compile Include="document\highlightingstrategy\HighlightingColorNotFoundException.cs" />
    <Compile Include="document\highlightingstrategy\HighlightingDefinitionParser.cs" />
    <Compile Include="document\highlightingstrategy\HighlightingManager.cs" />
    <Compile Include="document\highlightingstrategy\HighlightingStrategyFactory.cs" />
    <Compile Include="document\highlightingstrategy\HighlightRuleSet.cs" />
    <Compile Include="document\highlightingstrategy\IHighlightingStrategy.cs" />
    <Compile Include="document\highlightingstrategy\NextMarker.cs" />
    <Compile Include="document\highlightingstrategy\PrevMarker.cs" />
    <Compile Include="document\highlightingstrategy\Span.cs" />
    <Compile Include="document\highlightingstrategy\TextWord.cs" />
    <Compile Include="document\linemanager\LineManager.cs" />
    <Compile Include="document\linemanager\LineSegment.cs" />
    <Compile Include="document\linemanager\LineManagerEventArgs.cs" />
    <Compile Include="document\textbufferstrategy\GapTextBufferStrategy.cs" />
    <Compile Include="document\textbufferstrategy\ITextBufferStrategy.cs" />
    <Compile Include="document\textbufferstrategy\StringTextBufferStrategy.cs" />
    <Compile Include="misc\ContentCommands.cs" />
    <Compile Include="misc\searchandreplace\commands\SearchMainMenuCommands.cs" />
    <Compile Include="misc\searchandreplace\commands\SearchToolbarCommands.cs" />
    <Compile Include="misc\searchandreplace\engine\documentiterator\CurrentDocumentIterator.cs" />
    <Compile Include="misc\searchandreplace\engine\documentiterator\DirectoryDocumentIterator.cs" />
    <Compile Include="misc\searchandreplace\engine\documentiterator\IDocumentIterator.cs" />
    <Compile Include="misc\searchandreplace\engine\ITextIteratorBuilder.cs" />
    <Compile Include="misc\searchandreplace\engine\ProvidedDocumentInformation.cs" />
    <Compile Include="misc\searchandreplace\engine\Search.cs" />
    <Compile Include="misc\searchandreplace\engine\SearchReplaceManager.cs" />
    <Compile Include="misc\searchandreplace\engine\SearchReplaceUtilities.cs" />
    <Compile Include="misc\searchandreplace\engine\SearchResultMatch.cs" />
    <Compile Include="misc\searchandreplace\engine\searchstrategy\BoyerMooreSearchStrategy.cs" />
    <Compile Include="misc\searchandreplace\engine\searchstrategy\BruteForceSearchStrategy.cs" />
    <Compile Include="misc\searchandreplace\engine\searchstrategy\ISearchStrategy.cs" />
    <Compile Include="misc\searchandreplace\engine\searchstrategy\RegExSearchStrategy.cs" />
    <Compile Include="misc\searchandreplace\engine\searchstrategy\WildcardSearchStrategy.cs" />
    <Compile Include="misc\searchandreplace\engine\textiterator\ForwardTextIterator.cs" />
    <Compile Include="misc\searchandreplace\engine\textiterator\ForwardTextIteratorBuilder.cs" />
    <Compile Include="misc\searchandreplace\engine\textiterator\ITextIterator.cs" />
    <Compile Include="misc\searchandreplace\engine\TextSelection.cs" />
    <Compile Include="misc\searchandreplace\gui\SearchAndReplaceDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="misc\searchandreplace\gui\SearchAndReplacePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="misc\util\AsynchronousWaitDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="misc\util\AsynchronousWaitDialog.Designer.cs">
      <DependentUpon>AsynchronousWaitDialog.cs</DependentUpon>
    </Compile>
    <Compile Include="misc\util\commands\AbstractComboBoxCommand.cs" />
    <Compile Include="misc\util\commands\AbstractCommand.cs" />
    <Compile Include="misc\util\commands\AbstractMenuCommand.cs" />
    <Compile Include="misc\util\commands\IComboBoxCommand.cs" />
    <Compile Include="misc\util\commands\ICommand.cs" />
    <Compile Include="misc\util\commands\IMenuCommand.cs" />
    <Compile Include="misc\util\FileUtility.cs" />
    <Compile Include="misc\util\FormLocationHelper.cs" />
    <Compile Include="misc\util\ImageService.cs" />
    <Compile Include="misc\searchandreplace\SearchOptions.cs" />
    <Compile Include="misc\util\IProgressMonitor.cs" />
    <Compile Include="misc\util\MessageService.cs" />
    <Compile Include="misc\util\properties\Properties.cs" />
    <Compile Include="misc\util\properties\PropertyChangedEventArgs.cs" />
    <Compile Include="misc\util\PropertyService.cs" />
    <Compile Include="misc\xmlforms\BaseSharpDevelopUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="misc\xmlforms\DefaultObjectCreator.cs" />
    <Compile Include="misc\xmlforms\IObjectCreator.cs" />
    <Compile Include="misc\xmlforms\IPropertyValueCreator.cs" />
    <Compile Include="misc\xmlforms\IStringValueFilter.cs" />
    <Compile Include="misc\xmlforms\SharpDevelopPropertyValueCreator.cs" />
    <Compile Include="misc\xmlforms\SharpDevelopStringValueFilter.cs" />
    <Compile Include="misc\xmlforms\XmlLoader.cs" />
    <Compile Include="misc\xmlforms\XmlUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="util\AugmentableRedBlackTree.cs" />
    <Compile Include="util\CheckedList.cs" />
    <Compile Include="util\LoggingService.cs" />
    <Compile Include="util\LookupTable.cs" />
    <Compile Include="util\MouseWheelHandler.cs" />
    <Compile Include="util\RedBlackTreeIterator.cs" />
    <Compile Include="util\TextUtility.cs" />
    <Compile Include="undo\UndoableDelete.cs" />
    <Compile Include="undo\UndoableInsert.cs" />
    <Compile Include="undo\UndoableReplace.cs" />
    <Compile Include="actions\ClipBoardActions.cs" />
    <Compile Include="actions\CaretActions.cs" />
    <Compile Include="actions\HomeEndActions.cs" />
    <Compile Include="actions\IEditAction.cs" />
    <Compile Include="actions\MiscActions.cs" />
    <Compile Include="actions\SelectionActions.cs" />
    <Compile Include="document\selection\ISelection.cs" />
    <Compile Include="document\selection\DefaultSelection.cs" />
    <Compile Include="document\foldingstrategy\IFoldingStrategy.cs" />
    <Compile Include="document\foldingstrategy\IndentFoldingStrategy.cs" />
    <Compile Include="gui\Ime.cs" />
    <Compile Include="gui\TextAreaUpdate.cs" />
    <Compile Include="document\selection\SelectionManager.cs" />
    <Compile Include="gui\completionwindow\ICompletionData.cs" />
    <Compile Include="gui\completionwindow\ICompletionDataProvider.cs" />
    <Compile Include="gui\completionwindow\CodeCompletionWindow.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="gui\completionwindow\DeclarationViewWindow.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="gui\insightwindow\IInsightDataProvider.cs" />
    <Compile Include="gui\insightwindow\InsightWindow.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="util\RtfWriter.cs" />
    <Compile Include="document\foldingstrategy\FoldingManager.cs" />
    <Compile Include="document\AbstractSegment.cs" />
    <Compile Include="document\foldingstrategy\FoldMarker.cs" />
    <Compile Include="util\TipPainter.cs" />
    <Compile Include="util\TipSection.cs" />
    <Compile Include="util\TipText.cs" />
    <Compile Include="util\TipSplitter.cs" />
    <Compile Include="util\TipSpacer.cs" />
    <Compile Include="util\TipPainterTools.cs" />
    <Compile Include="document\ITextEditorProperties.cs" />
    <Compile Include="gui\Caret.cs" />
    <Compile Include="gui\TextArea.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="gui\TextEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="gui\TextEditorControlBase.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="gui\TextAreaClipboardHandler.cs" />
    <Compile Include="gui\TextView.cs" />
    <Compile Include="gui\GutterMargin.cs" />
    <Compile Include="gui\AbstractMargin.cs" />
    <Compile Include="undo\IUndoableOperation.cs" />
    <Compile Include="undo\UndoQueue.cs" />
    <Compile Include="undo\UndoStack.cs" />
    <Compile Include="gui\TextAreaControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="gui\TextAreaMouseHandler.cs" />
    <Compile Include="document\highlightingstrategy\syntaxmodes\ISyntaxModeFileProvider.cs" />
    <Compile Include="document\highlightingstrategy\syntaxmodes\SyntaxMode.cs" />
    <Compile Include="document\highlightingstrategy\syntaxmodes\ResourceSyntaxModeProvider.cs" />
    <Compile Include="gui\IconBarMargin.cs" />
    <Compile Include="gui\FoldMargin.cs" />
    <Compile Include="document\highlightingstrategy\syntaxmodes\FileSyntaxModeProvider.cs" />
    <Compile Include="document\selection\ColumnRange.cs" />
    <Compile Include="gui\TextAreaDragDropHandler.cs" />
    <Compile Include="gui\BracketHighlighter.cs" />
    <Compile Include="actions\BookmarkActions.cs" />
    <Compile Include="actions\FoldActions.cs" />
    <Compile Include="actions\FormatActions.cs" />
    <Compile Include="document\DefaultTextEditorProperties.cs" />
    <Compile Include="document\markerstrategy\MarkerStrategy.cs" />
    <Compile Include="document\markerstrategy\TextMarker.cs" />
    <Compile Include="gui\completionwindow\AbstractCompletionWindow.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="gui\completionwindow\CodeCompletionListView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="gui\BrushRegistry.cs" />
    <Compile Include="gui\HRuler.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="document\bookmarkmanager\Bookmark.cs" />
    <Compile Include="document\bookmarkmanager\BookmarkEventHandler.cs" />
    <Compile Include="configuration\AssemblyInfo.cs" />
    <Compile Include="util\FileReader.cs" />
    <Compile Include="gui\DrawableLine.cs" />
    <Compile Include="gui\ToolTipRequestEventArgs.cs" />
    <Compile Include="document\highlightingstrategy\SpanStack.cs" />
    <Compile Include="util\WeakCollection.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\Mode.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\SyntaxModes\ADT-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ALF-GRF-Mode.xshd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\SyntaxModes\ALF-GRR-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ALF-MSE-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ALF-RTF-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ASPX-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\BAT-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Boo-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Coco-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\GCSharp-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\GSQL-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ALF-OXS-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\CPP-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\CSharp-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\GRC-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\HTML-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ILAsm-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Java-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\JavaScript-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\ORACLESQL-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Patch-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\PHP-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Python-Line-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Python-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Python.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\SPG-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\SQL-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\SRx-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\SSR-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\Tex-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\VBNET-Mode.xshd" />
    <EmbeddedResource Include="Data\SyntaxModes\XML-Mode.xshd" />
    <EmbeddedResource Include="Resources\TextEditorControl.bmp" />
    <EmbeddedResource Include="Resources\Misc\SearchAndReplace\FindPanel.xfrm" />
    <EmbeddedResource Include="Resources\Misc\SearchAndReplace\ReplacePanel.xfrm" />
    <EmbeddedResource Include="Data\RightArrow.cur" />
    <EmbeddedResource Include="Data\SyntaxModes\SyntaxModes.xml" />
    <EmbeddedResource Include="Resources\Misc\SearchAndReplace\Icons.16x16.FindIcon.bmp" />
    <EmbeddedResource Include="Resources\Misc\SearchAndReplace\Icons.16x16.ReplaceIcon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Data\SyntaxModes\Copy of SQL-Mode.xshd" />
  </ItemGroup>
</Project>
