declare namespace Gordic.Data.Readers {
    /**
    * Klientská část AL - číselník kategorie deníku
    * keys : ["ktg_den"]
    * columns: ["ktg_den","ktg_den_txt","k_v"]
    * filters: ["ktg_den","ktg_den_txt","k_v"]
    */
    class Robctyp extends Base<Gordic.Data.Readers.RobctypDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RobctypDto {
		/**Autogenerated.*/
		ktg_den?: number|null;
		/**Autogenerated.*/
		ktg_den_txt?: string|null;
		/**Autogenerated.*/
		k_v?: number|null;
	}
	const enum RobctypDtoNames { ktg_den = "ktg_den", ktg_den_txt = "ktg_den_txt", k_v = "k_v",}
	const enum RobctypDtoFragments { ktg_den = "*", ktg_den_txt = "*", k_v = "*",}
	const enum RobctypDtoTypes { ktg_den = "number", ktg_den_txt = "string", k_v = "number",}
	const enum RobctypDtoTypeLengths {}

    /**
    * Klientská část AL - číselník typ události
    * keys : ["typ_vid"]
    * columns: ["typ_vid","typ_vid_txt","k_v"]
    * filters: ["typ_vid","typ_vid_txt","k_v"]
    */
    class Robcvid extends Base<Gordic.Data.Readers.RobcvidDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RobcvidDto {
		/**Autogenerated.*/
		typ_vid?: number|null;
		/**Autogenerated.*/
		typ_vid_txt?: string|null;
		/**Autogenerated.*/
		k_v?: number|null;
	}
	const enum RobcvidDtoNames { typ_vid = "typ_vid", typ_vid_txt = "typ_vid_txt", k_v = "k_v",}
	const enum RobcvidDtoFragments { typ_vid = "*", typ_vid_txt = "*", k_v = "*",}
	const enum RobcvidDtoTypes { typ_vid = "number", typ_vid_txt = "string", k_v = "number",}
	const enum RobcvidDtoTypeLengths {}

    /**
    * Klientská část AL - číselník Spojení pokladních sad předkontací a předkontací
    * keys : ["ixs_vpk","ixs_kon"]
    * columns: ["ixs_vpk","ixs_kon","aktivita","dat_zmena","zmenu_prov","typ_kon","kod","nazev","zkratka"]
    * filters: ["ixs_vpk","ixs_kon","aktivita","dat_zmena","zmenu_prov"]
    */
    class PokvkonDto extends Base<Gordic.Mtk.Interface.GPokvkonDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Klientská část AL - číselník Spojení funkce a pokladní knihy
    * keys : ["ixs_fun","ixp_den","subrada"]
    * columns: ["ixs_fun","ixp_den","subrada","aktivita","dat_od","dat_do","dat_zmena","zmenu_prov","ixs_fun","nazev"]
    * filters: ["ixs_fun","ixp_den","subrada","aktivita","dat_od","dat_do","dat_zmena","zmenu_prov"]
    */
    class PokvrfuDto extends Base<Gordic.Mtk.Interface.GPokvrfuDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Klientská část AL - Pokladní kniha
    * keys : ["ixp_den"]
    * columns: ["ixp_den","nazev","ixs_vpk"]
    * filters: ["ixp_den","nazev","ico","ucs","rok","aktivita"]
    */
    class Poksden extends Base<Gordic.Data.Readers.PoksdenDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface PoksdenDto {
		/**Autogenerated.*/
		ixp_den?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		ixs_vpk?: string|null;
	}
	const enum PoksdenDtoNames { ixp_den = "ixp_den", nazev = "nazev", ixs_vpk = "ixs_vpk",}
	const enum PoksdenDtoFragments { ixp_den = "*", nazev = "*", ixs_vpk = "*",}
	const enum PoksdenDtoTypes { ixp_den = "string", nazev = "string", ixs_vpk = "string",}
	const enum PoksdenDtoTypeLengths {}

    /**
    * Klientská část AL - Kontace pro knihu
    * keys : ["ixs_kon"]
    * columns: ["ixs_kon","kod","nazev"]
    * filters: ["ixs_kon","ixs_vpk","nazev","aktivita"]
    */
    class Pokvkon extends Base<Gordic.Data.Readers.PokvkonDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface PokvkonDto {
		/**Autogenerated.*/
		ixs_kon?: string|null;
		/**Autogenerated.*/
		kod?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
	}
	const enum PokvkonDtoNames { ixs_kon = "ixs_kon", kod = "kod", nazev = "nazev",}
	const enum PokvkonDtoFragments { ixs_kon = "*", kod = "*", nazev = "*",}
	const enum PokvkonDtoTypes { ixs_kon = "string", kod = "string", nazev = "string",}
	const enum PokvkonDtoTypeLengths {}

    /**
    * Klientská část AL - Pokladníci
    * keys : ["ixs_fun"]
    * columns: ["ixs_fun","nazev"]
    * filters: ["ixs_fun","ixp_den","nazev","aktivita"]
    */
    class Pokvrfu extends Base<Gordic.Data.Readers.PokvrfuDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface PokvrfuDto {
		/**Autogenerated.*/
		ixs_fun?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
	}
	const enum PokvrfuDtoNames { ixs_fun = "ixs_fun", nazev = "nazev",}
	const enum PokvrfuDtoFragments { ixs_fun = "*", nazev = "*",}
	const enum PokvrfuDtoTypes { ixs_fun = "string", nazev = "string",}
	const enum PokvrfuDtoTypeLengths {}

    /**
    * Klientská část AL - Knihy MTK
    * keys : ["ixp_dmd"]
    * columns: ["ixp_dmd","nazev","rok"]
    * filters: ["nazev","rok","ktg_den","aktivita","ixs_fun","s_uzavreno","ixp_dmd"]
    */
    class Robsdmd extends Base<Gordic.Data.Readers.RobsdmdDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RobsdmdDto {
		/**Autogenerated.*/
		ixp_dmd?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		rok?: number|null;
	}
	const enum RobsdmdDtoNames { ixp_dmd = "ixp_dmd", nazev = "nazev", rok = "rok",}
	const enum RobsdmdDtoFragments { ixp_dmd = "*", nazev = "*", rok = "*",}
	const enum RobsdmdDtoTypes { ixp_dmd = "string", nazev = "string", rok = "number",}
	const enum RobsdmdDtoTypeLengths {}

    /**
    * Klientská část AL - Číselník jmen
    * keys : ["jmeno"]
    * columns: ["jmeno","aktivita"]
    * filters: ["jmeno","aktivita"]
    */
    class Robsjme extends Base<Gordic.Data.Readers.RobsjmeDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RobsjmeDto {
		/**Autogenerated.*/
		jmeno?: string|null;
		/**Autogenerated.*/
		aktivita?: number|null;
	}
	const enum RobsjmeDtoNames { jmeno = "jmeno", aktivita = "aktivita",}
	const enum RobsjmeDtoFragments { jmeno = "*", aktivita = "*",}
	const enum RobsjmeDtoTypes { jmeno = "string", aktivita = "number",}
	const enum RobsjmeDtoTypeLengths {}

    /**
    * Klientská část AL - Číselník příjmení
    * keys : ["prijmeni"]
    * columns: ["prijmeni","aktivita"]
    * filters: ["prijmeni","aktivita"]
    */
    class Robspri extends Base<Gordic.Data.Readers.RobspriDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface RobspriDto {
		/**Autogenerated.*/
		prijmeni?: string|null;
		/**Autogenerated.*/
		aktivita?: number|null;
	}
	const enum RobspriDtoNames { prijmeni = "prijmeni", aktivita = "aktivita",}
	const enum RobspriDtoFragments { prijmeni = "*", aktivita = "*",}
	const enum RobspriDtoTypes { prijmeni = "string", aktivita = "number",}
	const enum RobspriDtoTypeLengths {}
}
declare namespace Gordic.Prefabs.Select {
    /**
    * Klientská část AL - číselník kategorie deníku
    * FieldOptions
    * itemTemplate: "{ktg_den_txt}"
    * helperColumns: ["ktg_den_txt"]
    *
    * DataReader 
    * keys: ["ktg_den"]
    * columns: ["ktg_den","ktg_den_txt","k_v"]
    * filters: ["ktg_den","ktg_den_txt","k_v"]
    */
    function robctyp(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RobctypDto>): GSelectBoxOptions<Gordic.Data.Readers.RobctypDto>;
    /**
    * Klientská část AL - číselník typ události
    * FieldOptions
    * itemTemplate: "{typ_vid_txt}"
    * helperColumns: ["typ_vid", "typ_vid_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["typ_vid"]
    * columns: ["typ_vid","typ_vid_txt","k_v"]
    * filters: ["typ_vid","typ_vid_txt","k_v"]
    */
    function robcvid(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RobcvidDto>): GSelectBoxOptions<Gordic.Data.Readers.RobcvidDto>;
    /**
    * Klientská část AL - číselník Spojení pokladních sad předkontací a předkontací
    * FieldOptions
    * itemTemplate: "{kod}"
    * helperColumns: ["ixs_kon", "kod", "nazev"]
    *
    * DataReader 
    * keys: ["ixs_vpk","ixs_kon"]
    * columns: ["ixs_vpk","ixs_kon","aktivita","dat_zmena","zmenu_prov","typ_kon","kod","nazev","zkratka"]
    * filters: ["ixs_vpk","ixs_kon","aktivita","dat_zmena","zmenu_prov"]
    */
    function pokvkonDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Mtk.Interface.GPokvkonDto>): GSelectBoxOptions<Gordic.Mtk.Interface.GPokvkonDto>;
    /**
    * Klientská část AL - číselník Spojení funkce a pokladní knihy
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev"]
    *
    * DataReader 
    * keys: ["ixs_fun","ixp_den","subrada"]
    * columns: ["ixs_fun","ixp_den","subrada","aktivita","dat_od","dat_do","dat_zmena","zmenu_prov","ixs_fun","nazev"]
    * filters: ["ixs_fun","ixp_den","subrada","aktivita","dat_od","dat_do","dat_zmena","zmenu_prov"]
    */
    function pokvrfuDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Mtk.Interface.GPokvrfuDto>): GSelectBoxOptions<Gordic.Mtk.Interface.GPokvrfuDto>;
    /**
    * Klientská část AL - Pokladní kniha
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev"]
    *
    * DataReader 
    * keys: ["ixp_den"]
    * columns: ["ixp_den","nazev","ixs_vpk"]
    * filters: ["ixp_den","nazev","ico","ucs","rok","aktivita"]
    */
    function poksden(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.PoksdenDto>): GSelectBoxOptions<Gordic.Data.Readers.PoksdenDto>;
    /**
    * Klientská část AL - Kontace pro knihu
    * FieldOptions
    * itemTemplate: "{kod}"
    * helperColumns: ["ixs_kon", "kod", "nazev"]
    *
    * DataReader 
    * keys: ["ixs_kon"]
    * columns: ["ixs_kon","kod","nazev"]
    * filters: ["ixs_kon","ixs_vpk","nazev","aktivita"]
    */
    function pokvkon(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.PokvkonDto>): GSelectBoxOptions<Gordic.Data.Readers.PokvkonDto>;
    /**
    * Klientská část AL - Pokladníci
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev"]
    *
    * DataReader 
    * keys: ["ixs_fun"]
    * columns: ["ixs_fun","nazev"]
    * filters: ["ixs_fun","ixp_den","nazev","aktivita"]
    */
    function pokvrfu(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.PokvrfuDto>): GSelectBoxOptions<Gordic.Data.Readers.PokvrfuDto>;
    /**
    * Klientská část AL - Knihy MTK
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ixp_dmd", "nazev", "rok"]
    *
    * DataReader 
    * keys: ["ixp_dmd"]
    * columns: ["ixp_dmd","nazev","rok"]
    * filters: ["nazev","rok","ktg_den","aktivita","ixs_fun","s_uzavreno","ixp_dmd"]
    */
    function robsdmd(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RobsdmdDto>): GSelectBoxOptions<Gordic.Data.Readers.RobsdmdDto>;
    /**
    * Klientská část AL - Číselník jmen
    * FieldOptions
    * itemTemplate: "{jmeno}"
    * helperColumns: ["jmeno"]
    *
    * DataReader 
    * keys: ["jmeno"]
    * columns: ["jmeno","aktivita"]
    * filters: ["jmeno","aktivita"]
    */
    function robsjme(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RobsjmeDto>): GSelectBoxOptions<Gordic.Data.Readers.RobsjmeDto>;
    /**
    * Klientská část AL - Číselník příjmení
    * FieldOptions
    * itemTemplate: "{prijmeni}"
    * helperColumns: ["prijmeni"]
    *
    * DataReader 
    * keys: ["prijmeni"]
    * columns: ["prijmeni","aktivita"]
    * filters: ["prijmeni","aktivita"]
    */
    function robspri(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.RobspriDto>): GSelectBoxOptions<Gordic.Data.Readers.RobspriDto>;}
declare namespace Gordic.Data.Selectors {
    /**
    * Klientská část AL - číselník Spojení pokladních sad předkontací a předkontací
    */
    function pokvkonDto(): Selectors.DefaultSelectorOptions<Gordic.Mtk.Interface.GPokvkonDto>;
    /**
    * Klientská část AL - Kontace pro knihu
    */
    function pokvkon(): Selectors.DefaultSelectorOptions<Gordic.Data.Readers.PokvkonDto>;
    /**
    * Klientská část AL - Knihy MTK
    */
    function robsdmd(): Selectors.DefaultSelectorOptions<Gordic.Data.Readers.RobsdmdDto>;}
