<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  </PropertyGroup>       

  <ItemGroup>
    <Reference Include="Gordic.General" />
    <Reference Include="Gordic.General.ApplicationClient" />
    <Reference Include="Gordic.General.WinApplication" />
    <Reference Include="Gordic.GFE.Parsers" />
    <Reference Include="Gordic.Report.Interface" />
    <Reference Include="Gordic.TextEditor" />
    <Reference Include="Gordic.WinForms.Controls" />
    <Reference Include="System" />
    <Reference Include="System.configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Design" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="application\CallHelper.cs" />
    <Compile Include="application\FormFillerHost.cs" />
    <Compile Include="gui\commands\Commands.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmSender.cs" />
    <Compile Include="texteditor\AddInTreeSyntaxModeProvider.cs" />
    <Compile Include="addIns\editor\ClipboardHandling.cs" />
    <Compile Include="addIns\editor\AdvancedHighlightingStrategy.cs" />
    <Compile Include="addIns\editor\FormFillerTextAreaControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="addIns\editor\IAdvancedHighlighter.cs" />
    <Compile Include="addIns\editor\TextEditorDisplayBinding.cs" />
    <Compile Include="addIns\editor\TextEditorDisplayBindingWrapper.cs" />
    <Compile Include="addIns\editor\FormFillerTextEditorProperties.cs" />
    <Compile Include="addIns\misc\AlfCompilationUnit.cs" />
    <Compile Include="addIns\misc\defaultconditionevaluators\ActiveWindowStateConditionEvaluator.cs" />
    <Compile Include="addIns\misc\defaultconditionevaluators\FormationTypeConditionEvaluator.cs" />
    <Compile Include="addIns\misc\defaultconditionevaluators\OpenWindowStateConditionEvaluator.cs" />
    <Compile Include="addIns\misc\defaultconditionevaluators\WindowActiveConditionEvaluator.cs" />
    <Compile Include="addIns\misc\startpage\ShowStartPageCommand.cs" />
    <Compile Include="addIns\misc\startpage\StartPane.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="addIns\structureview\StructureViewEntry.cs" />
    <Compile Include="addIns\structureview\StructureViewPad.cs" />
    <Compile Include="application\ApplicationKeyHandler.cs" />
    <Compile Include="application\MessageFilterManager.cs" />
    <Compile Include="application\StartupSettings.cs" />
    <Compile Include="application\StartDesktopCommand.cs" />
    <Compile Include="application\DefaultDesktop.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="gui\commands\ApplicationCommands.cs" />
    <Compile Include="gui\commands\FileCommands.cs" />
    <Compile Include="gui\commands\FileTabStripCommands.cs" />
    <Compile Include="gui\commands\ToolCommands.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmCompilationUnit.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmContainerControl.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmDisplayBinding.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmFiller.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmView.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmViewContent.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmFormationDocument.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmFormationProperties.cs" />
    <Compile Include="gui\displaybinding\ICurrentDocumentView.cs" />
    <Compile Include="gui\displaybinding\controls\DocfrmPagePanel.cs" />
    <Compile Include="gui\LayoutConfiguration.cs" />
    <Compile Include="gui\layout\FillerDesktopLayout.cs" />
    <Compile Include="gui\layout\FillerWorkspaceWindow.cs" />
    <Compile Include="gui\FormFillerProperties.cs" />
    <Compile Include="gui\SimpleDesktop.cs" />
    <Compile Include="gui\xmlforms\BaseXmlForm.cs" />
    <Compile Include="application\FormFillerMain.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="RevisionClass.cs" />
    <Compile Include="services\CompilationService.cs" />
    <Compile Include="services\file\FileChangeWatcher.cs" />
    <Compile Include="services\file\FileAgent.cs" />
    <Compile Include="services\file\FileServiceOpenedFile.cs" />
    <Compile Include="services\IconDescriptor.cs" />
    <Compile Include="services\ServiceService.cs" />
    <Compile Include="services\XmlDocumentService.cs" />
    <Compile Include="texteditor\SyntaxModeMaker.cs" />
    <Compile Include="services\ToolbarService.cs" />
    <Compile Include="winform\AbstractPadContent.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="addIns\editor\FormFillerTextAreaControl.resx">
      <DependentUpon>FormFillerTextAreaControl.cs</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="addIns\misc\startpage\StartPane.resx">
      <DependentUpon>StartPane.cs</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="application\DefaultDesktop.resx">
      <DependentUpon>DefaultDesktop.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Gordic.Gfe.FormFiller.resx">
      <LastGenOutput>Gordic.Report.Client.Exceptions.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Gordic.Gfe.FormFiller.Exceptions.resx">
      <LastGenOutput>Gordic.Report.Client.Exceptions.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="gui\displaybinding\controls\DocfrmContainerControl.resx">
      <DependentUpon>DocfrmContainerControl.cs</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="gui\layout\FillerWorkspaceWindow.resx">
      <DependentUpon>FillerWorkspaceWindow.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\config\StartPage.gconfig" />
    <EmbeddedResource Include="Resources\config\FormFiller.gconfig">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="GSAFRM01.hist.xml">
      <SubType>Designer</SubType>
    </Content>
    <Content Include="Properties\gordic.ico" />
    <None Include="Properties\launchSettings.json" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="app_release.config">
      <SubType>Designer</SubType>
    </None>
    <None Include="Properties\Gordic.Gfe.FormFiller.prj.config">
      <SubType>Designer</SubType>
    </None>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Include="Properties\Gordic.Gfe.FormFiller.Hist.xml">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
</Project>
