declare namespace Gordic.Data.Readers {
    /**
    * Klientská část AL - Správci pohledávek
    * keys: ["ixs_fun"]
    * columns: ["ixs_fun", "nazev", "ixp_den"]
    * filters: ["ixs_fun","ixp_den","nazev","aktivita"]
    */
    class Ddpvrfu extends Base<Gordic.Data.Readers.DdpvrfuDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface DdpvrfuDto {
		/**Autogenerated.*/
		ixs_fun?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
	}
	const enum DdpvrfuDtoNames { ixs_fun = "ixs_fun", nazev = "nazev",}
	const enum DdpvrfuDtoFragments { ixs_fun = "*", nazev = "*",}
	const enum DdpvrfuDtoTypes { ixs_fun = "string", nazev = "string",}
	const enum DdpvrfuDtoTypeLengths {}

    /**
    * Klientská část AL - číselník sprcdpl
    * keys: ["druh_pl"]
    * columns: ["druh_pl","druh_pl_txt"]
    * filters: ["druh_pl","druh_pl_txt","k_v","k_s","k_xml"]
    */
    class SprcdplDto extends Base<Gordic.Spr.Interface.GSprcdplDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcdplDtoDto = Gordic.Spr.Interface.GSprcdplDto;
    type SprcdplDtoDtoNames = Gordic.Spr.Interface.GSprcdplDtoNames;
    type SprcdplDtoDtoFragments = Gordic.Spr.Interface.GSprcdplDtoFragments;
    type SprcdplDtoDtoTypes = Gordic.Spr.Interface.GSprcdplDtoTypes;
    type SprcdplDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcdplDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcdpz
    * keys: ["duv_dotc"]
    * columns: ["duv_dotc","duv_dotc_txt","k_v","k_s","k_xml"]
    * filters: ["duv_dotc","duv_dotc_txt","k_v","k_s","k_xml"]
    */
    class SprcdpzDto extends Base<Gordic.Spr.Interface.GSprcdpzDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcdpzDtoDto = Gordic.Spr.Interface.GSprcdpzDto;
    type SprcdpzDtoDtoNames = Gordic.Spr.Interface.GSprcdpzDtoNames;
    type SprcdpzDtoDtoFragments = Gordic.Spr.Interface.GSprcdpzDtoFragments;
    type SprcdpzDtoDtoTypes = Gordic.Spr.Interface.GSprcdpzDtoTypes;
    type SprcdpzDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcdpzDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcdsa
    * keys: ["druh_sa"]
    * columns: ["druh_sa","druh_sa_txt"]
    * filters: ["druh_sa","druh_sa_txt","k_v","k_s","k_xml"]
    */
    class SprcdsaDto extends Base<Gordic.Spr.Interface.GSprcdsaDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcdsaDtoDto = Gordic.Spr.Interface.GSprcdsaDto;
    type SprcdsaDtoDtoNames = Gordic.Spr.Interface.GSprcdsaDtoNames;
    type SprcdsaDtoDtoFragments = Gordic.Spr.Interface.GSprcdsaDtoFragments;
    type SprcdsaDtoDtoTypes = Gordic.Spr.Interface.GSprcdsaDtoTypes;
    type SprcdsaDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcdsaDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcdur
    * keys: ["duv_urc"]
    * columns: ["duv_urc","duv_urc_txt","k_v","k_s","k_xml"]
    * filters: ["duv_urc","duv_urc_txt","k_v","k_s","k_xml"]
    */
    class SprcdurDto extends Base<Gordic.Spr.Interface.GSprcdurDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcdurDtoDto = Gordic.Spr.Interface.GSprcdurDto;
    type SprcdurDtoDtoNames = Gordic.Spr.Interface.GSprcdurDtoNames;
    type SprcdurDtoDtoFragments = Gordic.Spr.Interface.GSprcdurDtoFragments;
    type SprcdurDtoDtoTypes = Gordic.Spr.Interface.GSprcdurDtoTypes;
    type SprcdurDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcdurDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcmpr
    * keys: ["mpr"]
    * columns: ["mpr","mpr_txt","k_v","k_s","k_xml"]
    * filters: ["mpr","mpr_txt","k_v","k_s","k_xml"]
    */
    class SprcmprDto extends Base<Gordic.Spr.Interface.GSprcmprDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcmprDtoDto = Gordic.Spr.Interface.GSprcmprDto;
    type SprcmprDtoDtoNames = Gordic.Spr.Interface.GSprcmprDtoNames;
    type SprcmprDtoDtoFragments = Gordic.Spr.Interface.GSprcmprDtoFragments;
    type SprcmprDtoDtoTypes = Gordic.Spr.Interface.GSprcmprDtoTypes;
    type SprcmprDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcmprDtoTypeLengths;

    /**
    * Klientská část AL
    * keys: ["typ_pod"]
    * columns: ["typ_pod","typ_pod_txt"]
    * filters: ["typ_pod","typ_pod_txt","typ_sr","k_v","k_s","k_xml"]
    */
    class SprcpodDto extends Base<Gordic.Spr.Interface.GSprcpodDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcpodDtoDto = Gordic.Spr.Interface.GSprcpodDto;
    type SprcpodDtoDtoNames = Gordic.Spr.Interface.GSprcpodDtoNames;
    type SprcpodDtoDtoFragments = Gordic.Spr.Interface.GSprcpodDtoFragments;
    type SprcpodDtoDtoTypes = Gordic.Spr.Interface.GSprcpodDtoTypes;
    type SprcpodDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcpodDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcpvd
    * keys: ["typ_pvd"]
    * columns: ["typ_pvd","typ_pvd_txt","k_v","k_s","k_xml"]
    * filters: ["typ_pvd","typ_pvd_txt","k_v","k_s","k_xml"]
    */
    class SprcpvdDto extends Base<Gordic.Spr.Interface.GSprcpvdDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcpvdDtoDto = Gordic.Spr.Interface.GSprcpvdDto;
    type SprcpvdDtoDtoNames = Gordic.Spr.Interface.GSprcpvdDtoNames;
    type SprcpvdDtoDtoFragments = Gordic.Spr.Interface.GSprcpvdDtoFragments;
    type SprcpvdDtoDtoTypes = Gordic.Spr.Interface.GSprcpvdDtoTypes;
    type SprcpvdDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcpvdDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcrci
    * keys: ["rozsah_cin"]
    * columns: ["rozsah_cin","rozsah_cin_txt","k_v","k_s","k_xml"]
    * filters: ["rozsah_cin","rozsah_cin_txt","k_v","k_s","k_xml"]
    */
    class SprcrciDto extends Base<Gordic.Spr.Interface.GSprcrciDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcrciDtoDto = Gordic.Spr.Interface.GSprcrciDto;
    type SprcrciDtoDtoNames = Gordic.Spr.Interface.GSprcrciDtoNames;
    type SprcrciDtoDtoFragments = Gordic.Spr.Interface.GSprcrciDtoFragments;
    type SprcrciDtoDtoTypes = Gordic.Spr.Interface.GSprcrciDtoTypes;
    type SprcrciDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcrciDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcrsl
    * keys: ["rozsah_sl"]
    * columns: ["rozsah_sl","rozsah_sl_txt","k_v","k_s","k_xml"]
    * filters: ["rozsah_sl","rozsah_sl_txt","k_v","k_s","k_xml"]
    */
    class SprcrslDto extends Base<Gordic.Spr.Interface.GSprcrslDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcrslDtoDto = Gordic.Spr.Interface.GSprcrslDto;
    type SprcrslDtoDtoNames = Gordic.Spr.Interface.GSprcrslDtoNames;
    type SprcrslDtoDtoFragments = Gordic.Spr.Interface.GSprcrslDtoFragments;
    type SprcrslDtoDtoTypes = Gordic.Spr.Interface.GSprcrslDtoTypes;
    type SprcrslDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcrslDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcscj
    * keys: ["s_cj_jazyk"]
    * columns: ["s_cj_jazyk","s_cj_jazyk_txt","k_v","k_s"]
    * filters: ["s_cj_jazyk","s_cj_jazyk_txt","k_v","k_s"]
    */
    class SprcscjDto extends Base<Gordic.Spr.Interface.GSprcscjDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcscjDtoDto = Gordic.Spr.Interface.GSprcscjDto;
    type SprcscjDtoDtoNames = Gordic.Spr.Interface.GSprcscjDtoNames;
    type SprcscjDtoDtoFragments = Gordic.Spr.Interface.GSprcscjDtoFragments;
    type SprcscjDtoDtoTypes = Gordic.Spr.Interface.GSprcscjDtoTypes;
    type SprcscjDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcscjDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcslh
    * keys: ["stav_lh"]
    * columns: ["stav_lh","stav_lh_txt","k_v","k_s","k_xml"]
    * filters: ["stav_lh","stav_lh_txt","k_v","k_s","k_xml"]
    */
    class SprcslhDto extends Base<Gordic.Spr.Interface.GSprcslhDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcslhDtoDto = Gordic.Spr.Interface.GSprcslhDto;
    type SprcslhDtoDtoNames = Gordic.Spr.Interface.GSprcslhDtoNames;
    type SprcslhDtoDtoFragments = Gordic.Spr.Interface.GSprcslhDtoFragments;
    type SprcslhDtoDtoTypes = Gordic.Spr.Interface.GSprcslhDtoTypes;
    type SprcslhDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcslhDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcsta
    * keys: ["stav"]
    * columns: ["stav","stav_txt","k_v","k_s","k_xml"]
    * filters: ["stav","stav_txt","k_v","k_s","k_xml"]
    */
    class SprcstaDto extends Base<Gordic.Spr.Interface.GSprcstaDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcstaDtoDto = Gordic.Spr.Interface.GSprcstaDto;
    type SprcstaDtoDtoNames = Gordic.Spr.Interface.GSprcstaDtoNames;
    type SprcstaDtoDtoFragments = Gordic.Spr.Interface.GSprcstaDtoFragments;
    type SprcstaDtoDtoTypes = Gordic.Spr.Interface.GSprcstaDtoTypes;
    type SprcstaDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcstaDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcstu
    * keys: ["stav_ukn"]
    * columns: ["stav_ukn","stav_ukn_txt","k_v","k_s"]
    * filters: ["stav_ukn","stav_ukn_txt","k_v","k_s"]
    */
    class SprcstuDto extends Base<Gordic.Spr.Interface.GSprcstuDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcstuDtoDto = Gordic.Spr.Interface.GSprcstuDto;
    type SprcstuDtoDtoNames = Gordic.Spr.Interface.GSprcstuDtoNames;
    type SprcstuDtoDtoFragments = Gordic.Spr.Interface.GSprcstuDtoFragments;
    type SprcstuDtoDtoTypes = Gordic.Spr.Interface.GSprcstuDtoTypes;
    type SprcstuDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcstuDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprctpz
    * keys: ["typ_pz"]
    * columns: ["typ_pz","typ_pz_txt","k_v","k_s","k_xml"]
    * filters: ["typ_pz","typ_pz_txt","k_v","k_s","k_xml"]
    */
    class SprctpzDto extends Base<Gordic.Spr.Interface.GSprctpzDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprctpzDtoDto = Gordic.Spr.Interface.GSprctpzDto;
    type SprctpzDtoDtoNames = Gordic.Spr.Interface.GSprctpzDtoNames;
    type SprctpzDtoDtoFragments = Gordic.Spr.Interface.GSprctpzDtoFragments;
    type SprctpzDtoDtoTypes = Gordic.Spr.Interface.GSprctpzDtoTypes;
    type SprctpzDtoDtoTypeLengths = Gordic.Spr.Interface.GSprctpzDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprctrm
    * keys: ["typ_term"]
    * columns: ["typ_term","typ_term_txt","k_v","k_s","k_xml","s_cas"]
    * filters: ["typ_term","typ_term_txt","k_v","k_s","k_xml","s_cas"]
    */
    class SprctrmDto extends Base<Gordic.Spr.Interface.GSprctrmDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprctrmDtoDto = Gordic.Spr.Interface.GSprctrmDto;
    type SprctrmDtoDtoNames = Gordic.Spr.Interface.GSprctrmDtoNames;
    type SprctrmDtoDtoFragments = Gordic.Spr.Interface.GSprctrmDtoFragments;
    type SprctrmDtoDtoTypes = Gordic.Spr.Interface.GSprctrmDtoTypes;
    type SprctrmDtoDtoTypeLengths = Gordic.Spr.Interface.GSprctrmDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprctsc
    * keys: ["typ_sc"]
    * columns: ["typ_sc","typ_sc_txt","k_v","k_s","k_xml"]
    * filters: ["typ_sc","typ_sc_txt","k_v","k_s","k_xml"]
    */
    class SprctscDto extends Base<Gordic.Spr.Interface.GSprctscDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprctscDtoDto = Gordic.Spr.Interface.GSprctscDto;
    type SprctscDtoDtoNames = Gordic.Spr.Interface.GSprctscDtoNames;
    type SprctscDtoDtoFragments = Gordic.Spr.Interface.GSprctscDtoFragments;
    type SprctscDtoDtoTypes = Gordic.Spr.Interface.GSprctscDtoTypes;
    type SprctscDtoDtoTypeLengths = Gordic.Spr.Interface.GSprctscDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprctzk
    * keys: ["typ_zk"]
    * columns: ["typ_zk","typ_zk_txt","k_v","k_s","k_xml"]
    * filters: ["typ_zk","typ_zk_txt","k_v","k_s","k_xml"]
    */
    class SprctzkDto extends Base<Gordic.Spr.Interface.GSprctzkDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprctzkDtoDto = Gordic.Spr.Interface.GSprctzkDto;
    type SprctzkDtoDtoNames = Gordic.Spr.Interface.GSprctzkDtoNames;
    type SprctzkDtoDtoFragments = Gordic.Spr.Interface.GSprctzkDtoFragments;
    type SprctzkDtoDtoTypes = Gordic.Spr.Interface.GSprctzkDtoTypes;
    type SprctzkDtoDtoTypeLengths = Gordic.Spr.Interface.GSprctzkDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcuci
    * keys: ["ucinnost"]
    * columns: ["ucinnost","ucinnost_txt","k_v","k_s","k_xml"]
    * filters: ["ucinnost","ucinnost_txt","k_v","k_s","k_xml"]
    */
    class SprcuciDto extends Base<Gordic.Spr.Interface.GSprcuciDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcuciDtoDto = Gordic.Spr.Interface.GSprcuciDto;
    type SprcuciDtoDtoNames = Gordic.Spr.Interface.GSprcuciDtoNames;
    type SprcuciDtoDtoFragments = Gordic.Spr.Interface.GSprcuciDtoFragments;
    type SprcuciDtoDtoTypes = Gordic.Spr.Interface.GSprcuciDtoTypes;
    type SprcuciDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcuciDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprcucj
    * keys: ["typ_ucj"]
    * columns: ["typ_ucj","typ_ucj_txt","k_v","k_s","k_xml"]
    * filters: ["typ_ucj","typ_ucj_txt","k_v","k_s","k_xml"]
    */
    class SprcucjDto extends Base<Gordic.Spr.Interface.GSprcucjDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprcucjDtoDto = Gordic.Spr.Interface.GSprcucjDto;
    type SprcucjDtoDtoNames = Gordic.Spr.Interface.GSprcucjDtoNames;
    type SprcucjDtoDtoFragments = Gordic.Spr.Interface.GSprcucjDtoFragments;
    type SprcucjDtoDtoTypes = Gordic.Spr.Interface.GSprcucjDtoTypes;
    type SprcucjDtoDtoTypeLengths = Gordic.Spr.Interface.GSprcucjDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprczar
    * keys: ["druh_zar"]
    * columns: ["druh_zar","druh_zar_txt","k_v","k_s","k_xml"]
    * filters: ["druh_zar","druh_zar_txt","k_v","k_s","k_xml"]
    */
    class SprczarDto extends Base<Gordic.Spr.Interface.GSprczarDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprczarDtoDto = Gordic.Spr.Interface.GSprczarDto;
    type SprczarDtoDtoNames = Gordic.Spr.Interface.GSprczarDtoNames;
    type SprczarDtoDtoFragments = Gordic.Spr.Interface.GSprczarDtoFragments;
    type SprczarDtoDtoTypes = Gordic.Spr.Interface.GSprczarDtoTypes;
    type SprczarDtoDtoTypeLengths = Gordic.Spr.Interface.GSprczarDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprczpr
    * keys: ["zp_roz"]
    * columns: ["zp_roz","zp_roz_txt","k_v","k_s","k_xml"]
    * filters: ["zp_roz","zp_roz_txt","k_v","k_s","k_xml"]
    */
    class SprczprDto extends Base<Gordic.Spr.Interface.GSprczprDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprczprDtoDto = Gordic.Spr.Interface.GSprczprDto;
    type SprczprDtoDtoNames = Gordic.Spr.Interface.GSprczprDtoNames;
    type SprczprDtoDtoFragments = Gordic.Spr.Interface.GSprczprDtoFragments;
    type SprczprDtoDtoTypes = Gordic.Spr.Interface.GSprczprDtoTypes;
    type SprczprDtoDtoTypeLengths = Gordic.Spr.Interface.GSprczprDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprczpu
    * keys: ["zpu_pl"]
    * columns: ["zpu_pl","zpu_pl_txt"]
    * filters: ["zpu_pl","zpu_pl_txt","k_v","k_s","k_xml"]
    */
    class SprczpuDto extends Base<Gordic.Spr.Interface.GSprczpuDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprczpuDtoDto = Gordic.Spr.Interface.GSprczpuDto;
    type SprczpuDtoDtoNames = Gordic.Spr.Interface.GSprczpuDtoNames;
    type SprczpuDtoDtoFragments = Gordic.Spr.Interface.GSprczpuDtoFragments;
    type SprczpuDtoDtoTypes = Gordic.Spr.Interface.GSprczpuDtoTypes;
    type SprczpuDtoDtoTypeLengths = Gordic.Spr.Interface.GSprczpuDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprsduk
    * keys: ["ixs_duk"]
    * columns: ["ixs_duk","nazev","zakon_txt","topic_pokyn","topic_vzor","topic_pozn","s_lhuta","s_vyriz","lhuta","typ_ukn","skupina","podskupina","nazev_uziv"]
    * filters: ["ixs_duk","nazev","zakon_txt","topic_pokyn","topic_vzor","topic_pozn","s_lhuta","s_vyriz","lhuta","typ_ukn","skupina","podskupina","nazev_uziv","typ_vyberu_druhu_ukonu"]
    */
    class SprsdukDto extends Base<Gordic.Spr.Interface.GSprsdukProSprSpisDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprsdukDtoDto = Gordic.Spr.Interface.GSprsdukProSprSpisDto;
    type SprsdukDtoDtoNames = Gordic.Spr.Interface.GSprsdukProSprSpisDtoNames;
    type SprsdukDtoDtoFragments = Gordic.Spr.Interface.GSprsdukProSprSpisDtoFragments;
    type SprsdukDtoDtoTypes = Gordic.Spr.Interface.GSprsdukProSprSpisDtoTypes;
    type SprsdukDtoDtoTypeLengths = Gordic.Spr.Interface.GSprsdukProSprSpisDtoTypeLengths;

    /**
    * Klientská část AL - číselník Oprávněné úřední osoby
    * keys: ["ixs_ouo"]
    * columns: ["ixs_ouo","nazev","poznamka","aktivita"]
    * filters: ["ixs_ouo","nazev","poznamka","aktivita"]
    */
    class SprsouoAllDto extends Base<Gordic.Spr.Interface.GSprsouoAllDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprsouoAllDtoDto = Gordic.Spr.Interface.GSprsouoAllDto;
    type SprsouoAllDtoDtoNames = Gordic.Spr.Interface.GSprsouoAllDtoNames;
    type SprsouoAllDtoDtoFragments = Gordic.Spr.Interface.GSprsouoAllDtoFragments;
    type SprsouoAllDtoDtoTypes = Gordic.Spr.Interface.GSprsouoAllDtoTypes;
    type SprsouoAllDtoDtoTypeLengths = Gordic.Spr.Interface.GSprsouoAllDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprsouo
    * keys: ["ixs_ouo"]
    * columns: ["ixs_ouo", "ixs_ref", "ixs_fun", "nazev_ouo", "nazev_ref", "nazev_fun", "nazev_rf", "typ_ouo_txt"]
    * filters: ["ixs_ouo","ixs_dsr","ixs_ref","ixs_fun","nazev_ouo","nazev_ref","nazev_fun","nazev_rf","typ_ouo_txt","poznamka"]
    */
    class SprsouoDto extends Base<Gordic.Spr.Interface.GSprsouoDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprsouoDtoDto = Gordic.Spr.Interface.GSprsouoDto;
    type SprsouoDtoDtoNames = Gordic.Spr.Interface.GSprsouoDtoNames;
    type SprsouoDtoDtoFragments = Gordic.Spr.Interface.GSprsouoDtoFragments;
    type SprsouoDtoDtoTypes = Gordic.Spr.Interface.GSprsouoDtoTypes;
    type SprsouoDtoDtoTypeLengths = Gordic.Spr.Interface.GSprsouoDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprspsr
    * keys: ["ixs_psr"]
    * columns: ["ixs_psr","nazev","typ_sr","poznamka","aktivita","dat_zmena","zmenu_prov","nazev_4p","nazev_2p"]
    * filters: ["ixs_psr","nazev","typ_sr","poznamka","aktivita","dat_zmena","zmenu_prov","nazev_4p","nazev_2p"]
    */
    class SprspsrDto extends Base<Gordic.Spr.Interface.GSprspsrDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprspsrDtoDto = Gordic.Spr.Interface.GSprspsrDto;
    type SprspsrDtoDtoNames = Gordic.Spr.Interface.GSprspsrDtoNames;
    type SprspsrDtoDtoFragments = Gordic.Spr.Interface.GSprspsrDtoFragments;
    type SprspsrDtoDtoTypes = Gordic.Spr.Interface.GSprspsrDtoTypes;
    type SprspsrDtoDtoTypeLengths = Gordic.Spr.Interface.GSprspsrDtoTypeLengths;

    /**
    * Klientská část AL - číselník sprsvpr
    * keys: ["ixs_vpr"]
    * columns: ["ixs_vpr","zakon_txt","zakonik","paragraf","odstavec","pismeno","poznamka","aktivita","dat_zmena","zmenu_prov","typ_vpr","kategorie"]
    * filters: ["ixs_vpr","zakon_txt","zakonik","paragraf","odstavec","pismeno","poznamka","aktivita","dat_zmena","zmenu_prov","typ_vpr","kategorie"]
    */
    class SprsvprDto extends Base<Gordic.Spr.Interface.GSprsvprDto>
    {
        constructor(options?: IGReaderBase);
    }
    type SprsvprDtoDto = Gordic.Spr.Interface.GSprsvprDto;
    type SprsvprDtoDtoNames = Gordic.Spr.Interface.GSprsvprDtoNames;
    type SprsvprDtoDtoFragments = Gordic.Spr.Interface.GSprsvprDtoFragments;
    type SprsvprDtoDtoTypes = Gordic.Spr.Interface.GSprsvprDtoTypes;
    type SprsvprDtoDtoTypeLengths = Gordic.Spr.Interface.GSprsvprDtoTypeLengths;

    /**
    * Klientská část AL - číselník Důvod vazby
    * keys: ["ixs_dva"]
    * columns: ["ixs_dva","nazev","typ_vazby","aktivita"]
    * filters: ["ixs_dva","nazev","typ_vazby","aktivita"]
    */
    class WflsdvaSprDto extends Base<Gordic.Spr.Interface.GWflsdvaSprDto>
    {
        constructor(options?: IGReaderBase);
    }
    type WflsdvaSprDtoDto = Gordic.Spr.Interface.GWflsdvaSprDto;
    type WflsdvaSprDtoDtoNames = Gordic.Spr.Interface.GWflsdvaSprDtoNames;
    type WflsdvaSprDtoDtoFragments = Gordic.Spr.Interface.GWflsdvaSprDtoFragments;
    type WflsdvaSprDtoDtoTypes = Gordic.Spr.Interface.GWflsdvaSprDtoTypes;
    type WflsdvaSprDtoDtoTypeLengths = Gordic.Spr.Interface.GWflsdvaSprDtoTypeLengths;
}
declare namespace Gordic.Prefabs.Select {
    /**
    * Klientská část AL - Správci pohledávek
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev"]
    *
    * DataReader
    * keys: ["ixs_fun"]
    * columns: ["ixs_fun", "nazev", "ixp_den"]
    * filters: ["ixs_fun","ixp_den","nazev","aktivita"]
    */
    function ddpvrfu(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.DdpvrfuDto>): GSelectBoxOptions<Gordic.Data.Readers.DdpvrfuDto>;
    /**
    * Klientská část AL - číselník sprcdpl
    * FieldOptions
    * itemTemplate: "{druh_pl_txt}"
    * helperColumns: ["druh_pl", "druh_pl_txt"]
    *
    * DataReader
    * keys: ["druh_pl"]
    * columns: ["druh_pl","druh_pl_txt"]
    * filters: ["druh_pl","druh_pl_txt","k_v","k_s","k_xml"]
    */
    function sprcdplDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcdplDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcdplDto>;
    /**
    * Klientská část AL - číselník sprcdpz
    * FieldOptions
    * itemTemplate: "{duv_dotc_txt}"
    * helperColumns: ["duv_dotc","duv_dotc_txt"]
    *
    * DataReader
    * keys: ["duv_dotc"]
    * columns: ["duv_dotc","duv_dotc_txt","k_v","k_s","k_xml"]
    * filters: ["duv_dotc","duv_dotc_txt","k_v","k_s","k_xml"]
    */
    function sprcdpzDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcdpzDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcdpzDto>;
    /**
    * Klientská část AL - číselník sprcdsa
    * FieldOptions
    * itemTemplate: "{druh_sa_txt}"
    * helperColumns: ["druh_sa", "druh_sa_txt"]
    *
    * DataReader
    * keys: ["druh_sa"]
    * columns: ["druh_sa","druh_sa_txt"]
    * filters: ["druh_sa","druh_sa_txt","k_v","k_s","k_xml"]
    */
    function sprcdsaDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcdsaDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcdsaDto>;
    /**
    * Klientská část AL - číselník sprcdur
    * FieldOptions
    * itemTemplate: "{duv_urc_txt}"
    * helperColumns: ["duv_urc_txt"]
    *
    * DataReader
    * keys: ["duv_urc"]
    * columns: ["duv_urc","duv_urc_txt","k_v","k_s","k_xml"]
    * filters: ["duv_urc","duv_urc_txt","k_v","k_s","k_xml"]
    */
    function sprcdurDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcdurDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcdurDto>;
    /**
    * Klientská část AL - číselník sprcmpr
    * FieldOptions
    * itemTemplate: "{mpr_txt}"
    * helperColumns: ["mpr", "mpr_txt", "k_v", "k_s", "k_xml"]
    *
    * DataReader
    * keys: ["mpr"]
    * columns: ["mpr","mpr_txt","k_v","k_s","k_xml"]
    * filters: ["mpr","mpr_txt","k_v","k_s","k_xml"]
    */
    function sprcmprDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcmprDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcmprDto>;
    /**
    * Klientská část AL
    * FieldOptions
    * itemTemplate: "{typ_pod_txt}"
    * helperColumns: ["typ_pod", "typ_pod_txt"]
    *
    * DataReader
    * keys: ["typ_pod"]
    * columns: ["typ_pod","typ_pod_txt"]
    * filters: ["typ_pod","typ_pod_txt","typ_sr","k_v","k_s","k_xml"]
    */
    function sprcpodDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcpodDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcpodDto>;
    /**
    * Klientská část AL - číselník sprcpvd
    * FieldOptions
    * itemTemplate: "{typ_pvd_txt}"
    * helperColumns: ["typ_pvd", "typ_pvd_txt"]
    *
    * DataReader
    * keys: ["typ_pvd"]
    * columns: ["typ_pvd","typ_pvd_txt","k_v","k_s","k_xml"]
    * filters: ["typ_pvd","typ_pvd_txt","k_v","k_s","k_xml"]
    */
    function sprcpvdDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcpvdDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcpvdDto>;
    /**
    * Klientská část AL - číselník sprcrci
    * FieldOptions
    * itemTemplate: "{rozsah_cin_txt}"
    * helperColumns: ["rozsah_cin", "rozsah_cin_txt"]
    *
    * DataReader
    * keys: ["rozsah_cin"]
    * columns: ["rozsah_cin","rozsah_cin_txt","k_v","k_s","k_xml"]
    * filters: ["rozsah_cin","rozsah_cin_txt","k_v","k_s","k_xml"]
    */
    function sprcrciDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcrciDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcrciDto>;
    /**
    * Klientská část AL - číselník sprcrsl
    * FieldOptions
    * itemTemplate: "{rozsah_sl_txt}"
    * helperColumns: ["rozsah_sl","rozsah_sl_txt"]
    *
    * DataReader
    * keys: ["rozsah_sl"]
    * columns: ["rozsah_sl","rozsah_sl_txt","k_v","k_s","k_xml"]
    * filters: ["rozsah_sl","rozsah_sl_txt","k_v","k_s","k_xml"]
    */
    function sprcrslDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcrslDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcrslDto>;
    /**
    * Klientská část AL - číselník sprcscj
    * FieldOptions
    * itemTemplate: "{s_cj_jazyk_txt}"
    * helperColumns: ["s_cj_jazyk","s_cj_jazyk_txt"]
    *
    * DataReader
    * keys: ["s_cj_jazyk"]
    * columns: ["s_cj_jazyk","s_cj_jazyk_txt","k_v","k_s"]
    * filters: ["s_cj_jazyk","s_cj_jazyk_txt","k_v","k_s"]
    */
    function sprcscjDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcscjDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcscjDto>;
    /**
    * Klientská část AL - číselník sprcslh
    * FieldOptions
    * itemTemplate: "{stav_lh_txt}"
    * helperColumns: ["stav_lh","stav_lh_txt"]
    *
    * DataReader
    * keys: ["stav_lh"]
    * columns: ["stav_lh","stav_lh_txt","k_v","k_s","k_xml"]
    * filters: ["stav_lh","stav_lh_txt","k_v","k_s","k_xml"]
    */
    function sprcslhDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcslhDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcslhDto>;
    /**
    * Klientská část AL - číselník sprcsta
    * FieldOptions
    * itemTemplate: "{stav_txt}"
    * helperColumns: ["stav_txt"]
    *
    * DataReader
    * keys: ["stav"]
    * columns: ["stav","stav_txt","k_v","k_s","k_xml"]
    * filters: ["stav","stav_txt","k_v","k_s","k_xml"]
    */
    function sprcstaDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcstaDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcstaDto>;
    /**
    * Klientská část AL - číselník sprcstu
    * FieldOptions
    * itemTemplate: "{stav_ukn_txt}"
    * helperColumns: ["stav_ukn", "stav_ukn_txt", "k_v", "k_s"]
    *
    * DataReader
    * keys: ["stav_ukn"]
    * columns: ["stav_ukn","stav_ukn_txt","k_v","k_s"]
    * filters: ["stav_ukn","stav_ukn_txt","k_v","k_s"]
    */
    function sprcstuDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcstuDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcstuDto>;
    /**
    * Klientská část AL - číselník sprctpz
    * FieldOptions
    * itemTemplate: "{typ_pz_txt}"
    * helperColumns: ["typ_pz","typ_pz_txt"]
    *
    * DataReader
    * keys: ["typ_pz"]
    * columns: ["typ_pz","typ_pz_txt","k_v","k_s","k_xml"]
    * filters: ["typ_pz","typ_pz_txt","k_v","k_s","k_xml"]
    */
    function sprctpzDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprctpzDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprctpzDto>;
    /**
    * Klientská část AL - číselník sprctrm
    * FieldOptions
    * itemTemplate: "{typ_term_txt}"
    * helperColumns: ["typ_term","typ_term_txt"]
    *
    * DataReader
    * keys: ["typ_term"]
    * columns: ["typ_term","typ_term_txt","k_v","k_s","k_xml","s_cas"]
    * filters: ["typ_term","typ_term_txt","k_v","k_s","k_xml","s_cas"]
    */
    function sprctrmDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprctrmDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprctrmDto>;
    /**
    * Klientská část AL - číselník sprctsc
    * FieldOptions
    * itemTemplate: "{typ_sc_txt}"
    * helperColumns: ["typ_sc_txt"]
    *
    * DataReader
    * keys: ["typ_sc"]
    * columns: ["typ_sc","typ_sc_txt","k_v","k_s","k_xml"]
    * filters: ["typ_sc","typ_sc_txt","k_v","k_s","k_xml"]
    */
    function sprctscDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprctscDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprctscDto>;
    /**
    * Klientská část AL - číselník sprctzk
    * FieldOptions
    * itemTemplate: "{typ_zk_txt}"
    * helperColumns: ["typ_zk","typ_zk_txt"]
    *
    * DataReader
    * keys: ["typ_zk"]
    * columns: ["typ_zk","typ_zk_txt","k_v","k_s","k_xml"]
    * filters: ["typ_zk","typ_zk_txt","k_v","k_s","k_xml"]
    */
    function sprctzkDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprctzkDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprctzkDto>;
    /**
    * Klientská část AL - číselník sprcuci
    * FieldOptions
    * itemTemplate: "{ucinnost_txt}"
    * helperColumns: ["ucinnost_txt"]
    *
    * DataReader
    * keys: ["ucinnost"]
    * columns: ["ucinnost","ucinnost_txt","k_v","k_s","k_xml"]
    * filters: ["ucinnost","ucinnost_txt","k_v","k_s","k_xml"]
    */
    function sprcuciDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcuciDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcuciDto>;
    /**
    * Klientská část AL - číselník sprcucj
    * FieldOptions
    * itemTemplate: "{typ_ucj_txt}"
    * helperColumns: ["typ_ucj","typ_ucj_txt"]
    *
    * DataReader
    * keys: ["typ_ucj"]
    * columns: ["typ_ucj","typ_ucj_txt","k_v","k_s","k_xml"]
    * filters: ["typ_ucj","typ_ucj_txt","k_v","k_s","k_xml"]
    */
    function sprcucjDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprcucjDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprcucjDto>;
    /**
    * Klientská část AL - číselník sprczar
    * FieldOptions
    * itemTemplate: "{druh_zar_txt}"
    * helperColumns: ["druh_zar_txt", "druh_zar"]
    *
    * DataReader
    * keys: ["druh_zar"]
    * columns: ["druh_zar","druh_zar_txt","k_v","k_s","k_xml"]
    * filters: ["druh_zar","druh_zar_txt","k_v","k_s","k_xml"]
    */
    function sprczarDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprczarDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprczarDto>;
    /**
    * Klientská část AL - číselník sprczpr
    * FieldOptions
    * itemTemplate: "{zp_roz_txt}"
    * helperColumns: ["zp_roz_txt"]
    *
    * DataReader
    * keys: ["zp_roz"]
    * columns: ["zp_roz","zp_roz_txt","k_v","k_s","k_xml"]
    * filters: ["zp_roz","zp_roz_txt","k_v","k_s","k_xml"]
    */
    function sprczprDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprczprDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprczprDto>;
    /**
    * Klientská část AL - číselník sprczpu
    * FieldOptions
    * itemTemplate: "{zpu_pl_txt}"
    * helperColumns: ["zpu_pl", "zpu_pl_txt"]
    *
    * DataReader
    * keys: ["zpu_pl"]
    * columns: ["zpu_pl","zpu_pl_txt"]
    * filters: ["zpu_pl","zpu_pl_txt","k_v","k_s","k_xml"]
    */
    function sprczpuDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprczpuDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprczpuDto>;
    /**
    * Klientská část AL - číselník sprsduk
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev", "zakon_txt"]
    *
    * DataReader
    * keys: ["ixs_duk"]
    * columns: ["ixs_duk","nazev","zakon_txt","topic_pokyn","topic_vzor","topic_pozn","s_lhuta","s_vyriz","lhuta","typ_ukn","skupina","podskupina","nazev_uziv"]
    * filters: ["ixs_duk","nazev","zakon_txt","topic_pokyn","topic_vzor","topic_pozn","s_lhuta","s_vyriz","lhuta","typ_ukn","skupina","podskupina","nazev_uziv","typ_vyberu_druhu_ukonu"]
    */
    function sprsdukDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprsdukProSprSpisDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprsdukProSprSpisDto>;
    /**
    * Klientská část AL - číselník Oprávněné úřední osoby
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev", "ixs_ouo"]
    *
    * DataReader
    * keys: ["ixs_ouo"]
    * columns: ["ixs_ouo","nazev","poznamka","aktivita"]
    * filters: ["ixs_ouo","nazev","poznamka","aktivita"]
    */
    function sprsouoAllDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprsouoAllDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprsouoAllDto>;
    /**
    * Klientská část AL - číselník sprsouo
    * FieldOptions
    * itemTemplate: "{nazev_rf}"
    * helperColumns: ["nazev_rf", "typ_ouo_txt"]
    *
    * DataReader
    * keys: ["ixs_ouo"]
    * columns: ["ixs_ouo", "ixs_ref", "ixs_fun", "nazev_ouo", "nazev_ref", "nazev_fun", "nazev_rf", "typ_ouo_txt"]
    * filters: ["ixs_ouo","ixs_dsr","ixs_ref","ixs_fun","nazev_ouo","nazev_ref","nazev_fun","nazev_rf","typ_ouo_txt","poznamka"]
    */
    function sprsouoDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprsouoDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprsouoDto>;
    /**
    * Klientská část AL - číselník sprspsr
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ixs_psr","nazev"]
    *
    * DataReader
    * keys: ["ixs_psr"]
    * columns: ["ixs_psr","nazev","typ_sr","poznamka","aktivita","dat_zmena","zmenu_prov","nazev_4p","nazev_2p"]
    * filters: ["ixs_psr","nazev","typ_sr","poznamka","aktivita","dat_zmena","zmenu_prov","nazev_4p","nazev_2p"]
    */
    function sprspsrDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprspsrDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprspsrDto>;
    /**
    * Klientská část AL - číselník sprsvpr
    * FieldOptions
    * itemTemplate: "{zakon_txt}"
    * helperColumns: ["ixs_vpr","zakon_txt"]
    *
    * DataReader
    * keys: ["ixs_vpr"]
    * columns: ["ixs_vpr","zakon_txt","zakonik","paragraf","odstavec","pismeno","poznamka","aktivita","dat_zmena","zmenu_prov","typ_vpr","kategorie"]
    * filters: ["ixs_vpr","zakon_txt","zakonik","paragraf","odstavec","pismeno","poznamka","aktivita","dat_zmena","zmenu_prov","typ_vpr","kategorie"]
    */
    function sprsvprDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GSprsvprDto>): GSelectBoxOptions<Gordic.Spr.Interface.GSprsvprDto>;
    /**
    * Klientská část AL - číselník Důvod vazby
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ixs_dva", "nazev"]
    *
    * DataReader
    * keys: ["ixs_dva"]
    * columns: ["ixs_dva","nazev","typ_vazby","aktivita"]
    * filters: ["ixs_dva","nazev","typ_vazby","aktivita"]
    */
    function wflsdvaSprDto(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Spr.Interface.GWflsdvaSprDto>): GSelectBoxOptions<Gordic.Spr.Interface.GWflsdvaSprDto>;}
declare namespace Gordic.Data.Selectors {
    /**
    * Klientská část AL - číselník sprsduk
    */
    function sprsdukDto(): Selectors.DefaultSelectorOptions<Gordic.Spr.Interface.GSprsdukProSprSpisDto>;}
