//  <FileHeader xmlns="http://www.gordic.cz/shared/file-header/v_1.0.0.0">
//    <Name>        Gordic.Report.Interface.IGGinsxme.cs                        </Name>
//    <Description> Rozhraní AL - Struktury (xme)                               </Description>
//    <Author>      Martin Aliger                                               </Author>
//    <Copyright>   © GORDIC spol. s r. o. 1993-2012                            </Copyright>
//    <Created>     2012-03-21                                                  </Created>
//  </FileHeader>

using System;
using System.Data;
using Gordic.General;
using Gordic.General.ApplicationInterface;

namespace Gordic.Report.Interface
{
	/// <summary>
    /// Rozhraní AL - Struktury (xme)
	/// </summary>
    [ActivatedObject("Gordic.Report.Server.GGinsxme")]
    public interface IGGinsxme : IGAppLogic
    {
        /// <summary>Získá data</summary>
        /// <param name="filters">Filtry, podle kterých se filtrují data z databáze (nebo cache)</param>
        /// <returns>Tabulka s daty</returns>
        GGinsxmeDataSet.SeznamDataTable GetData(params GFilter<FilterGinsxme>[] filters);
    }

    /// <summary>Autogenerated.</summary>
    public enum FilterGinsxme
    {
        /// <summary>Autogenerated.</summary>
        ixs_xme,
        /// <summary>Autogenerated.</summary>
        nazev,
        /// <summary>Autogenerated.</summary>
        aktivita,
        /// <summary>Autogenerated.</summary>
        poznamka,
        /// <summary>Autogenerated.</summary>
        xmeta_ver,
        /// <summary>Autogenerated.</summary>
        xmeta_subver,
    }
}
