/**
*   @copyright  © GORDIC spol. s r. o. 1993-2026
*   @version    498243
*
*   @file       fuc.client.types.d.ts
*    project     q:\ginis\Development\NET\Gordic.Fuc.Client\Gordic.Fuc.Client.csproj
*    created     2026-02-16 14:34:08
*    files       fuc.fields.d.ts
*/

//#region q:\ginis\Development\NET\Gordic.Fuc.Client\fuc.fields.d.ts 

declare namespace Gordic.Data.Readers {
    /**
    * Číselník Buccbvy (stavy bankovních výpisů) pro zápočtové listy
    * keys: ["s_bvy"]
    * columns: ["s_bvy","s_bvy_zl_txt"]
    * filters: ["s_bvy","s_bvy_zl_txt","NeLokalita"]
    */
    class BuccbvyZL extends Base<Gordic.Fuc.Interface.GBuccbvyDto>
    {
        constructor(options?: IGReaderBase);
    }
    type BuccbvyZLDto = Gordic.Fuc.Interface.GBuccbvyDto;
    type BuccbvyZLDtoNames = Gordic.Fuc.Interface.GBuccbvyDtoNames;
    type BuccbvyZLDtoFragments = Gordic.Fuc.Interface.GBuccbvyDtoFragments;
    type BuccbvyZLDtoTypes = Gordic.Fuc.Interface.GBuccbvyDtoTypes;
    type BuccbvyZLDtoTypeLengths = Gordic.Fuc.Interface.GBuccbvyDtoTypeLengths;

    /**
    * Klientská AL - číselník Bucspid (bankovní výpisy)
    * keys: ["ixp"]
    * columns: ["ixp","bu_vl","sk_vl","cis_pid","dat_nov_zus","rok_pid"]
    * filters: ["ixp","bu_vl","sk_vl","cis_pid","dat_nov_zus","rok_pid"]
    */
    class Bucspid extends Base<Gordic.Data.Readers.BucspidDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface BucspidDto {
		/**Autogenerated.*/
		ixp?: string|null;
		/**Autogenerated.*/
		bu_vl?: string|null;
		/**Autogenerated.*/
		sk_vl?: string|null;
		/**Autogenerated.*/
		rok_pid?: number|null;
		/**Autogenerated.*/
		cis_pid?: number|null;
		/**Autogenerated.*/
		dat_nov_zus?: JsonDate|null;
	}
	const enum BucspidDtoNames { ixp = "ixp", bu_vl = "bu_vl", sk_vl = "sk_vl", rok_pid = "rok_pid", cis_pid = "cis_pid", dat_nov_zus = "dat_nov_zus",}
	const enum BucspidDtoFragments { ixp = "*", bu_vl = "*", sk_vl = "*", rok_pid = "*", cis_pid = "*", dat_nov_zus = "*",}
	const enum BucspidDtoTypes { ixp = "string", bu_vl = "string", sk_vl = "string", rok_pid = "number", cis_pid = "number", dat_nov_zus = "JsonDate",}
	const enum BucspidDtoTypeLengths {}

    /**
    * Klientská AL - číselník Ekoaden (knihy)
    * keys: ["ixp_den"]
    * columns: ["ixp_den","nazev","typ_ag","zkr_ag"]
    * filters: ["ixp_den","nazev","typ_ag"]
    */
    class Ekoaden extends Base<Gordic.Data.Readers.EkoadenDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface EkoadenDto {
		/**Autogenerated.*/
		ixp_den?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		typ_ag?: number|null;
		/**Autogenerated.*/
		zkr_ag?: string|null;
	}
	const enum EkoadenDtoNames { ixp_den = "ixp_den", nazev = "nazev", typ_ag = "typ_ag", zkr_ag = "zkr_ag",}
	const enum EkoadenDtoFragments { ixp_den = "*", nazev = "*", typ_ag = "*", zkr_ag = "*",}
	const enum EkoadenDtoTypes { ixp_den = "string", nazev = "string", typ_ag = "number", zkr_ag = "string",}
	const enum EkoadenDtoTypeLengths {}

    /**
    * Klientská AL - číselník Ekoakon (kontace)
    * keys: ["ixs_kon"]
    * columns: ["ixs_kon","kod","nazev","typ_ag","zkr_ag"]
    * filters: ["ixs_kon","kod","nazev","typ_ag"]
    */
    class Ekoakon extends Base<Gordic.Data.Readers.EkoakonDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface EkoakonDto {
		/**Autogenerated.*/
		ixs_kon?: string|null;
		/**Autogenerated.*/
		kod?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		typ_ag?: number|null;
		/**Autogenerated.*/
		zkr_ag?: string|null;
	}
	const enum EkoakonDtoNames { ixs_kon = "ixs_kon", kod = "kod", nazev = "nazev", typ_ag = "typ_ag", zkr_ag = "zkr_ag",}
	const enum EkoakonDtoFragments { ixs_kon = "*", kod = "*", nazev = "*", typ_ag = "*", zkr_ag = "*",}
	const enum EkoakonDtoTypes { ixs_kon = "string", kod = "string", nazev = "string", typ_ag = "number", zkr_ag = "string",}
	const enum EkoakonDtoTypeLengths {}

    /**
    * Klientská AL - číselník Ekocsuh (stavy úhrady)
    * keys: ["s_uhr"]
    * columns: ["s_uhr","s_uhr_txt"]
    * filters: ["s_uhr","s_uhr_txt"]
    */
    class Ekocsuh extends Base<Gordic.Data.Readers.EkocsuhDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface EkocsuhDto {
		/**Autogenerated.*/
		s_uhr?: number|null;
		/**Autogenerated.*/
		s_uhr_txt?: string|null;
	}
	const enum EkocsuhDtoNames { s_uhr = "s_uhr", s_uhr_txt = "s_uhr_txt",}
	const enum EkocsuhDtoFragments { s_uhr = "*", s_uhr_txt = "*",}
	const enum EkocsuhDtoTypes { s_uhr = "number", s_uhr_txt = "string",}
	const enum EkocsuhDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccdpo (druhy pohybů)
    * keys: ["druh_poh"]
    * columns: ["druh_poh","druh_poh_txt"]
    * filters: ["druh_poh","druh_poh_txt"]
    */
    class Fuccdpo extends Base<Gordic.Data.Readers.FuccdpoDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccdpoDto {
		/**Autogenerated.*/
		druh_poh?: number|null;
		/**Autogenerated.*/
		druh_poh_txt?: string|null;
	}
	const enum FuccdpoDtoNames { druh_poh = "druh_poh", druh_poh_txt = "druh_poh_txt",}
	const enum FuccdpoDtoFragments { druh_poh = "*", druh_poh_txt = "*",}
	const enum FuccdpoDtoTypes { druh_poh = "number", druh_poh_txt = "string",}
	const enum FuccdpoDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccdup (druhy pohybů)
    * keys: ["druh_upo"]
    * columns: ["druh_upo","druh_upo_txt"]
    * filters: ["druh_upo","druh_upo_txt"]
    */
    class Fuccdup extends Base<Gordic.Data.Readers.FuccdupDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccdupDto {
		/**Autogenerated.*/
		druh_upo?: number|null;
		/**Autogenerated.*/
		druh_upo_txt?: string|null;
	}
	const enum FuccdupDtoNames { druh_upo = "druh_upo", druh_upo_txt = "druh_upo_txt",}
	const enum FuccdupDtoFragments { druh_upo = "*", druh_upo_txt = "*",}
	const enum FuccdupDtoTypes { druh_upo = "number", druh_upo_txt = "string",}
	const enum FuccdupDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fucckup (kategorie účtovaných pohybů)
    * keys: ["uct_poh"]
    * columns: ["uct_poh","uct_poh_txt"]
    * filters: ["uct_poh","uct_poh_txt"]
    */
    class Fucckup extends Base<Gordic.Data.Readers.FucckupDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FucckupDto {
		/**Autogenerated.*/
		uct_poh?: number|null;
		/**Autogenerated.*/
		uct_poh_txt?: string|null;
	}
	const enum FucckupDtoNames { uct_poh = "uct_poh", uct_poh_txt = "uct_poh_txt",}
	const enum FucckupDtoFragments { uct_poh = "*", uct_poh_txt = "*",}
	const enum FucckupDtoTypes { uct_poh = "number", uct_poh_txt = "string",}
	const enum FucckupDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccpod (příznak odloženého zpracování)
    * keys: ["priz_odl"]
    * columns: ["priz_odl","priz_odl_txt"]
    * filters: ["priz_odl","priz_odl_txt"]
    */
    class Fuccpod extends Base<Gordic.Data.Readers.FuccpodDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccpodDto {
		/**Autogenerated.*/
		priz_odl?: number|null;
		/**Autogenerated.*/
		priz_odl_txt?: string|null;
	}
	const enum FuccpodDtoNames { priz_odl = "priz_odl", priz_odl_txt = "priz_odl_txt",}
	const enum FuccpodDtoFragments { priz_odl = "*", priz_odl_txt = "*",}
	const enum FuccpodDtoTypes { priz_odl = "number", priz_odl_txt = "string",}
	const enum FuccpodDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccsmp (stavy mylné platby)
    * keys: ["stav_mp"]
    * columns: ["stav_mp","stav_mp_txt","stav_mp_zkr"]
    * filters: ["stav_mp","stav_mp_txt","stav_mp_zkr"]
    */
    class Fuccsmp extends Base<Gordic.Data.Readers.FuccsmpDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccsmpDto {
		/**Autogenerated.*/
		stav_mp?: number|null;
		/**Autogenerated.*/
		stav_mp_txt?: string|null;
		/**Autogenerated.*/
		stav_mp_zkr?: string|null;
	}
	const enum FuccsmpDtoNames { stav_mp = "stav_mp", stav_mp_txt = "stav_mp_txt", stav_mp_zkr = "stav_mp_zkr",}
	const enum FuccsmpDtoFragments { stav_mp = "*", stav_mp_txt = "*", stav_mp_zkr = "*",}
	const enum FuccsmpDtoTypes { stav_mp = "number", stav_mp_txt = "string", stav_mp_zkr = "string",}
	const enum FuccsmpDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccsod (stavy odeslání k úhradě)
    * keys: ["s_ode"]
    * columns: ["s_ode","s_ode_txt"]
    * filters: ["s_ode","s_ode_txt"]
    */
    class Fuccsod extends Base<Gordic.Data.Readers.FuccsodDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccsodDto {
		/**Autogenerated.*/
		s_ode?: number|null;
		/**Autogenerated.*/
		s_ode_txt?: string|null;
	}
	const enum FuccsodDtoNames { s_ode = "s_ode", s_ode_txt = "s_ode_txt",}
	const enum FuccsodDtoFragments { s_ode = "*", s_ode_txt = "*",}
	const enum FuccsodDtoTypes { s_ode = "number", s_ode_txt = "string",}
	const enum FuccsodDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccspa (stavy párování)
    * keys: ["s_par"]
    * columns: ["s_par","s_par_txt"]
    * filters: ["s_par","s_par_txt"]
    */
    class Fuccspa extends Base<Gordic.Data.Readers.FuccspaDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccspaDto {
		/**Autogenerated.*/
		s_par?: number|null;
		/**Autogenerated.*/
		s_par_txt?: string|null;
	}
	const enum FuccspaDtoNames { s_par = "s_par", s_par_txt = "s_par_txt",}
	const enum FuccspaDtoFragments { s_par = "*", s_par_txt = "*",}
	const enum FuccspaDtoTypes { s_par = "number", s_par_txt = "string",}
	const enum FuccspaDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fuccspr (stavy přípravy k úhradě)
    * keys: ["s_prip"]
    * columns: ["s_prip","s_prip_txt"]
    * filters: ["s_prip","s_prip_txt"]
    */
    class Fuccspr extends Base<Gordic.Data.Readers.FuccsprDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FuccsprDto {
		/**Autogenerated.*/
		s_prip?: number|null;
		/**Autogenerated.*/
		s_prip_txt?: string|null;
	}
	const enum FuccsprDtoNames { s_prip = "s_prip", s_prip_txt = "s_prip_txt",}
	const enum FuccsprDtoFragments { s_prip = "*", s_prip_txt = "*",}
	const enum FuccsprDtoTypes { s_prip = "number", s_prip_txt = "string",}
	const enum FuccsprDtoTypeLengths {}

    /**
    * Číselník Fuccsso (stavy soupisky)
    * keys: ["s_soup"]
    * columns: ["s_soup","s_soup_txt"]
    * filters: ["s_soup","s_soup_txt"]
    */
    class Fuccsso extends Base<Gordic.Fuc.Interface.GFuccssoDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FuccssoDto = Gordic.Fuc.Interface.GFuccssoDto;
    type FuccssoDtoNames = Gordic.Fuc.Interface.GFuccssoDtoNames;
    type FuccssoDtoFragments = Gordic.Fuc.Interface.GFuccssoDtoFragments;
    type FuccssoDtoTypes = Gordic.Fuc.Interface.GFuccssoDtoTypes;
    type FuccssoDtoTypeLengths = Gordic.Fuc.Interface.GFuccssoDtoTypeLengths;

    /**
    * Číselník Fuccsuc (stavy účtování)
    * keys: ["stav_uctovani"]
    * columns: ["stav_uctovani","stav_uctovani_txt"]
    * filters: ["stav_uctovani","stav_uctovani_txt"]
    */
    class Fuccsuc extends Base<Gordic.Fuc.Interface.GFuccsucDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FuccsucDto = Gordic.Fuc.Interface.GFuccsucDto;
    type FuccsucDtoNames = Gordic.Fuc.Interface.GFuccsucDtoNames;
    type FuccsucDtoFragments = Gordic.Fuc.Interface.GFuccsucDtoFragments;
    type FuccsucDtoTypes = Gordic.Fuc.Interface.GFuccsucDtoTypes;
    type FuccsucDtoTypeLengths = Gordic.Fuc.Interface.GFuccsucDtoTypeLengths;

    /**
    * Číselník Fuccsuo (stavy pohybů)
    * keys: ["s_upo"]
    * columns: ["s_upo","s_upo_ur_txt"]
    * filters: ["s_upo","s_upo_txt","s_upo_rez_txt","s_upo_ur_txt"]
    */
    class Fuccsuo extends Base<Gordic.Fuc.Interface.GFuccsuoDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FuccsuoDto = Gordic.Fuc.Interface.GFuccsuoDto;
    type FuccsuoDtoNames = Gordic.Fuc.Interface.GFuccsuoDtoNames;
    type FuccsuoDtoFragments = Gordic.Fuc.Interface.GFuccsuoDtoFragments;
    type FuccsuoDtoTypes = Gordic.Fuc.Interface.GFuccsuoDtoTypes;
    type FuccsuoDtoTypeLengths = Gordic.Fuc.Interface.GFuccsuoDtoTypeLengths;

    /**
    * Číselník Fuccsuo (stavy rezervačních pohybů)
    * keys: ["s_upo"]
    * columns: ["s_upo","s_upo_rez_txt"]
    * filters: ["s_upo","s_upo_rez_txt"]
    */
    class FuccsuoR extends Base<Gordic.Fuc.Interface.GFuccsuoDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FuccsuoRDto = Gordic.Fuc.Interface.GFuccsuoDto;
    type FuccsuoRDtoNames = Gordic.Fuc.Interface.GFuccsuoDtoNames;
    type FuccsuoRDtoFragments = Gordic.Fuc.Interface.GFuccsuoDtoFragments;
    type FuccsuoRDtoTypes = Gordic.Fuc.Interface.GFuccsuoDtoTypes;
    type FuccsuoRDtoTypeLengths = Gordic.Fuc.Interface.GFuccsuoDtoTypeLengths;

    /**
    * Číselník Fuccsuo (stavy účetních pohybů)
    * keys: ["s_upo"]
    * columns: ["s_upo","s_upo_txt"]
    * filters: ["s_upo","s_upo_txt"]
    */
    class FuccsuoU extends Base<Gordic.Fuc.Interface.GFuccsuoDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FuccsuoUDto = Gordic.Fuc.Interface.GFuccsuoDto;
    type FuccsuoUDtoNames = Gordic.Fuc.Interface.GFuccsuoDtoNames;
    type FuccsuoUDtoFragments = Gordic.Fuc.Interface.GFuccsuoDtoFragments;
    type FuccsuoUDtoTypes = Gordic.Fuc.Interface.GFuccsuoDtoTypes;
    type FuccsuoUDtoTypeLengths = Gordic.Fuc.Interface.GFuccsuoDtoTypeLengths;

    /**
    * Číselník Fuccsup (stavy účetního případu)
    * keys: ["s_upr"]
    * columns: ["s_upr","s_upr_txt"]
    * filters: ["s_upr","s_upr_txt"]
    */
    class Fuccsup extends Base<Gordic.Fuc.Interface.GFuccsupDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FuccsupDto = Gordic.Fuc.Interface.GFuccsupDto;
    type FuccsupDtoNames = Gordic.Fuc.Interface.GFuccsupDtoNames;
    type FuccsupDtoFragments = Gordic.Fuc.Interface.GFuccsupDtoFragments;
    type FuccsupDtoTypes = Gordic.Fuc.Interface.GFuccsupDtoTypes;
    type FuccsupDtoTypeLengths = Gordic.Fuc.Interface.GFuccsupDtoTypeLengths;

    /**
    * Klientská AL - číselník Fucctuf (typy účtování FUC)
    * keys: ["typ_uct_fuc"]
    * columns: ["typ_uct_fuc","typ_uct_fuc_txt"]
    * filters: ["typ_uct_fuc","typ_uct_fuc_txt"]
    */
    class Fucctuf extends Base<Gordic.Data.Readers.FucctufDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface FucctufDto {
		/**Autogenerated.*/
		typ_uct_fuc?: number|null;
		/**Autogenerated.*/
		typ_uct_fuc_txt?: string|null;
	}
	const enum FucctufDtoNames { typ_uct_fuc = "typ_uct_fuc", typ_uct_fuc_txt = "typ_uct_fuc_txt",}
	const enum FucctufDtoFragments { typ_uct_fuc = "*", typ_uct_fuc_txt = "*",}
	const enum FucctufDtoTypes { typ_uct_fuc = "number", typ_uct_fuc_txt = "string",}
	const enum FucctufDtoTypeLengths {}

    /**
    * Klientská AL - číselník Fucspid (soupisky)
    * keys: ["ixp"]
    * columns: ["ixp","ac_ag","ac","typ_ag","popis","rok","s_soup"]
    * filters: ["ixp","ac_ag","ac","typ_ag","popis","rok","s_soup"]
    */
    class Fucspid extends Base<Gordic.Fuc.Interface.GSoupiskaDto>
    {
        constructor(options?: IGReaderBase);
    }
    type FucspidDto = Gordic.Fuc.Interface.GSoupiskaDto;
    type FucspidDtoNames = Gordic.Fuc.Interface.GSoupiskaDtoNames;
    type FucspidDtoFragments = Gordic.Fuc.Interface.GSoupiskaDtoFragments;
    type FucspidDtoTypes = Gordic.Fuc.Interface.GSoupiskaDtoTypes;
    type FucspidDtoTypeLengths = Gordic.Fuc.Interface.GSoupiskaDtoTypeLengths;

    /**
    * Klientská AL - číselník IdIissp (identifikace IISSP)
    * keys: ["id_hdr_ris","radek_hdr"]
    * columns: ["id_hdr_ris","radek_hdr"]
    * filters: ["id_hdr_ris","radek_hdr","nks","uea","ueb","uec","ued","uee","uef","ueg","ueh","uei","uej","te0","te1","te2","te3","te4","uek","uel","uem","uen","te5","te6","te7","te8","te9"]
    */
    class IdIissp extends Base<Gordic.Data.Readers.IdIisspDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface IdIisspDto {
		/**Autogenerated.*/
		id_hdr_ris?: string|null;
		/**Autogenerated.*/
		radek_hdr?: number|null;
	}
	const enum IdIisspDtoNames { id_hdr_ris = "id_hdr_ris", radek_hdr = "radek_hdr",}
	const enum IdIisspDtoFragments { id_hdr_ris = "*", radek_hdr = "*",}
	const enum IdIisspDtoTypes { id_hdr_ris = "string", radek_hdr = "number",}
	const enum IdIisspDtoTypeLengths {}

    /**
    * Klientská AL - číselník Intsdav (typy dávek)
    * keys: ["ixs_dav"]
    * columns: ["ixs_dav","nazev","aktivita"]
    * filters: ["ixs_dav","nazev","aktivita"]
    */
    class Intsdav extends Base<Gordic.Data.Readers.IntsdavDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface IntsdavDto {
		/**Autogenerated.*/
		ixs_dav?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		aktivita?: number|null;
	}
	const enum IntsdavDtoNames { ixs_dav = "ixs_dav", nazev = "nazev", aktivita = "aktivita",}
	const enum IntsdavDtoFragments { ixs_dav = "*", nazev = "*", aktivita = "*",}
	const enum IntsdavDtoTypes { ixs_dav = "string", nazev = "string", aktivita = "number",}
	const enum IntsdavDtoTypeLengths {}

    /**
    * Klientská AL - číselník Intsroz (lokality externích systémů)
    * keys: ["ixp_exs"]
    * columns: ["ixp_exs","nazev","aktivita","ixs_ext","ixs_ext_txt"]
    * filters: ["ixp_exs","nazev","aktivita","ixs_ext","ixs_ext_txt"]
    */
    class Intsroz extends Base<Gordic.Data.Readers.IntsrozDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface IntsrozDto {
		/**Autogenerated.*/
		ixp_exs?: string|null;
		/**Autogenerated.*/
		nazev?: string|null;
		/**Autogenerated.*/
		aktivita?: number|null;
		/**Autogenerated.*/
		ixs_ext?: string|null;
		/**Autogenerated.*/
		ixs_ext_txt?: string|null;
	}
	const enum IntsrozDtoNames { ixp_exs = "ixp_exs", nazev = "nazev", aktivita = "aktivita", ixs_ext = "ixs_ext", ixs_ext_txt = "ixs_ext_txt",}
	const enum IntsrozDtoFragments { ixp_exs = "*", nazev = "*", aktivita = "*", ixs_ext = "*", ixs_ext_txt = "*",}
	const enum IntsrozDtoTypes { ixp_exs = "string", nazev = "string", aktivita = "number", ixs_ext = "string", ixs_ext_txt = "string",}
	const enum IntsrozDtoTypeLengths {}

    /**
    * Klientská AL - číselník xxxxxxx (příznak daňového pohybu)
    * keys: ["priz_dd"]
    * columns: ["priz_dd","priz_dd_txt"]
    * filters: ["priz_dd","priz_dd_txt"]
    */
    class PrizDdPoh extends Base<Gordic.Data.Readers.PrizDdPohDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface PrizDdPohDto {
		/**Autogenerated.*/
		priz_dd?: number|null;
		/**Autogenerated.*/
		priz_dd_txt?: string|null;
	}
	const enum PrizDdPohDtoNames { priz_dd = "priz_dd", priz_dd_txt = "priz_dd_txt",}
	const enum PrizDdPohDtoFragments { priz_dd = "*", priz_dd_txt = "*",}
	const enum PrizDdPohDtoTypes { priz_dd = "number", priz_dd_txt = "string",}
	const enum PrizDdPohDtoTypeLengths {}

    /**
    * Klientská AL - číselník xxxxxxx (typ položek zápočtového listu
    * keys: ["typ_pol"]
    * columns: ["typ_pol", "typ_pol_txt", "ktg_typ"]
    * filters: ["typ_pol","typ_pol_txt","ktg_typ"]
    */
    class TypPolZL extends Base<Gordic.Data.Readers.TypPolZLDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface TypPolZLDto {
		/**Autogenerated.*/
		typ_pol?: number|null;
		/**Autogenerated.*/
		typ_pol_txt?: string|null;
		/**Autogenerated.*/
		ktg_typ?: number|null;
	}
	const enum TypPolZLDtoNames { typ_pol = "typ_pol", typ_pol_txt = "typ_pol_txt", ktg_typ = "ktg_typ",}
	const enum TypPolZLDtoFragments { typ_pol = "*", typ_pol_txt = "*", ktg_typ = "*",}
	const enum TypPolZLDtoTypes { typ_pol = "number", typ_pol_txt = "string", ktg_typ = "number",}
	const enum TypPolZLDtoTypeLengths {}
}
declare namespace Gordic.Prefabs.Select {
    /**
    * Číselník Buccbvy (stavy bankovních výpisů) pro zápočtové listy
    * FieldOptions
    * itemTemplate: "{s_bvy_zl_txt}"
    * helperColumns: ["s_bvy_zl_txt"]
    *
    * DataReader
    * keys: ["s_bvy"]
    * columns: ["s_bvy","s_bvy_zl_txt"]
    * filters: ["s_bvy","s_bvy_zl_txt","NeLokalita"]
    */
    function buccbvyZL(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GBuccbvyDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GBuccbvyDto>;
    /**
    * Klientská AL - číselník Bucspid (bankovní výpisy)
    * FieldOptions
    * itemTemplate: function
    * helperColumns: ["bu_vl", "sk_vl", "cis_pid", "rok_pid", "dat_nov_zus"]
    *
    * DataReader
    * keys: ["ixp"]
    * columns: ["ixp","bu_vl","sk_vl","cis_pid","dat_nov_zus","rok_pid"]
    * filters: ["ixp","bu_vl","sk_vl","cis_pid","dat_nov_zus","rok_pid"]
    */
    function bucspid(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.BucspidDto>): GSelectBoxOptions<Gordic.Data.Readers.BucspidDto>;
    /**
    * Klientská AL - číselník Ekoaden (knihy)
    * FieldOptions
    * itemTemplate: "[{zkr_ag}] {nazev}"
    * helperColumns: ["nazev"]
    *
    * DataReader
    * keys: ["ixp_den"]
    * columns: ["ixp_den","nazev","typ_ag","zkr_ag"]
    * filters: ["ixp_den","nazev","typ_ag"]
    */
    function ekoaden(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.EkoadenDto>): GSelectBoxOptions<Gordic.Data.Readers.EkoadenDto>;
    /**
    * Klientská AL - číselník Ekoakon (kontace)
    * FieldOptions
    * itemTemplate: "[{zkr_ag}] {kod} - {nazev}"
    * helperColumns: ["kod","nazev"]
    *
    * DataReader
    * keys: ["ixs_kon"]
    * columns: ["ixs_kon","kod","nazev","typ_ag","zkr_ag"]
    * filters: ["ixs_kon","kod","nazev","typ_ag"]
    */
    function ekoakon(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.EkoakonDto>): GSelectBoxOptions<Gordic.Data.Readers.EkoakonDto>;
    /**
    * Klientská AL - číselník Ekocsuh (stavy úhrady)
    * FieldOptions
    * itemTemplate: "{?}"
    * helperColumns: ["?"]
    *
    * DataReader
    * keys: ["s_uhr"]
    * columns: ["s_uhr","s_uhr_txt"]
    * filters: ["s_uhr","s_uhr_txt"]
    */
    function ekocsuh(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.EkocsuhDto>): GSelectBoxOptions<Gordic.Data.Readers.EkocsuhDto>;
    /**
    * Klientská AL - číselník Fuccdpo (druhy pohybů)
    * FieldOptions
    * itemTemplate: "{druh_poh_txt}"
    * helperColumns: ["druh_poh_txt"]
    *
    * DataReader
    * keys: ["druh_poh"]
    * columns: ["druh_poh","druh_poh_txt"]
    * filters: ["druh_poh","druh_poh_txt"]
    */
    function fuccdpo(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccdpoDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccdpoDto>;
    /**
    * Klientská AL - číselník Fuccdup (druhy pohybů)
    * FieldOptions
    * itemTemplate: "{druh_upo_txt}"
    * helperColumns: ["druh_upo_txt"]
    *
    * DataReader
    * keys: ["druh_upo"]
    * columns: ["druh_upo","druh_upo_txt"]
    * filters: ["druh_upo","druh_upo_txt"]
    */
    function fuccdup(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccdupDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccdupDto>;
    /**
    * Klientská AL - číselník Fucckup (kategorie účtovaných pohybů)
    * FieldOptions
    * itemTemplate: "{uct_poh_txt}"
    * helperColumns: ["uct_poh_txt"]
    *
    * DataReader
    * keys: ["uct_poh"]
    * columns: ["uct_poh","uct_poh_txt"]
    * filters: ["uct_poh","uct_poh_txt"]
    */
    function fucckup(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FucckupDto>): GSelectBoxOptions<Gordic.Data.Readers.FucckupDto>;
    /**
    * Klientská AL - číselník Fuccpod (příznak odloženého zpracování)
    * FieldOptions
    * itemTemplate: "{priz_odl_txt}"
    * helperColumns: ["priz_odl_txt"]
    *
    * DataReader
    * keys: ["priz_odl"]
    * columns: ["priz_odl","priz_odl_txt"]
    * filters: ["priz_odl","priz_odl_txt"]
    */
    function fuccpod(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccpodDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccpodDto>;
    /**
    * Klientská AL - číselník Fuccsmp (stavy mylné platby)
    * FieldOptions
    * itemTemplate: "{stav_mp_txt}"
    * helperColumns: ["stav_mp_txt"]
    *
    * DataReader
    * keys: ["stav_mp"]
    * columns: ["stav_mp","stav_mp_txt","stav_mp_zkr"]
    * filters: ["stav_mp","stav_mp_txt","stav_mp_zkr"]
    */
    function fuccsmp(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccsmpDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccsmpDto>;
    /**
    * Klientská AL - číselník Fuccsod (stavy odeslání k úhradě)
    * FieldOptions
    * itemTemplate: "{s_ode_txt}"
    * helperColumns: ["s_ode_txt"]
    *
    * DataReader
    * keys: ["s_ode"]
    * columns: ["s_ode","s_ode_txt"]
    * filters: ["s_ode","s_ode_txt"]
    */
    function fuccsod(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccsodDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccsodDto>;
    /**
    * Klientská AL - číselník Fuccspa (stavy párování)
    * FieldOptions
    * itemTemplate: "{s_par_txt}"
    * helperColumns: ["s_par_txt"]
    *
    * DataReader
    * keys: ["s_par"]
    * columns: ["s_par","s_par_txt"]
    * filters: ["s_par","s_par_txt"]
    */
    function fuccspa(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccspaDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccspaDto>;
    /**
    * Klientská AL - číselník Fuccspr (stavy přípravy k úhradě)
    * FieldOptions
    * itemTemplate: "{s_prip_txt}"
    * helperColumns: ["s_prip_txt"]
    *
    * DataReader
    * keys: ["s_prip"]
    * columns: ["s_prip","s_prip_txt"]
    * filters: ["s_prip","s_prip_txt"]
    */
    function fuccspr(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FuccsprDto>): GSelectBoxOptions<Gordic.Data.Readers.FuccsprDto>;
    /**
    * Číselník Fuccsso (stavy soupisky)
    * FieldOptions
    * itemTemplate: "{s_soup_txt}"
    * helperColumns: ["s_soup_txt"]
    *
    * DataReader
    * keys: ["s_soup"]
    * columns: ["s_soup","s_soup_txt"]
    * filters: ["s_soup","s_soup_txt"]
    */
    function fuccsso(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GFuccssoDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GFuccssoDto>;
    /**
    * Číselník Fuccsuc (stavy účtování)
    * FieldOptions
    * itemTemplate: "{stav_uctovani_txt}"
    * helperColumns: ["stav_uctovani_txt"]
    *
    * DataReader
    * keys: ["stav_uctovani"]
    * columns: ["stav_uctovani","stav_uctovani_txt"]
    * filters: ["stav_uctovani","stav_uctovani_txt"]
    */
    function fuccsuc(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GFuccsucDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GFuccsucDto>;
    /**
    * Číselník Fuccsuo (stavy pohybů)
    * FieldOptions
    * itemTemplate: "{s_upo_ur_txt}"
    * helperColumns: ["s_upo_ur_txt"]
    *
    * DataReader
    * keys: ["s_upo"]
    * columns: ["s_upo","s_upo_ur_txt"]
    * filters: ["s_upo","s_upo_txt","s_upo_rez_txt","s_upo_ur_txt"]
    */
    function fuccsuo(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GFuccsuoDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GFuccsuoDto>;
    /**
    * Číselník Fuccsuo (stavy rezervačních pohybů)
    * FieldOptions
    * itemTemplate: "{s_upo_rez_txt}"
    * helperColumns: ["s_upo_rez_txt"]
    *
    * DataReader
    * keys: ["s_upo"]
    * columns: ["s_upo","s_upo_rez_txt"]
    * filters: ["s_upo","s_upo_rez_txt"]
    */
    function fuccsuoR(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GFuccsuoDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GFuccsuoDto>;
    /**
    * Číselník Fuccsuo (stavy účetních pohybů)
    * FieldOptions
    * itemTemplate: "{s_upo_txt}"
    * helperColumns: ["s_upo_txt"]
    *
    * DataReader
    * keys: ["s_upo"]
    * columns: ["s_upo","s_upo_txt"]
    * filters: ["s_upo","s_upo_txt"]
    */
    function fuccsuoU(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GFuccsuoDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GFuccsuoDto>;
    /**
    * Číselník Fuccsup (stavy účetního případu)
    * FieldOptions
    * itemTemplate: "{s_upr_txt}"
    * helperColumns: ["s_upr_txt"]
    *
    * DataReader
    * keys: ["s_upr"]
    * columns: ["s_upr","s_upr_txt"]
    * filters: ["s_upr","s_upr_txt"]
    */
    function fuccsup(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GFuccsupDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GFuccsupDto>;
    /**
    * Klientská AL - číselník Fucctuf (typy účtování FUC)
    * FieldOptions
    * itemTemplate: "{typ_uct_fuc_txt}"
    * helperColumns: ["typ_uct_fuc_txt"]
    *
    * DataReader
    * keys: ["typ_uct_fuc"]
    * columns: ["typ_uct_fuc","typ_uct_fuc_txt"]
    * filters: ["typ_uct_fuc","typ_uct_fuc_txt"]
    */
    function fucctuf(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.FucctufDto>): GSelectBoxOptions<Gordic.Data.Readers.FucctufDto>;
    /**
    * Klientská AL - číselník Fucspid (soupisky)
    * FieldOptions
    * itemTemplate: function
    * helperColumns: ["ixp", "ac_ag", "ac", "typ_ag", "popis"]
    *
    * DataReader
    * keys: ["ixp"]
    * columns: ["ixp","ac_ag","ac","typ_ag","popis","rok","s_soup"]
    * filters: ["ixp","ac_ag","ac","typ_ag","popis","rok","s_soup"]
    */
    function fucspid(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Fuc.Interface.GSoupiskaDto>): GSelectBoxOptions<Gordic.Fuc.Interface.GSoupiskaDto>;
    /**
    * Klientská AL - číselník IdIissp (identifikace IISSP)
    * FieldOptions
    * itemTemplate: "{id_hdr_ris}, {radek_hdr}"
    * helperColumns: ["id_hdr_ris","radek_hdr"]
    *
    * DataReader
    * keys: ["id_hdr_ris","radek_hdr"]
    * columns: ["id_hdr_ris","radek_hdr"]
    * filters: ["id_hdr_ris","radek_hdr","nks","uea","ueb","uec","ued","uee","uef","ueg","ueh","uei","uej","te0","te1","te2","te3","te4","uek","uel","uem","uen","te5","te6","te7","te8","te9"]
    */
    function idIissp(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.IdIisspDto>): GSelectBoxOptions<Gordic.Data.Readers.IdIisspDto>;
    /**
    * Klientská AL - číselník Intsdav (typy dávek)
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev", "ixs_dav"]
    *
    * DataReader
    * keys: ["ixs_dav"]
    * columns: ["ixs_dav","nazev","aktivita"]
    * filters: ["ixs_dav","nazev","aktivita"]
    */
    function intsdav(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.IntsdavDto>): GSelectBoxOptions<Gordic.Data.Readers.IntsdavDto>;
    /**
    * Klientská AL - číselník Intsroz (lokality externích systémů)
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["nazev", "ixp_exs", "ixs_ext", "ixs_ext_txt"]
    *
    * DataReader
    * keys: ["ixp_exs"]
    * columns: ["ixp_exs","nazev","aktivita","ixs_ext","ixs_ext_txt"]
    * filters: ["ixp_exs","nazev","aktivita","ixs_ext","ixs_ext_txt"]
    */
    function intsroz(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.IntsrozDto>): GSelectBoxOptions<Gordic.Data.Readers.IntsrozDto>;
    /**
    * Klientská AL - číselník xxxxxxx (příznak daňového pohybu)
    * FieldOptions
    * itemTemplate: "{priz_dd_txt}"
    * helperColumns: ["priz_dd_txt"]
    *
    * DataReader
    * keys: ["priz_dd"]
    * columns: ["priz_dd","priz_dd_txt"]
    * filters: ["priz_dd","priz_dd_txt"]
    */
    function prizDdPoh(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.PrizDdPohDto>): GSelectBoxOptions<Gordic.Data.Readers.PrizDdPohDto>;
    /**
    * Klientská AL - číselník xxxxxxx (typ položek zápočtového listu
    * FieldOptions
    * itemTemplate: "{typ_pol_txt}"
    * helperColumns: ["typ_pol_txt"]
    *
    * DataReader
    * keys: ["typ_pol"]
    * columns: ["typ_pol", "typ_pol_txt", "ktg_typ"]
    * filters: ["typ_pol","typ_pol_txt","ktg_typ"]
    */
    function typPolZL(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.TypPolZLDto>): GSelectBoxOptions<Gordic.Data.Readers.TypPolZLDto>;}
declare namespace Gordic.Data.Selectors {
    /**
    * Klientská AL - číselník Bucspid (bankovní výpisy)
    */
    function bucspid(): Selectors.DefaultSelectorOptions<Gordic.Data.Readers.BucspidDto>;
    /**
    * Klientská AL - číselník Fucspid (soupisky)
    */
    function fucspid(): Selectors.DefaultSelectorOptions<Gordic.Fuc.Interface.GSoupiskaDto>;}

//#endregion

