// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.4.5
// Machine:  M-ALIGER2
// DateTime: 15.02.2017 10:52:13
// UserName: maliger
// Input file <Gordic.General.GDataExpressionParser.y - 14.03.2016 9:14:36>

// options: no-lines

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace Gordic.General.DataFilterParser
{
internal enum Tokens2 {error=63,EOF=64,OR=65,AND=66,
    NOT=67,NE=68,GE=69,LE=70,IN=71,IS=72,
    NULL=73,BETWEEN=74,LIKE=75,TextConstant=76,NumberConstant=77,ID=78};

internal class ExpressionParser: ShiftReduceParser<Gordic.General.GDataFilter.FilterTree, LexLocation>
{
  // Verbatim content from Gordic.General.GDataExpressionParser.y - 14.03.2016 9:14:36
    public Gordic.General.GDataFilter.FilterTree Result;
  // End verbatim content from Gordic.General.GDataExpressionParser.y - 14.03.2016 9:14:36

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[41];
  private static State[] states = new State[71];
  private static string[] nonTerms = new string[] {
      "stat", "$accept", "value", "literal", "in_value_list", "expr", "nexpr", 
      "sexpr", "ve", };

  static ExpressionParser() {
    states[0] = new State(new int[]{78,12,76,19,77,20,45,21,40,23,64,70},new int[]{-1,1,-3,3,-4,18});
    states[1] = new State(new int[]{64,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{43,4,45,6,42,8,47,10,64,-2});
    states[4] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,5,-4,18});
    states[5] = new State(new int[]{43,-10,45,6,42,8,47,10,64,-10,61,-10,62,-10,60,-10,70,-10,69,-10,68,-10,72,-10,75,-10,67,-10,71,-10,74,-10,41,-10,44,-10,66,-10});
    states[6] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,7,-4,18});
    states[7] = new State(new int[]{43,-11,45,-11,42,8,47,10,64,-11,61,-11,62,-11,60,-11,70,-11,69,-11,68,-11,72,-11,75,-11,67,-11,71,-11,74,-11,41,-11,44,-11,66,-11});
    states[8] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,9,-4,18});
    states[9] = new State(new int[]{43,-12,45,-12,42,-12,47,10,64,-12,61,-12,62,-12,60,-12,70,-12,69,-12,68,-12,72,-12,75,-12,67,-12,71,-12,74,-12,41,-12,44,-12,66,-12});
    states[10] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,11,-4,18});
    states[11] = new State(-13);
    states[12] = new State(new int[]{40,13,43,-7,45,-7,42,-7,47,-7,64,-7,61,-7,62,-7,60,-7,70,-7,69,-7,68,-7,72,-7,75,-7,67,-7,71,-7,74,-7,41,-7,44,-7,66,-7});
    states[13] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-5,14,-9,26,-3,27,-4,18,-8,34});
    states[14] = new State(new int[]{41,15,44,16});
    states[15] = new State(-9);
    states[16] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,17,-4,18});
    states[17] = new State(new int[]{43,4,45,6,42,8,47,10,41,-40,44,-40});
    states[18] = new State(-8);
    states[19] = new State(-4);
    states[20] = new State(-5);
    states[21] = new State(new int[]{77,22});
    states[22] = new State(-6);
    states[23] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,24,-4,18});
    states[24] = new State(new int[]{41,25,43,4,45,6,42,8,47,10});
    states[25] = new State(-14);
    states[26] = new State(-39);
    states[27] = new State(new int[]{43,4,45,6,42,8,47,10,61,28,62,32,60,35,70,37,69,39,68,41,72,43,75,47,67,49,71,60,74,64,41,-22,44,-22});
    states[28] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-9,29,-3,27,-4,18,-8,34});
    states[29] = new State(-25);
    states[30] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,31,-8,68,-4,18});
    states[31] = new State(new int[]{41,25,43,4,45,6,42,8,47,10,61,28,62,32,60,35,70,37,69,39,68,41,72,43,75,47,67,49,71,60,74,64});
    states[32] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-9,33,-3,27,-4,18,-8,34});
    states[33] = new State(-26);
    states[34] = new State(-23);
    states[35] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-9,36,-3,27,-4,18,-8,34});
    states[36] = new State(-27);
    states[37] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-9,38,-3,27,-4,18,-8,34});
    states[38] = new State(-28);
    states[39] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-9,40,-3,27,-4,18,-8,34});
    states[40] = new State(-29);
    states[41] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-9,42,-3,27,-4,18,-8,34});
    states[42] = new State(-30);
    states[43] = new State(new int[]{73,44,67,45});
    states[44] = new State(-31);
    states[45] = new State(new int[]{73,46});
    states[46] = new State(-32);
    states[47] = new State(new int[]{76,48});
    states[48] = new State(-33);
    states[49] = new State(new int[]{75,50,71,52,74,56});
    states[50] = new State(new int[]{76,51});
    states[51] = new State(-34);
    states[52] = new State(new int[]{40,53});
    states[53] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-5,54,-9,26,-3,27,-4,18,-8,34});
    states[54] = new State(new int[]{41,55,44,16});
    states[55] = new State(-36);
    states[56] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,57,-4,18});
    states[57] = new State(new int[]{66,58,43,4,45,6,42,8,47,10});
    states[58] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,59,-4,18});
    states[59] = new State(new int[]{43,4,45,6,42,8,47,10,41,-38,44,-38});
    states[60] = new State(new int[]{40,61});
    states[61] = new State(new int[]{78,12,76,19,77,20,45,21,40,30},new int[]{-5,62,-9,26,-3,27,-4,18,-8,34});
    states[62] = new State(new int[]{41,63,44,16});
    states[63] = new State(-35);
    states[64] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,65,-4,18});
    states[65] = new State(new int[]{66,66,43,4,45,6,42,8,47,10});
    states[66] = new State(new int[]{78,12,76,19,77,20,45,21,40,23},new int[]{-3,67,-4,18});
    states[67] = new State(new int[]{43,4,45,6,42,8,47,10,41,-37,44,-37});
    states[68] = new State(new int[]{41,69});
    states[69] = new State(-24);
    states[70] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,64});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-1, new int[]{64});
    rules[4] = new Rule(-4, new int[]{76});
    rules[5] = new Rule(-4, new int[]{77});
    rules[6] = new Rule(-4, new int[]{45,77});
    rules[7] = new Rule(-3, new int[]{78});
    rules[8] = new Rule(-3, new int[]{-4});
    rules[9] = new Rule(-3, new int[]{78,40,-5,41});
    rules[10] = new Rule(-3, new int[]{-3,43,-3});
    rules[11] = new Rule(-3, new int[]{-3,45,-3});
    rules[12] = new Rule(-3, new int[]{-3,42,-3});
    rules[13] = new Rule(-3, new int[]{-3,47,-3});
    rules[14] = new Rule(-3, new int[]{40,-3,41});
    rules[15] = new Rule(-6, new int[]{40,-6,41});
    rules[16] = new Rule(-6, new int[]{-6,65,-6});
    rules[17] = new Rule(-6, new int[]{-6,66,-6});
    rules[18] = new Rule(-6, new int[]{-7});
    rules[19] = new Rule(-7, new int[]{67,-8});
    rules[20] = new Rule(-7, new int[]{67,40,-6,41});
    rules[21] = new Rule(-7, new int[]{-8});
    rules[22] = new Rule(-9, new int[]{-3});
    rules[23] = new Rule(-9, new int[]{-8});
    rules[24] = new Rule(-9, new int[]{40,-8,41});
    rules[25] = new Rule(-8, new int[]{-3,61,-9});
    rules[26] = new Rule(-8, new int[]{-3,62,-9});
    rules[27] = new Rule(-8, new int[]{-3,60,-9});
    rules[28] = new Rule(-8, new int[]{-3,70,-9});
    rules[29] = new Rule(-8, new int[]{-3,69,-9});
    rules[30] = new Rule(-8, new int[]{-3,68,-9});
    rules[31] = new Rule(-8, new int[]{-3,72,73});
    rules[32] = new Rule(-8, new int[]{-3,72,67,73});
    rules[33] = new Rule(-8, new int[]{-3,75,76});
    rules[34] = new Rule(-8, new int[]{-3,67,75,76});
    rules[35] = new Rule(-8, new int[]{-3,71,40,-5,41});
    rules[36] = new Rule(-8, new int[]{-3,67,71,40,-5,41});
    rules[37] = new Rule(-8, new int[]{-3,74,-3,66,-3});
    rules[38] = new Rule(-8, new int[]{-3,67,74,-3,66,-3});
    rules[39] = new Rule(-5, new int[]{-9});
    rules[40] = new Rule(-5, new int[]{-5,44,-3});

    aliasses = new Dictionary<int, string>();
    aliasses.Add(68, "\"<>\"");
    aliasses.Add(69, "\">=\"");
    aliasses.Add(70, "\"<=\"");
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens2.error, (int)Tokens2.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // stat -> value
{ Result=ValueStack[ValueStack.Depth-1]; }
        break;
      case 3: // stat -> EOF
{ Result=null; }
        break;
      case 6: // literal -> '-', NumberConstant
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterLiteral(new GInt32(-1 * ((GInt32)(ValueStack[ValueStack.Depth-1].Value))));}
        break;
      case 7: // value -> ID
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterColumn(ValueStack[ValueStack.Depth-1].Name);}
        break;
      case 9: // value -> ID, '(', in_value_list, ')'
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterFunc(ValueStack[ValueStack.Depth-4].Name,ValueStack[ValueStack.Depth-2]);}
        break;
      case 10: // value -> value, '+', value
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterArithmetics(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.ArithmeticOperator.Plus,ValueStack[ValueStack.Depth-1]); }
        break;
      case 11: // value -> value, '-', value
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterArithmetics(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.ArithmeticOperator.Minus,ValueStack[ValueStack.Depth-1]); }
        break;
      case 12: // value -> value, '*', value
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterArithmetics(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.ArithmeticOperator.Multiply,ValueStack[ValueStack.Depth-1]); }
        break;
      case 13: // value -> value, '/', value
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterArithmetics(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.ArithmeticOperator.Divide,ValueStack[ValueStack.Depth-1]); }
        break;
      case 14: // value -> '(', value, ')'
{ CurrentSemanticValue=ValueStack[ValueStack.Depth-2]; }
        break;
      case 15: // expr -> '(', expr, ')'
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 16: // expr -> expr, OR, expr
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterTreeOr(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 17: // expr -> expr, AND, expr
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterTreeAnd(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1]); }
        break;
      case 19: // nexpr -> NOT, sexpr
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterTreeNot(ValueStack[ValueStack.Depth-1]); }
        break;
      case 20: // nexpr -> NOT, '(', expr, ')'
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterTreeNot(ValueStack[ValueStack.Depth-2]); }
        break;
      case 22: // ve -> value
{CurrentSemanticValue=ValueStack[ValueStack.Depth-1];}
        break;
      case 23: // ve -> sexpr
{CurrentSemanticValue=ValueStack[ValueStack.Depth-1];}
        break;
      case 24: // ve -> '(', sexpr, ')'
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 25: // sexpr -> value, '=', ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterComparisonPredicate(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.FilterOperator.Equal,ValueStack[ValueStack.Depth-1]); }
        break;
      case 26: // sexpr -> value, '>', ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterComparisonPredicate(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.FilterOperator.Greater,ValueStack[ValueStack.Depth-1]); }
        break;
      case 27: // sexpr -> value, '<', ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterComparisonPredicate(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.FilterOperator.Less,ValueStack[ValueStack.Depth-1]); }
        break;
      case 28: // sexpr -> value, "<=", ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterComparisonPredicate(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.FilterOperator.LessOrEqual,ValueStack[ValueStack.Depth-1]); }
        break;
      case 29: // sexpr -> value, ">=", ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterComparisonPredicate(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.FilterOperator.GreaterOrEqual,ValueStack[ValueStack.Depth-1]); }
        break;
      case 30: // sexpr -> value, "<>", ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterComparisonPredicate(ValueStack[ValueStack.Depth-3],Gordic.General.GDataFilter.FilterOperator.NotEqual,ValueStack[ValueStack.Depth-1]); }
        break;
      case 31: // sexpr -> value, IS, NULL
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterNullPredicate(ValueStack[ValueStack.Depth-3],true); }
        break;
      case 32: // sexpr -> value, IS, NOT, NULL
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterNullPredicate(ValueStack[ValueStack.Depth-4],false); }
        break;
      case 33: // sexpr -> value, LIKE, TextConstant
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterLikePredicate(ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1].Value,true); }
        break;
      case 34: // sexpr -> value, NOT, LIKE, TextConstant
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterLikePredicate(ValueStack[ValueStack.Depth-4],ValueStack[ValueStack.Depth-1].Value,false); }
        break;
      case 35: // sexpr -> value, IN, '(', in_value_list, ')'
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterInPredicate(ValueStack[ValueStack.Depth-5],(Gordic.General.GDataFilter.FilterValueList)ValueStack[ValueStack.Depth-2],true); }
        break;
      case 36: // sexpr -> value, NOT, IN, '(', in_value_list, ')'
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterInPredicate(ValueStack[ValueStack.Depth-6],(Gordic.General.GDataFilter.FilterValueList)ValueStack[ValueStack.Depth-2],false); }
        break;
      case 37: // sexpr -> value, BETWEEN, value, AND, value
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterBetweenPredicate(ValueStack[ValueStack.Depth-5],ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1],true); }
        break;
      case 38: // sexpr -> value, NOT, BETWEEN, value, AND, value
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterBetweenPredicate(ValueStack[ValueStack.Depth-6],ValueStack[ValueStack.Depth-3],ValueStack[ValueStack.Depth-1],false); }
        break;
      case 39: // in_value_list -> ve
{ CurrentSemanticValue = new Gordic.General.GDataFilter.FilterValueList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 40: // in_value_list -> in_value_list, ',', value
{ ((Gordic.General.GDataFilter.FilterValueList)ValueStack[ValueStack.Depth-3]).Add(ValueStack[ValueStack.Depth-1]);CurrentSemanticValue=ValueStack[ValueStack.Depth-3]; }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens2)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens2)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

    public ExpressionParser(string expression) : base(new Scanner()) { ((Scanner)Scanner).SetSource(expression,0); }


}
}
