<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>$(G_TargetF);$(G_TargetC)</TargetFrameworks>
	<PlatformTarget>AnyCPU</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  </PropertyGroup>       

  <ItemGroup>
	  <Reference Include="Gordic.General" />
	  <Reference Include="Gordic.General.ApplicationInterface" />
	  <Reference Include="Newtonsoft.Json" />
	  <Reference Include="NLog" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == '$(G_TargetF)'">
	  <Reference Include="Gordic.Adu.Interface" />
	  <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == '$(G_TargetC)'">
	  <Reference Include="System.Drawing.Common" />
	  <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Classes\GFrm.cs" />
    <Compile Include="Classes\IGReportGenerator.cs" />
    <Compile Include="Classes\IGReportConfiguration.cs" />
    <Compile Include="Classes\Gordic.Report.GAlCodedMemoryFile.cs" />
    <Compile Include="Classes\Gordic.Report.GBackedMemoryFile.cs" />
    <Compile Include="Classes\GReportDataAdapter.cs" />
    <Compile Include="CustomDialogs\GCustomDialogBuilder.cs" />
    <Compile Include="CustomDialogs\GSesControls.cs" />
    <Compile Include="ds\GGinsstr.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GGinsstr.xsd</DependentUpon>
    </Compile>
    <Compile Include="ds\GGinsalv.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GGinsalv.xsd</DependentUpon>
    </Compile>
    <Compile Include="ds\GGinsfrm.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GGinsfrm.xsd</DependentUpon>
    </Compile>
    <Compile Include="ds\GReportList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GReportList.xsd</DependentUpon>
    </Compile>
    <Compile Include="ds\GGinsxme.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GGinsxme.xsd</DependentUpon>
    </Compile>
    <Compile Include="Dto\GBatchesInfoDto.cs" />
    <Compile Include="Dto\GCreateReportAsyncDto.cs" />
    <Compile Include="Dto\GCustomDialogDto.cs" />
    <Compile Include="Dto\GFormatTypeInfoDto.cs" />
    <Compile Include="Dto\GReportDmsInfoDto.cs" />
    <Compile Include="Dto\GReportMinimalInfoDto.cs" />
    <Compile Include="Dto\GReportInfoDto.cs" />
    <Compile Include="Dto\GReportOutputInfoDto.cs" />
    <Compile Include="Dto\GReportProgressDto.cs" />
    <Compile Include="Dto\GSablonaKonvenceGordicDto.cs" />
    <Compile Include="Dto\GSablonaKonvenceGordicStrediska.cs" />
    <Compile Include="Implementation\Charting.cs" />
    <Compile Include="Implementation\GNativeStringCache.cs" />
    <Compile Include="Implementation\GLists.cs" />
    <Compile Include="Implementation\GReportXmeReader.cs" />
    <Compile Include="Implementation\GReportDataReader.cs" />
    <Compile Include="Implementation\GScriptEngine.cs" />
    <Compile Include="Implementation\InterfacesVidrun.cs" />
    <Compile Include="Interfaces\GReportDto.cs" />
    <Compile Include="Interfaces\IGReportDocument.cs" />
    <Compile Include="Interfaces\IGReportPublisher.cs" />
    <Compile Include="Interfaces\IGGinsxme.cs" />
    <Compile Include="Interfaces\IGReportVykaz.cs" />
    <Compile Include="Interfaces\IGReportList.cs" />
    <Compile Include="Interfaces\IGSablonaKonvenceGordic.cs" />
    <Compile Include="PdfEngine\GPdfEngine.cs" />
    <Compile Include="Classes\Gordic.Report.GOperationPrintParameters.cs" />
    <Compile Include="Classes\GReportConsts.cs" />
    <Compile Include="Interfaces\IGServerGFF.cs" />
    <Compile Include="Interfaces\IGServerGXL.cs" />
    <Compile Include="Classes\GReportDebugSupport.cs" />
    <Compile Include="Exceptions\GReportWebDialogException.cs" />
    <Compile Include="ds\GGinvfof.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GGinvfof.xsd</DependentUpon>
    </Compile>
    <Compile Include="Classes\GPrintFormatManager.cs" />
    <Compile Include="Classes\GPrintFormat.cs" />
    <Compile Include="Interfaces\IGGinvfof.cs" />
    <Compile Include="Interfaces\IGDmsSave.cs" />
    <Compile Include="ds\GGinlses.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GGinlses.xsd</DependentUpon>
    </Compile>
    <Compile Include="ds\GScheduledReportDataSet.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GScheduledReportDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Include="Interfaces\IGGinlses.cs" />
    <Compile Include="Implementation\Interfaces09.cs" />
    <Compile Include="Implementation\GReportSrzReader.cs" />
    <Compile Include="Implementation\GReportSsrReader.cs" />
    <Compile Include="Implementation\Interfaces08.cs" />
    <Compile Include="Implementation\Interfaces06.cs" />
    <Compile Include="PdfEngine\PdfAVerifier.cs" />
    <Compile Include="Classes\Gordic.Report.GMemoryFile.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Interfaces\Gordic.Report.IGMemoryFile.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Interfaces\Gordic.Report.IGReport.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Interfaces\Gordic.Report.IGReportImplementation.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Interfaces\Gordic.Report.IGReportMessageBoxes.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Interfaces\Gordic.Report.IGReportPaperSetting.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Interfaces\Gordic.Report.IGReportProvider.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Exceptions\GReportAbortException.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Classes\GReportCommon.cs" />
    <Compile Include="Classes\GReportDistributionType.cs" />
    <Compile Include="Exceptions\GReportException.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Classes\GReportIdentity.cs" />
    <Compile Include="Exceptions\GReportUserException.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Classes\GReportX0009.cs" />
    <Compile Include="Wrapper\GUnsafeRepWrapper.cs" />
    <Compile Include="Classes\GScheduledReportParameter.cs" />
    <Compile Include="Interfaces\IGPreselected.cs" />
    <Compile Include="Interfaces\IGReportAdmin.cs" />
    <Compile Include="Interfaces\IGScheduledReport.cs" />
    <Compile Include="ds\ListOfPreselectedDataset.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ListOfPreselectedDataset.xsd</DependentUpon>
    </Compile>
    <Compile Include="Classes\Gordic.Report.GReportHeader.cs" />
    <Compile Include="ds\SeznamFaziSestav.ds.cs">
      <DependentUpon>SeznamFaziSestav.ds.xsd</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="PdfEngine\sRGB.icc" />
    <EmbeddedResource Include="PdfEngine\ZapfDingbats.ttf" />
    <EmbeddedResource Include="PdfEngine\EuropeISOCoatedFOGRA27.icc" />
    <EmbeddedResource Include="Gordic.Report.Interface.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Gordic.Report.Interface.Exceptions.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Properties\Gordic.Report.Interface.Hist.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Classes\GScheduledReportParameter.d.ts">
      <DependentUpon>GScheduledReportParameter.cs</DependentUpon>
    </None>
    <None Include="ds\GGinlses.xsc">
      <DependentUpon>GGinlses.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinlses.xss">
      <DependentUpon>GGinlses.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinvfof.xsc">
      <DependentUpon>GGinvfof.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinvfof.xsd">
      <Generator>GDataSetGenerator</Generator>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
      <SubType>Designer</SubType>
      <LastGenOutput>GGinvfof.cs</LastGenOutput>
    </None>
    <None Include="ds\GGinvfof.xss">
      <DependentUpon>GGinvfof.xsd</DependentUpon>
    </None>
    <None Include="ds\GScheduledReportDataSet.xsd">
      <Generator>GDataSetGenerator</Generator>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
      <SubType />
      <LastGenOutput>GScheduledReportDataSet.cs</LastGenOutput>
    </None>
    <None Include="ds\GGinlses.xsd">
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>GGinlses.cs</LastGenOutput>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
      <SubType>Designer</SubType>
    </None>
    <None Include="ds\GGinsstr.xsc">
      <DependentUpon>GGinsstr.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsstr.xsd">
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>GGinsstr.cs</LastGenOutput>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
    </None>
    <None Include="ds\GGinsstr.xss">
      <DependentUpon>GGinsstr.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsalv.xsc">
      <DependentUpon>GGinsalv.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsalv.xsd">
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>GGinsalv.cs</LastGenOutput>
      <SubType>Designer</SubType>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
    </None>
    <None Include="ds\GGinsalv.xss">
      <DependentUpon>GGinsalv.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsfrm.xsc">
      <DependentUpon>GGinsfrm.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsfrm.xsd">
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>GGinsfrm.cs</LastGenOutput>
      <SubType>Designer</SubType>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
    </None>
    <None Include="ds\GGinsfrm.xss">
      <DependentUpon>GGinsfrm.xsd</DependentUpon>
    </None>
    <None Include="ds\GReportList.xsc">
      <DependentUpon>GReportList.xsd</DependentUpon>
    </None>
    <None Include="ds\GReportList.xsd">
      <SubType>Designer</SubType>
      <Generator>GDataSetGenerator</Generator>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
      <LastGenOutput>GReportList.cs</LastGenOutput>
    </None>
    <None Include="ds\GReportList.xss">
      <DependentUpon>GReportList.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsxme.xsc">
      <DependentUpon>GGinsxme.xsd</DependentUpon>
    </None>
    <None Include="ds\GGinsxme.xsd">
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>GGinsxme.cs</LastGenOutput>
      <SubType>Designer</SubType>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
    </None>
    <None Include="ds\GGinsxme.xss">
      <DependentUpon>GGinsxme.xsd</DependentUpon>
    </None>
    <None Include="ds\ListOfPreselectedDataset.xsd">
      <SubType />
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>ListOfPreselectedDataset.cs</LastGenOutput>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
    </None>
    <None Include="ds\SeznamFaziSestav.ds.xsd">
      <SubType />
      <Generator>GDataSetGenerator</Generator>
      <LastGenOutput>SeznamFaziSestav.ds.cs</LastGenOutput>
      <CustomToolNamespace>Gordic.Report.Interface</CustomToolNamespace>
    </None>
    <None Include="Dto\GBatchesInfoDto.d.ts">
      <DependentUpon>GBatchesInfoDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GCreateReportAsyncDto.d.ts">
      <DependentUpon>GCreateReportAsyncDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GCustomDialogDto.d.ts">
      <DependentUpon>GCustomDialogDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GFormatTypeInfoDto.d.ts">
      <DependentUpon>GFormatTypeInfoDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GReportDmsInfoDto.d.ts">
      <DependentUpon>GReportDmsInfoDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GReportInfoDto.d.ts">
      <DependentUpon>GReportInfoDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GReportMinimalInfoDto.d.ts">
      <DependentUpon>GReportMinimalInfoDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GReportOutputInfoDto.d.ts">
      <DependentUpon>GReportOutputInfoDto.cs</DependentUpon>
    </None>
    <None Include="Dto\GSablonaKonvenceGordicDto.d.ts">
      <DependentUpon>GSablonaKonvenceGordicDto.cs</DependentUpon>
    </None>
    <None Include="Interfaces\IGSablonaKonvenceGordic.d.ts">
      <DependentUpon>IGSablonaKonvenceGordic.cs</DependentUpon>
    </None>
    <None Include="makara.json" />
    <None Include="Properties\Gordic.Report.Interface.prj.config">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
</Project>
