declare namespace Gordic.Data.Readers {
    /**
    * Reader pro cteni dat číselníku balancování
    * keys : ["priz_nebalanc"]
    * columns: ["priz_nebalanc","priz_nebalanc_txt"]
    * filters: ["priz_nebalanc","priz_nebalanc_txt"]
    */
    class Balanc extends Base<Gordic.Data.Readers.BalancDto>
    {
        constructor(options?: IGReaderBase);
    }
	/**Dto*/
	interface BalancDto {
		/**Autogenerated.*/
		priz_nebalanc?: number|null;
		/**Autogenerated.*/
		priz_nebalanc_txt?: string|null;
	}
	const enum BalancDtoNames { priz_nebalanc = "priz_nebalanc", priz_nebalanc_txt = "priz_nebalanc_txt",}
	const enum BalancDtoFragments { priz_nebalanc = "*", priz_nebalanc_txt = "*",}
	const enum BalancDtoTypes { priz_nebalanc = "number", priz_nebalanc_txt = "string",}
	const enum BalancDtoTypeLengths {}

    /**
    * Reader pro čtení dat číselníku Vztah osoby k požadavku.
    * keys : ["stav_dos"]
    * columns: ["stav_dos", "stav_dos_txt", "k_v", "k_s"]
    * filters: ["stav_dos","stav_dos_txt","k_v","k_s"]
    */
    class Psccdos extends Base<Gordic.Pcn.Interface.GPsccdosDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Viditelnosti míst.
    * keys : ["viditelnost"]
    * columns: ["viditelnost", "viditelnost_txt", "k_v", "k_s"]
    * filters: ["viditelnost","viditelnost_txt","k_v","k_s"]
    */
    class Psccmis extends Base<Gordic.Pcn.Interface.GPsccmisDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Stav požadavku.
    * keys : ["stav_psc"]
    * columns: ["stav_psc", "stav_psc_txt", "k_v", "k_s"]
    * filters: ["stav_psc","stav_psc_txt","k_v","k_s"]
    */
    class Psccpsc extends Base<Gordic.Pcn.Interface.GPsccpscDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Reciprocita nákladů.
    * keys : ["priz_recip"]
    * columns: ["priz_recip", "priz_recip_txt", "k_v", "k_s"]
    * filters: ["priz_recip","priz_recip_txt","k_v","k_s"]
    */
    class Psccrec extends Base<Gordic.Pcn.Interface.GPsccrecDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Typ financování.
    * keys : ["kod_tfz"]
    * columns: ["kod_tfz", "kod_tfz_txt", "k_v", "k_s"]
    * filters: ["kod_tfz","kod_tfz_txt","k_v","k_s"]
    */
    class Pscctfz extends Base<Gordic.Pcn.Interface.GPscctfzDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Typ požadavku plánu.
    * keys : ["typ_poz"]
    * columns: ["typ_poz", "typ_poz_txt", "k_v", "k_s"]
    * filters: ["typ_poz","typ_poz_txt","k_v","k_s"]
    */
    class Pscctyp extends Base<Gordic.Pcn.Interface.GPscctypDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Stav změnového řízení.
    * keys : ["stav_zmr"]
    * columns: ["stav_zmr", "stav_zmr_txt"]
    * filters: ["stav_zmr","stav_zmr_txt","k_v","k_s"]
    */
    class Pscczmr extends Base<Gordic.Pcn.Interface.GPscczmrDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Způsob výpočtu.
    * keys : ["zp_vyp","typ_poz"]
    * columns: ["zp_vyp", "zp_vyp_txt", "k_v", "k_s", "typ_poz"]
    * filters: ["zp_vyp","zp_vyp_txt","k_v","k_s","typ_poz"]
    */
    class Pscczpv extends Base<Gordic.Pcn.Interface.GPscczpvDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Typ změnového řízení.
    * keys : ["typ_zmr"]
    * columns: ["typ_zmr", "typ_zmr_txt", "k_v", "k_s"]
    * filters: ["typ_zmr","typ_zmr_txt","k_v","k_s"]
    */
    class Psccztp extends Base<Gordic.Pcn.Interface.GPsccztpDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Popisy kategorie priorit.
    * keys : ["rok","kat_pri","radek"]
    * columns: ["rok", "kat_pri", "radek", "popis", "aktivita"]
    * filters: ["rok","kat_pri","radek","popis","aktivita"]
    */
    class Pscdkpr extends Base<Gordic.Pcn.Interface.GPscdkprDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Členění.
    * keys : ["ixs_cle","typ_poz","ixp_den"]
    * columns: ["ixs_cle", "nazev", "kod_cle", "poznamka", "typ_poz", "ixp_den", "ixs_vpk", "aktivita", "typ_poz_txt"]
    * filters: ["ixs_cle","nazev","kod_cle","poznamka","aktivita","typ_poz","ixp_den","ixs_vpk"]
    */
    class Pscscle extends Base<Gordic.Pcn.Interface.GPscscleDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Kniha PCN.
    * keys : ["ixp_den"]
    * columns: ["ixp_den", "nazev", "rok", "aktivita", "priz_plan"]
    * filters: ["ixp_den","lic","arw","dat_od","dat_do","ico","ucs","nazev","rok","typ_den","ktg_den","por_cislo_max","subrada_max","subrada_duz","len_ac","krok_uza","ixp_den_old","uus","prefix","suffix","poznamka","aktivita","rok_sberu","priz_plan"]
    */
    class Pscsden extends Base<Gordic.Pcn.Interface.GPscsdenDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Dodatky.
    * keys : ["ixp"]
    * columns: ["ixp", "nazev", "ixp_den", "dat_od", "dat_do", "aktivita", ]
    * filters: ["ixp","ixp_den","nazev","dat_od","dat_do","aktivita"]
    */
    class Pscsdod extends Base<Gordic.Pcn.Interface.GPscsdodDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Kategorie priorit.
    * keys : ["rok","kat_pri"]
    * columns: ["rok", "kat_pri", "nazev", "aktivita"]
    * filters: ["rok","kat_pri","nazev","aktivita"]
    */
    class Pscskpr extends Base<Gordic.Pcn.Interface.GPscskprDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Cílová místa.
    * keys : ["id_misto"]
    * columns: ["id_misto", "misto", "aktivita", "viditelnost"]
    * filters: ["id_misto","misto","aktivita","viditelnost"]
    */
    class Pscsmis extends Base<Gordic.Pcn.Interface.GPscsmisDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Název kategorií hodnocení.
    * keys : ["ico","rok"]
    * columns: ["ico", "rok", "nazev", "aktivita", ]
    * filters: ["ico","rok","nazev","aktivita"]
    */
    class Pscsnkh extends Base<Gordic.Pcn.Interface.GPscsnkhDto>
    {
        constructor(options?: IGReaderBase);
    }

    /**
    * Reader pro čtení dat číselníku Typ náhrad.
    * keys : ["ixs_tna"]
    * columns: ["ixs_tna", "nazev", "ktg_tna", "dat_od", "dat_do", "aktivita", "kod_tna"]
    * filters: ["ixs_tna","ktg_tna","ixs_zpz","nazev","dat_od","dat_do","aktivita","kod_tna","typ_poz"]
    */
    class Pscstna extends Base<Gordic.Pcn.Interface.GPscstnaDto>
    {
        constructor(options?: IGReaderBase);
    }
}
declare namespace Gordic.Prefabs.Select {
    /**
    * Reader pro cteni dat číselníku balancování
    * FieldOptions
    * itemTemplate: "{priz_nebalanc_txt}"
    * helperColumns: ["priz_nebalanc", "priz_nebalanc_txt"]
    *
    * DataReader 
    * keys: ["priz_nebalanc"]
    * columns: ["priz_nebalanc","priz_nebalanc_txt"]
    * filters: ["priz_nebalanc","priz_nebalanc_txt"]
    */
    function balanc(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Data.Readers.BalancDto>): GSelectBoxOptions<Gordic.Data.Readers.BalancDto>;
    /**
    * Reader pro čtení dat číselníku Vztah osoby k požadavku.
    * FieldOptions
    * itemTemplate: "{stav_dos_txt}"
    * helperColumns: ["stav_dos", "stav_dos_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["stav_dos"]
    * columns: ["stav_dos", "stav_dos_txt", "k_v", "k_s"]
    * filters: ["stav_dos","stav_dos_txt","k_v","k_s"]
    */
    function psccdos(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPsccdosDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPsccdosDto>;
    /**
    * Reader pro čtení dat číselníku Viditelnosti míst.
    * FieldOptions
    * itemTemplate: "{viditelnost_txt}"
    * helperColumns: ["viditelnost", "viditelnost_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["viditelnost"]
    * columns: ["viditelnost", "viditelnost_txt", "k_v", "k_s"]
    * filters: ["viditelnost","viditelnost_txt","k_v","k_s"]
    */
    function psccmis(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPsccmisDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPsccmisDto>;
    /**
    * Reader pro čtení dat číselníku Stav požadavku.
    * FieldOptions
    * itemTemplate: "{stav_psc_txt}"
    * helperColumns: ["stav_psc", "stav_psc_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["stav_psc"]
    * columns: ["stav_psc", "stav_psc_txt", "k_v", "k_s"]
    * filters: ["stav_psc","stav_psc_txt","k_v","k_s"]
    */
    function psccpsc(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPsccpscDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPsccpscDto>;
    /**
    * Reader pro čtení dat číselníku Reciprocita nákladů.
    * FieldOptions
    * itemTemplate: "{priz_recip_txt}"
    * helperColumns: ["priz_recip", "priz_recip_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["priz_recip"]
    * columns: ["priz_recip", "priz_recip_txt", "k_v", "k_s"]
    * filters: ["priz_recip","priz_recip_txt","k_v","k_s"]
    */
    function psccrec(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPsccrecDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPsccrecDto>;
    /**
    * Reader pro čtení dat číselníku Typ financování.
    * FieldOptions
    * itemTemplate: "{kod_tfz_txt}"
    * helperColumns: ["kod_tfz", "kod_tfz_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["kod_tfz"]
    * columns: ["kod_tfz", "kod_tfz_txt", "k_v", "k_s"]
    * filters: ["kod_tfz","kod_tfz_txt","k_v","k_s"]
    */
    function pscctfz(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscctfzDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscctfzDto>;
    /**
    * Reader pro čtení dat číselníku Typ požadavku plánu.
    * FieldOptions
    * itemTemplate: "{typ_poz_txt}"
    * helperColumns: ["typ_poz", "typ_poz_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["typ_poz"]
    * columns: ["typ_poz", "typ_poz_txt", "k_v", "k_s"]
    * filters: ["typ_poz","typ_poz_txt","k_v","k_s"]
    */
    function pscctyp(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscctypDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscctypDto>;
    /**
    * Reader pro čtení dat číselníku Stav změnového řízení.
    * FieldOptions
    * itemTemplate: "{stav_zmr_txt}"
    * helperColumns: ["stav_zmr", "stav_zmr_txt"]
    *
    * DataReader 
    * keys: ["stav_zmr"]
    * columns: ["stav_zmr", "stav_zmr_txt"]
    * filters: ["stav_zmr","stav_zmr_txt","k_v","k_s"]
    */
    function pscczmr(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscczmrDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscczmrDto>;
    /**
    * Reader pro čtení dat číselníku Způsob výpočtu.
    * FieldOptions
    * itemTemplate: "{zp_vyp_txt}"
    * helperColumns: ["zp_vyp", "zp_vyp_txt", "k_v", "k_s", "typ_poz"]
    *
    * DataReader 
    * keys: ["zp_vyp","typ_poz"]
    * columns: ["zp_vyp", "zp_vyp_txt", "k_v", "k_s", "typ_poz"]
    * filters: ["zp_vyp","zp_vyp_txt","k_v","k_s","typ_poz"]
    */
    function pscczpv(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscczpvDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscczpvDto>;
    /**
    * Reader pro čtení dat číselníku Typ změnového řízení.
    * FieldOptions
    * itemTemplate: "{typ_zmr_txt}"
    * helperColumns: ["typ_zmr", "typ_zmr_txt", "k_v", "k_s"]
    *
    * DataReader 
    * keys: ["typ_zmr"]
    * columns: ["typ_zmr", "typ_zmr_txt", "k_v", "k_s"]
    * filters: ["typ_zmr","typ_zmr_txt","k_v","k_s"]
    */
    function psccztp(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPsccztpDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPsccztpDto>;
    /**
    * Reader pro čtení dat číselníku Popisy kategorie priorit.
    * FieldOptions
    * itemTemplate: "{popis}"
    * helperColumns: ["rok", "kat_pri", "radek", "popis", "aktivita"]
    *
    * DataReader 
    * keys: ["rok","kat_pri","radek"]
    * columns: ["rok", "kat_pri", "radek", "popis", "aktivita"]
    * filters: ["rok","kat_pri","radek","popis","aktivita"]
    */
    function pscdkpr(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscdkprDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscdkprDto>;
    /**
    * Reader pro čtení dat číselníku Členění.
    * FieldOptions
    * itemTemplate: function
    * helperColumns: ["ixs_cle", "nazev"]
    *
    * DataReader 
    * keys: ["ixs_cle","typ_poz","ixp_den"]
    * columns: ["ixs_cle", "nazev", "kod_cle", "poznamka", "typ_poz", "ixp_den", "ixs_vpk", "aktivita", "typ_poz_txt"]
    * filters: ["ixs_cle","nazev","kod_cle","poznamka","aktivita","typ_poz","ixp_den","ixs_vpk"]
    */
    function pscscle(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscscleDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscscleDto>;
    /**
    * Reader pro čtení dat číselníku Kniha PCN.
    * FieldOptions
    * itemTemplate: function
    * helperColumns: ["nazev", "rok", "ixp_den"]
    *
    * DataReader 
    * keys: ["ixp_den"]
    * columns: ["ixp_den", "nazev", "rok", "aktivita", "priz_plan"]
    * filters: ["ixp_den","lic","arw","dat_od","dat_do","ico","ucs","nazev","rok","typ_den","ktg_den","por_cislo_max","subrada_max","subrada_duz","len_ac","krok_uza","ixp_den_old","uus","prefix","suffix","poznamka","aktivita","rok_sberu","priz_plan"]
    */
    function pscsden(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscsdenDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscsdenDto>;
    /**
    * Reader pro čtení dat číselníku Dodatky.
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ixp", "ixp_den", "nazev", "dat_od", "dat_do", "aktivita", ]
    *
    * DataReader 
    * keys: ["ixp"]
    * columns: ["ixp", "nazev", "ixp_den", "dat_od", "dat_do", "aktivita", ]
    * filters: ["ixp","ixp_den","nazev","dat_od","dat_do","aktivita"]
    */
    function pscsdod(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscsdodDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscsdodDto>;
    /**
    * Reader pro čtení dat číselníku Kategorie priorit.
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["rok", "kat_pri", "nazev", "aktivita"]
    *
    * DataReader 
    * keys: ["rok","kat_pri"]
    * columns: ["rok", "kat_pri", "nazev", "aktivita"]
    * filters: ["rok","kat_pri","nazev","aktivita"]
    */
    function pscskpr(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscskprDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscskprDto>;
    /**
    * Reader pro čtení dat číselníku Cílová místa.
    * FieldOptions
    * itemTemplate: "{misto}"
    * helperColumns: ["id_misto", "misto", "aktivita", "viditelnost"]
    *
    * DataReader 
    * keys: ["id_misto"]
    * columns: ["id_misto", "misto", "aktivita", "viditelnost"]
    * filters: ["id_misto","misto","aktivita","viditelnost"]
    */
    function pscsmis(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscsmisDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscsmisDto>;
    /**
    * Reader pro čtení dat číselníku Název kategorií hodnocení.
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ico", "rok", "nazev", "aktivita", ]
    *
    * DataReader 
    * keys: ["ico","rok"]
    * columns: ["ico", "rok", "nazev", "aktivita", ]
    * filters: ["ico","rok","nazev","aktivita"]
    */
    function pscsnkh(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscsnkhDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscsnkhDto>;
    /**
    * Reader pro čtení dat číselníku Typ náhrad.
    * FieldOptions
    * itemTemplate: "{nazev}"
    * helperColumns: ["ixs_tna", "nazev", "ktg_tna", "dat_od", "dat_do", "aktivita", "kod_tna"]
    *
    * DataReader 
    * keys: ["ixs_tna"]
    * columns: ["ixs_tna", "nazev", "ktg_tna", "dat_od", "dat_do", "aktivita", "kod_tna"]
    * filters: ["ixs_tna","ktg_tna","ixs_zpz","nazev","dat_od","dat_do","aktivita","kod_tna","typ_poz"]
    */
    function pscstna(prefabOptions?: Partial<Gordic.Data.Selectors.UserSelectorOptions> & Gordic.Data.Selectors.DefaultSelectorOptionsType<Gordic.Pcn.Interface.GPscstnaDto>): GSelectBoxOptions<Gordic.Pcn.Interface.GPscstnaDto>;}
declare namespace Gordic.Data.Selectors {
    /**
    * Reader pro čtení dat číselníku Kniha PCN.
    */
    function pscsden(): Selectors.DefaultSelectorOptions<Gordic.Pcn.Interface.GPscsdenDto>;}
