//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordic.GFE.WinClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gordic.GFE.WinClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_box_icon {
            get {
                object obj = ResourceManager.GetObject("check_box_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__App__agx01 {
            get {
                object obj = ResourceManager.GetObject("Icons__App__agx01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Eko__kalkulace_limit {
            get {
                object obj = ResourceManager.GetObject("Icons__Eko__kalkulace_limit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Eko__obdobi_ucetni_edit {
            get {
                object obj = ResourceManager.GetObject("Icons__Eko__obdobi_ucetni_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Eko__prijem {
            get {
                object obj = ResourceManager.GetObject("Icons__Eko__prijem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Eko__sleva {
            get {
                object obj = ResourceManager.GetObject("Icons__Eko__sleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Esu__subjekt_externi_s_gex {
            get {
                object obj = ResourceManager.GetObject("Icons__Esu__subjekt_externi_s_gex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Esu__subjekt_externi_skupina_novy {
            get {
                object obj = ResourceManager.GetObject("Icons__Esu__subjekt_externi_skupina_novy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__akce {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__akce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__akce_aktivni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__akce_aktivni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_info {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_napoveda {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_napoveda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_nastaveni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_nastaveni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_nastaveni_uzivatelske {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_nastaveni_uzivatelske", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_nastaveni_vzhled {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_nastaveni_vzhled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_ukonceni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_ukonceni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__aplikace_vlastnosti {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__aplikace_vlastnosti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__archivni_format {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__archivni_format", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__casove_platne {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__casove_platne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__ciselnik {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__ciselnik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__ciselnik_editace {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__ciselnik_editace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__ciselniky {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__ciselniky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__data_import {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__data_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__databaze {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__databaze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__datova_schranka_zrusit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__datova_schranka_zrusit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__detail {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__detail_edit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__detail_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__dialog_dotaz {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__dialog_dotaz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__dialog_info {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__dialog_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__edit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__editace {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__editace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__fajfka_cervena {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__fajfka_cervena", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__fajfka_zelena {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__fajfka_zelena", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__format_sloupce {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__format_sloupce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__formular {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__formular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__formular_novy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__formular_novy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__graf_kolacovy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__graf_kolacovy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__graf_rozpadovy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__graf_rozpadovy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__graf_sloupcovy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__graf_sloupcovy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__graf_spojnicovy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__graf_spojnicovy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__hledat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__hledat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__hledat_a_nahradit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__hledat_a_nahradit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__hledat_dle_vlastnosti {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__hledat_dle_vlastnosti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__komentar {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__komentar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__kontrola {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__kontrola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__kopirovat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__kopirovat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__likvidace {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__likvidace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__maska_ulozena_vyber {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__maska_ulozena_vyber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__menu_strom {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__menu_strom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__nastaveni_obnovit_vychozi {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__nastaveni_obnovit_vychozi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__nastroje {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__nastroje", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__oblast {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__oblast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__oblibene_vymazat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__oblibene_vymazat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__odebrat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__odebrat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__odstornovat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__odstornovat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__okno_nastaveni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__okno_nastaveni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__okno_odspendlit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__okno_odspendlit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__okno_prispendlit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__okno_prispendlit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__okno_zavrit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__okno_zavrit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__plus {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__plus_centralni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__plus_centralni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__polozka_povinna {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__polozka_povinna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__polozky {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__polozky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__polozky_neplanovane {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__polozky_neplanovane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__polozky_uzamcene {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__polozky_uzamcene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__posun_doprava {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__posun_doprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__posun_maly_dolu {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__posun_maly_dolu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__posun_maly_nahoru {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__posun_maly_nahoru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__predplnit_podaci_cislo {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__predplnit_podaci_cislo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__prehled_ulozene {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__prehled_ulozene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__prepocitat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__prepocitat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__pridat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__pridat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__pridat_sejmutim_pidu {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__pridat_sejmutim_pidu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__pridat_ze_seznamu {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__pridat_ze_seznamu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__priloha {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__priloha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__protokol_zmen {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__protokol_zmen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__prvek_button {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__prvek_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__prvek_checkbox {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__prvek_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__prvek_obrazek {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__prvek_obrazek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__prvek_textbox {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__prvek_textbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__redistribuce {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__redistribuce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__rozpad {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__rozpad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sestava {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sestava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sestava_generovat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sestava_generovat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__seznam_vyber {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__seznam_vyber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_doleva {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_doleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_dolu {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_dolu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_dolu_uplne {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_dolu_uplne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_doprava {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_doprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_nahoru {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_nahoru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_nahoru_uplne {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_nahoru_uplne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sipka_o_polozku_vys {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sipka_o_polozku_vys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__slozka {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__slozka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__slozka_obsahujici {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__slozka_obsahujici", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__slozka_otevrena {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__slozka_otevrena", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__slozka_otevrena_obsahujici {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__slozka_otevrena_obsahujici", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_doc {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_download {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_gor {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_gor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_otevrit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_otevrit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_special {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_special", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_standard {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_standard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_textovy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_textovy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_xls {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_xls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soubor_zip {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soubor_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__soucast_v_typovem_spisu {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__soucast_v_typovem_spisu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__sprava {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__sprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_archivovano {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_archivovano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_castecne_hotovo_barva {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_castecne_hotovo_barva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_hotovo_barva {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_hotovo_barva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_k_archivaci {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_k_archivaci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_odemceno {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_odemceno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_overeni_negativni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_overeni_negativni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_overeni_neprovedeno {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_overeni_neprovedeno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_overeni_pozitivni {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_overeni_pozitivni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_rozlozeno {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_rozlozeno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_uzamceno {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_uzamceno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stav_uzavreno {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stav_uzavreno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__stornovat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__stornovat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__symbol_cislo {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__symbol_cislo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__tabulka {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__tabulka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__tisk_nahled {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__tisk_nahled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__ulozit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__ulozit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__ulozit_do_databaze {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__ulozit_do_databaze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__ulozit_jako {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__ulozit_jako", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__uzivatel_ukon {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__uzivatel_ukon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__validace_varovani {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__validace_varovani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vazba {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vazba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vlastnictvi_moje {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vlastnictvi_moje", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vlastnosti {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vlastnosti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vlozit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vlozit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vratit {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vratit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vyber {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vyber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vyjmout {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vyjmout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__vymazat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__vymazat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__zaznam {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__zaznam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__zaznam_detail {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__zaznam_detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__zaznam_novy {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__zaznam_novy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__zaznam_novy_vlozit_pred {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__zaznam_novy_vlozit_pred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__zaznam_vymazat {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__zaznam_vymazat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__znovuproved {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__znovuproved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Gin__zpet {
            get {
                object obj = ResourceManager.GetObject("Icons__Gin__zpet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__indikator_atribut {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__indikator_atribut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_bottom {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_dokola {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_dokola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_dokola_vnitrek {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_dokola_vnitrek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_horizontalne {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_horizontalne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_left {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_right {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_top {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_vertikalne {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_vertikalne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_vnitrek {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_vnitrek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oramovani_zadne {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oramovani_zadne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__oznacit_barvou_zadnou {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__oznacit_barvou_zadnou", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__presunout_do_popredi {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__presunout_do_popredi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__presunout_do_pozadi {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__presunout_do_pozadi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__presunout_do_tela {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__presunout_do_tela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__radek {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__radek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__registr_uprava_pismen {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__registr_uprava_pismen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__struktura {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__struktura", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__struktura_sprava {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__struktura_sprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__text_zarovnat_doleva {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__text_zarovnat_doleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__text_zarovnat_dolu {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__text_zarovnat_dolu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__text_zarovnat_doprava {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__text_zarovnat_doprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__text_zarovnat_na_stred_horizont {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__text_zarovnat_na_stred_horizont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__text_zarovnat_na_stred_vertikal {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__text_zarovnat_na_stred_vertikal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__text_zarovnat_nahoru {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__text_zarovnat_nahoru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__validace_externi {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__validace_externi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__vlozit_bunku {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__vlozit_bunku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__vlozit_bunku_pred {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__vlozit_bunku_pred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__vlozit_bunku_za {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__vlozit_bunku_za", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__vlozit_radek {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__vlozit_radek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__vlozit_radek_pred {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__vlozit_radek_pred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__vlozit_radek_za {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__vlozit_radek_za", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__xml {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ost__zdrojovy_kod {
            get {
                object obj = ResourceManager.GetObject("Icons__Ost__zdrojovy_kod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ssl__sip_balicek_generovat {
            get {
                object obj = ResourceManager.GetObject("Icons__Ssl__sip_balicek_generovat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ssl__sip_balicek_nacteni {
            get {
                object obj = ResourceManager.GetObject("Icons__Ssl__sip_balicek_nacteni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Ssl__sip_balicek_novy {
            get {
                object obj = ResourceManager.GetObject("Icons__Ssl__sip_balicek_novy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokspis_pid {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokspis_pid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument_editace {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument_editace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument_kopie {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument_kopie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument_novy {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument_novy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument_obsah {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument_obsah", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument_odeslat_original {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument_odeslat_original", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__dokument_vymazat {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__dokument_vymazat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__e_dokument_ulozit {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__e_dokument_ulozit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons__Wfl__priznak_formy_fyzicke_a_hybridni {
            get {
                object obj = ResourceManager.GetObject("Icons__Wfl__priznak_formy_fyzicke_a_hybridni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons_32x32_Pilcrow {
            get {
                object obj = ResourceManager.GetObject("Icons_32x32_Pilcrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons_48x48_LineNumbers {
            get {
                object obj = ResourceManager.GetObject("Icons_48x48_LineNumbers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap priloha {
            get {
                object obj = ResourceManager.GetObject("priloha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radiobutton_icon {
            get {
                object obj = ResourceManager.GetObject("radiobutton_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
